Repository tektoncd/operator, pull requests merged in 2019-10, with the labels that each got.

#45 Add pipeline release v0.6.0 and v0.7.0. Change the default to v0.7.0
  deploy/resources/v0.6.0/release.yaml
  deploy/resources/v0.7.0/release.yaml
  pkg/controller/config/config_controller.go
Labels: approved, lgtm, size/XXL

#47 Bump tektoncd/plumbing dependency ⛽️
  go.mod
  go.sum
  vendor/github.com/tektoncd/plumbing/scripts/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S

#48 Enable Tekton-trigger v0.1.0 as new addon
  README.md
  deploy/crds/operator_v1alpha1_addon_trigger_cr.yaml
  deploy/resources/addons/trigger/v0.1.0/release.yaml
Labels: approved, lgtm, size/L

#52 Correct version in README.md
  README.md
Labels: approved, lgtm, size/XS
