Repository tektoncd/operator, pull requests merged in 2020-04, with the labels that each got.

#76 Adopt pipeline v0.11.0
  README.md
  deploy/resources/v0.11.0/release.yaml
  deploy/role.yaml
  pkg/controller/config/config_controller.go
Labels: approved, lgtm, size/XXL

#81 fix: major bugs in addon_controller.go
  pkg/controller/addon/addon_controller.go
Labels: approved, lgtm, ok-to-test, size/M

#78 Add Triggers v0.4.0 as addon
  README.md
  deploy/crds/operator_v1alpha1_addon_trigger_cr.yaml
  deploy/resources/addons/trigger/v0.4.0/release.yaml
  deploy/role.yaml
Labels: approved, lgtm, size/XL
