Repository tektoncd/operator, pull requests merged in 2020-03, with the labels that each got.

#72 Adds goland files to gitignore
  .gitignore
Labels: approved, lgtm, size/XS

#73 Add Triggers v0.3.1 release as addon
  deploy/crds/operator_v1alpha1_addon_trigger_cr.yaml
  deploy/resources/addons/trigger/v0.3.1/release.yaml
Labels: approved, lgtm, size/XL

#75 cmd/manager: do not set operatorNs
  cmd/manager/main.go
Labels: approved, lgtm, ok-to-test, size/XS
