Repository tektoncd/operator, pull requests merged in 2020-11, with the labels that each got.

#166 Update script to avoid removing vendor OWNERS file
  hack/update-deps.sh
  third_party/VENDOR-LICENSE/github.com/openzipkin/zipkin-go/model/LICENSE
Labels: approved, lgtm, release-note, size/L

#168 add rbac for openshift endpoint
  cmd/openshift/main.go
  pkg/reconciler/openshift/rbac/controller.go
  pkg/reconciler/openshift/rbac/rbac.go
  pkg/reconciler/openshift/tektonpipeline/extension.go
  pkg/reconciler/openshift/tektontrigger/extension.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/namespace/namespace.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/controller.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/reconciler.go
  vendor/knative.dev/pkg/client/injection/kube/reconciler/core/v1/namespace/state.go
  vendor/modules.txt
Labels: approved, lgtm, release-note, size/XXL

#172 Add optional resource to addons
  cmd/openshift/kodata/tekton-addon/0.0.1/05-optional/pipelinesamples/docker_build_deploy.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/05-optional/pipelinesamples/docker_build_deploy_pr.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/05-optional/pipelinesamples/s2i_build_deploy-pr.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/05-optional/pipelinesamples/s2i_build_deploy.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/05-optional/pipelinesamples/simple_pipeline.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/05-optional/tasksnippets/buildah-pr-task-snippet.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/05-optional/tasksnippets/buildah-task-snippet.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/05-optional/tasksnippets/openshift-client-task-snippet.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/05-optional/tasksnippets/s2i-go-pr-task-snippet.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/05-optional/tasksnippets/s2i-go-task-snippet.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/05-optional/tasksnippets/s2i-java-11-pr-task-snippet.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/05-optional/tasksnippets/s2i-java-11-task-snippet.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/05-optional/tasksnippets/s2i-java-8-pr-task-snippet.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/05-optional/tasksnippets/s2i-java-8-task-snippet.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/05-optional/tasksnippets/s2i-nodejs-pr-task-snippet.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/05-optional/tasksnippets/s2i-nodejs-task-snippet.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/05-optional/tasksnippets/s2i-python-3-pr-task-snippet.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/05-optional/tasksnippets/s2i-python-3-task-snippet.yaml
Labels: approved, lgtm, release-note, size/XL

#177 Add some reviewers (main branch)
  OWNERS
Labels: approved, kind/misc, lgtm, release-note-none, size/XS
