Repository tektoncd/operator, pull requests merged in 2020-07, with the labels that each got.

#100 Adopte Trigger v0.6.0
  README.md
  deploy/crds/operator_v1alpha1_addon_trigger_cr.yaml
  deploy/resources/addons/trigger/v0.6.0/release.yaml
Labels: approved, lgtm, size/XL

#102 Update github pull-request template
  .github/pull_request_template.md
Labels: approved, kind/misc, lgtm, size/S

#106 Adopt tekton pipeline v0.14.0
  README.md
  deploy/resources/v0.14.0/release.yaml
  deploy/role.yaml
  pkg/controller/pipeline/pipeline_controller.go
Labels: approved, lgtm, size/XXL

#108 Fix flag in make local-dev target
  Makefile
Labels: approved, lgtm, size/XS

#109 Upgrade manifestival to adopt bug fixing
  go.mod
  go.sum
  vendor/github.com/evanphx/json-patch/v5/LICENSE
  vendor/github.com/evanphx/json-patch/v5/errors.go
  vendor/github.com/evanphx/json-patch/v5/go.mod
  vendor/github.com/evanphx/json-patch/v5/go.sum
  vendor/github.com/evanphx/json-patch/v5/merge.go
  vendor/github.com/evanphx/json-patch/v5/patch.go
  vendor/github.com/golang/protobuf/proto/lib.go
  vendor/github.com/golang/protobuf/proto/text.go
  vendor/github.com/google/gofuzz/README.md
  vendor/github.com/google/gofuzz/fuzz.go
  vendor/github.com/googleapis/gnostic/OpenAPIv2/OpenAPIv2.pb.go
  vendor/github.com/googleapis/gnostic/extensions/extension.pb.go
  vendor/github.com/manifestival/manifestival/.travis.yml
  vendor/github.com/manifestival/manifestival/CHANGELOG.md
  vendor/github.com/manifestival/manifestival/Gopkg.lock
  vendor/github.com/manifestival/manifestival/Gopkg.toml
  vendor/github.com/manifestival/manifestival/README.md
  vendor/github.com/manifestival/manifestival/client.go
  vendor/github.com/manifestival/manifestival/dry.go
  vendor/github.com/manifestival/manifestival/filter.go
  vendor/github.com/manifestival/manifestival/go.mod
  vendor/github.com/manifestival/manifestival/go.sum
  vendor/github.com/manifestival/manifestival/internal/overlay/overlay.go
  vendor/github.com/manifestival/manifestival/internal/patch/patch.go
  vendor/github.com/manifestival/manifestival/internal/sources/path.go
  vendor/github.com/manifestival/manifestival/internal/sources/yaml.go
  vendor/github.com/manifestival/manifestival/manifestival.go
  vendor/github.com/manifestival/manifestival/options.go
  vendor/github.com/manifestival/manifestival/source.go
  vendor/github.com/manifestival/manifestival/transform.go
  vendor/modules.txt
  vendor/sigs.k8s.io/yaml/.travis.yml
  vendor/sigs.k8s.io/yaml/OWNERS
  vendor/sigs.k8s.io/yaml/README.md
  vendor/sigs.k8s.io/yaml/go.mod
  vendor/sigs.k8s.io/yaml/go.sum
  vendor/sigs.k8s.io/yaml/yaml.go
Labels: approved, lgtm, size/XXL

#111 Bump manifestival to v0.6.0
  go.mod
  go.sum
  vendor/github.com/manifestival/controller-runtime-client/Gopkg.lock
  vendor/github.com/manifestival/controller-runtime-client/Gopkg.toml
  vendor/github.com/manifestival/controller-runtime-client/go.mod
  vendor/github.com/manifestival/controller-runtime-client/go.sum
  vendor/github.com/manifestival/manifestival/CHANGELOG.md
  vendor/github.com/manifestival/manifestival/client.go
  vendor/github.com/manifestival/manifestival/dry.go
  vendor/github.com/manifestival/manifestival/go.sum
  vendor/github.com/manifestival/manifestival/manifestival.go
  vendor/golang.org/x/sys/unix/syscall_linux_mips64x.go
  vendor/golang.org/x/sys/unix/syscall_openbsd.go
  vendor/golang.org/x/sys/unix/zerrors_linux_386.go
  vendor/golang.org/x/sys/unix/zerrors_linux_amd64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm.go
  vendor/golang.org/x/sys/unix/zerrors_linux_arm64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mips64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_mipsle.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/zerrors_linux_riscv64.go
  vendor/golang.org/x/sys/unix/zerrors_linux_s390x.go
  vendor/golang.org/x/sys/unix/zerrors_linux_sparc64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_386.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_amd64.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm.go
  vendor/golang.org/x/sys/unix/zsyscall_openbsd_arm64.go
  vendor/golang.org/x/sys/unix/zsysnum_linux_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_386.go
  vendor/golang.org/x/sys/unix/ztypes_linux_amd64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_arm.go
  vendor/golang.org/x/sys/unix/ztypes_linux_arm64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mips64le.go
  vendor/golang.org/x/sys/unix/ztypes_linux_mipsle.go
  vendor/golang.org/x/sys/unix/ztypes_linux_ppc64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_ppc64le.go
  vendor/golang.org/x/sys/unix/ztypes_linux_riscv64.go
  vendor/golang.org/x/sys/unix/ztypes_linux_s390x.go
  vendor/golang.org/x/sys/unix/ztypes_linux_sparc64.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL

#112 Handle changes of labels in pipeline
  pkg/controller/pipeline/pipeline_controller.go
Labels: approved, lgtm, release-note, size/M

#123 Handling changing label in addon
  pkg/controller/addon/addon_controller.go
Labels: approved, lgtm, release-note, size/M

#124 Rename deploy to config in README
  README.md
Labels: approved, lgtm, ok-to-test, release-note-none, size/S

#125 Remove 'https://' from .ko.yaml
  .ko.yaml
Labels: approved, lgtm, release-note-none, size/XS

#122 Add Tasks and Pipeline for Operator release
  config/crds/300-operator_v1alpha1_addon_crd.yaml
  config/crds/300-operator_v1alpha1_pipeline_crd.yaml
  config/operator.yaml
  tekton/create-draft-operator-release.yaml
  tekton/koparse/koparse.py
  tekton/koparse/test_koparse.py
  tekton/koparse/test_release.yaml
  tekton/pipelineresources.yaml
  tekton/publish-tekton-operator-task.yaml
  tekton/release-pipeline.yaml
Labels: approved, lgtm, release-note-none, size/XXL
