Repository tektoncd/operator, pull requests merged in 2020-05, with the labels that each got.

#86 Adopt Pipelines v0.12.0
  README.md
  deploy/resources/v0.12.0/release.yaml
  deploy/role.yaml
  pkg/controller/config/config_controller.go
Labels: approved, lgtm, size/XXL

#85 Bump plumbing to recent master 👼
  go.mod
  go.sum
  vendor/github.com/tektoncd/plumbing/scripts/library.sh
  vendor/github.com/tektoncd/plumbing/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M

#89 Adopt Trigger v0.5.0
  README.md
  deploy/crds/operator_v1alpha1_addon_trigger_cr.yaml
  deploy/resources/addons/trigger/v0.5.0/release.yaml
Labels: approved, lgtm, size/XL

#87 Adopt Dashboard&Webhook for v0.6.1
  README.md
  deploy/crds/operator_v1alpha1_addon_dashboard_cr.yaml
  deploy/crds/operator_v1alpha1_addon_extensionwebhooks_cr.yaml
  deploy/resources/addons/dashboard/v0.6.1/release.yaml
  deploy/resources/addons/extensionwebhooks/v0.6.1/release.yaml
  deploy/role.yaml
Labels: approved, lgtm, size/XXL

#39 Restore the deployment if it is deleted 🧗‍♂️
  pkg/controller/config/config_controller.go
  test/config/constants.go
  test/helpers/helpers.go
  test/testgroups/cluster_crd.go
  test/testsuites/auto_install_pipeline.go
Labels: approved, lgtm, size/M
