Repository tektoncd/operator, pull requests merged in 2020-09, with the labels that each got.

#145 fix unavailable command in develpment doc
  docs/README.md
Labels: approved, lgtm, release-note, size/XS

#146 Avoid multiple useless condition in cr: tektonpipeline
  pkg/controller/pipeline/pipeline_controller.go
Labels: approved, lgtm, release-note, size/XS

#135 Fix local-test-e2e target in Makefile
  Makefile
Labels: approved, lgtm, ok-to-test, release-note-none, size/XS

#151 Add Tektoncd Pipeline v0.16.3
  cmd/manager/kodata/resources/pipelines/v0.16.3/release.notags.yaml
  pkg/controller/pipeline/pipeline_controller.go
Labels: approved, lgtm, release-note, size/L

#154 Remove release-note block indentation in PR template 🌮
  .github/pull_request_template.md
Labels: approved, lgtm, release-note-none, size/S

#152 fix condition duplicated issue for addon
  pkg/controller/addon/addon_controller.go
Labels: approved, lgtm, release-note, size/XS

#157 Fixes tektonpipline status conditions update
  pkg/apis/operator/v1alpha1/common.go
  pkg/apis/operator/v1alpha1/tektonpipeline_lifecycle.go
  pkg/apis/operator/v1alpha1/tektonpipeline_lifecycle_test.go
Labels: approved, lgtm, release-note, size/M

#158 Change of name from cluster to pipeline
  config/crs/operator_v1alpha1_pipeline_cr.yaml
  pkg/reconciler/common/common.go
Labels: approved, lgtm, release-note-none, size/XS
