Repository tektoncd/operator, pull requests merged in 2020-06, with the labels that each got.

#91 Adopte tekton pipeline v0.13.0
  README.md
  deploy/resources/v0.13.0/release.yaml
  pkg/controller/config/config_controller.go
Labels: approved, lgtm, size/XXL

#95 Change `operator-sdk up local` into `operator-sdk run local`
  Makefile
  test/e2e-tests.sh
Labels: approved, lgtm, size/XS

#96 Remove the olm-catalog
  deploy/olm-catalog/tekton-operator/0.5.0/tekton-operator.v0.5.0.clusterserviceversion.yaml
  deploy/olm-catalog/tekton-operator/tekton-operator.package.yaml
Labels: approved, lgtm, size/L

#93 Remove the useless zz_generated.openapi.go
  pkg/apis/operator/v1alpha1/zz_generated.openapi.go
Labels: approved, lgtm, size/L
