Repository tektoncd/operator, pull requests merged in 2021-06, with the labels that each got.

#315 Update profile name default to basic and basic to lite
  Makefile
  README.md
  config/crs/kubernetes/config/lite/operator_v1alpha1_config_cr.yaml
  config/crs/openshift/config/lite/operator_v1alpha1_config_cr.yaml
  pkg/reconciler/common/common.go
  pkg/reconciler/kubernetes/tektonconfig/tektonconfig.go
Labels: approved, lgtm, release-note, size/S

#317 Mount certs at different path than default
  pkg/reconciler/openshift/common/cabundle.go
  pkg/reconciler/openshift/common/cabundle_test.go
  pkg/reconciler/proxy/proxy.go
  pkg/reconciler/proxy/proxy_test.go
Labels: approved, lgtm, release-note, size/M

#323 Bump jib-maven to 0.4 version
  pkg/reconciler/openshift/tektonaddon/tektonaddon.go
Labels: approved, lgtm, release-note, size/XS

#327 Remove imagePullPolicy: Always from the controller 🧙
  config/base/operator.yaml
Labels: approved, lgtm, release-note-none, size/XS

#326 Update README with recent release's link.
  README.md
Labels: approved, lgtm, release-note-none, size/XS

#325 TektonConfig watch namespace event in Openshift
  pkg/reconciler/kubernetes/tektonconfig/controller.go
  pkg/reconciler/openshift/tektonconfig/controller.go
Labels: approved, lgtm, release-note-none, size/M

#321 Update rbac changes to support triggers clusterinterceptors
  pkg/reconciler/openshift/tektonconfig/rbac.go
Labels: approved, lgtm, release-note, size/L

#328 Adds params to customize TektonAddon component on OpenShift
  config/base/300-operator_v1alpha1_addon_crd.yaml
  config/base/300-operator_v1alpha1_config_crd.yaml
  config/crs/openshift/config/all/operator_v1alpha1_config_cr.yaml
  pkg/apis/operator/v1alpha1/common.go
  pkg/apis/operator/v1alpha1/tektonaddon_types.go
  pkg/apis/operator/v1alpha1/tektonconfig_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/common/install.go
  pkg/reconciler/common/install_test.go
  pkg/reconciler/common/validate.go
  pkg/reconciler/common/validate_test.go
  pkg/reconciler/kubernetes/tektonconfig/tektonconfig.go
  pkg/reconciler/kubernetes/tektondashboard/tektondashboard.go
  pkg/reconciler/kubernetes/tektonpipeline/tektonpipeline.go
  pkg/reconciler/kubernetes/tektontrigger/tektontrigger.go
  pkg/reconciler/openshift/tektonaddon/tektonaddon.go
  pkg/reconciler/openshift/tektonconfig/extension.go
  pkg/reconciler/openshift/tektonconfig/extension/addon.go
  test/e2e/common/tektonconfigdeployment_test.go
  test/e2e/common/tektonpipelinedeployment_test.go
  test/e2e/common/tektontriggerdeployment_test.go
  test/e2e/openshift/tektonaddondeployment_test.go
Labels: approved, lgtm, release-note, size/XL

#332 Fix the cp command in the release publish task
  tekton/bases/build-publish-images-manifests.yaml
Labels: approved, lgtm, release-note-none, size/XS

#335 [OpenShift] Update payloads for 1.5 release
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/01-clustertriggerbindings/bitbucket.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/01-clustertriggerbindings/cluster-role.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/01-clustertriggerbindings/cluster-rolebinding.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/01-clustertriggerbindings/github.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/01-clustertriggerbindings/gitlab.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/02-clustertasks/buildah/buildah-1-5-0-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/02-clustertasks/buildah/buildah-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/02-clustertasks/cluster-role.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/02-clustertasks/cluster-rolebinding.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/02-clustertasks/git-clone/git-clone-1-5-0-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/02-clustertasks/git-clone/git-clone-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/02-clustertasks/kn-apply/kn-apply-1-5-0-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/02-clustertasks/kn-apply/kn-apply-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/02-clustertasks/kn/kn-1-5-0-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/02-clustertasks/kn/kn-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/02-clustertasks/openshift-client/openshift-client-1-5-0-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/02-clustertasks/openshift-client/openshift-client-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/02-clustertasks/s2i-dotnet/s2i-dotnet-1-5-0-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/02-clustertasks/s2i-dotnet/s2i-dotnet-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/02-clustertasks/s2i-go/s2i-go-1-5-0-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/02-clustertasks/s2i-go/s2i-go-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/02-clustertasks/s2i-java/s2i-java-1-5-0-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/02-clustertasks/s2i-java/s2i-java-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/02-clustertasks/s2i-nodejs/s2i-nodejs-1-5-0-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/02-clustertasks/s2i-nodejs/s2i-nodejs-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/02-clustertasks/s2i-perl/s2i-perl-1-5-0-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/02-clustertasks/s2i-perl/s2i-perl-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/02-clustertasks/s2i-php/s2i-php-1-5-0-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/02-clustertasks/s2i-php/s2i-php-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/02-clustertasks/s2i-python/s2i-python-1-5-0-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/02-clustertasks/s2i-python/s2i-python-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/02-clustertasks/s2i-ruby/s2i-ruby-1-5-0-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/02-clustertasks/s2i-ruby/s2i-ruby-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/02-clustertasks/skopeo-copy/skopeo-copy-1-5-0-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/02-clustertasks/skopeo-copy/skopeo-copy-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/02-clustertasks/tkn/tkn-1-5-0-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/02-clustertasks/tkn/tkn-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/03-pipelines/cluster-role.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/03-pipelines/role.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/03-pipelines/rolebinding.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/04-consolecli/console_cli_download_tkn.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/optional/quickstarts/install-associate-pipeline-quickstart.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/optional/samples/pipelinesamples/docker_build_deploy.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/optional/samples/pipelinesamples/s2i_build_deploy.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/optional/samples/pipelinesamples/simple_pipeline.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/optional/samples/tasksnippets/buildah-task-snippet.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/optional/samples/tasksnippets/openshift-client-task-snippet.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/optional/samples/tasksnippets/s2i-go-task-snippet.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/optional/samples/tasksnippets/s2i-java-task-snippet.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/optional/samples/tasksnippets/s2i-nodejs-task-snippet.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/optional/samples/tasksnippets/s2i-python-task-snippet.yaml
  cmd/openshift/operator/kodata/tekton-pipeline/0.24.3/00_tektoncd-pipeline-v0.24.3.yaml
  cmd/openshift/operator/kodata/tekton-pipeline/0.24.3/01-clusterrole.yaml
  cmd/openshift/operator/kodata/tekton-pipeline/0.24.3/02-rolebinding.yaml
  cmd/openshift/operator/kodata/tekton-trigger/0.14.2/01_tektoncd-triggers-v0.14.2.yaml
  cmd/openshift/operator/kodata/tekton-trigger/0.14.2/02_tektoncd-triggers-interceptor-v0.14.2.yaml
  config/base/operator.yaml.orig
  config/openshift/operator.yaml
  hack/openshift/update-tasks.sh
Labels: approved, lgtm, release-note, size/XXL

#337 Fix tkn task label
  pkg/reconciler/openshift/tektonaddon/tektonaddon.go
Labels: approved, lgtm, release-note, size/XS
