Repository tektoncd/operator, pull requests merged in 2021-08, with the labels that each got.

#371 [OpenShift] Removes external reference in openshift payload
  pkg/reconciler/openshift/common/testdata/test-prefix-images-expected.yaml
  pkg/reconciler/openshift/common/transformer.go
  pkg/reconciler/openshift/common/transformer_test.go
  pkg/reconciler/openshift/tektonpipeline/extension.go
  pkg/reconciler/openshift/tektontrigger/extension.go
Labels: approved, lgtm, release-note, size/M

#373 Cleanup: Removes unused file and code
  config/base/operator.yaml.orig
  pkg/reconciler/common/releases.go
  pkg/reconciler/common/transformers.go
  pkg/reconciler/openshift/common/transformer.go
  pkg/reconciler/openshift/tektonpipeline/extension.go
Labels: approved, lgtm, release-note, size/M

#340 Append OwnerReference if already exists
  pkg/reconciler/openshift/tektonconfig/rbac.go
Labels: approved, lgtm, size/M, release-note-none

#376 Update release pipelines by adding payload fetch Task
  Makefile
  cmd/kubernetes/operator/kodata/tekton-dashboard/0.12.0/tekton-dashboard-release.yaml
  cmd/kubernetes/operator/kodata/tekton-dashboard/0.14.0/tekton-dashboard-release.yaml
  cmd/kubernetes/operator/kodata/tekton-dashboard/0.16.0/tekton-dashboard-release.yaml
  cmd/kubernetes/operator/kodata/tekton-dashboard/0.16.1/tekton-dashboard-release.yaml
  cmd/kubernetes/operator/kodata/tekton-dashboard/0.8.2/tekton-dashboard-release.yaml
  cmd/kubernetes/operator/kodata/tekton-result/0.2.0/release.yaml
  hack/fetch-releases.sh
  pkg/reconciler/common/releases.go
  tekton/build-publish-images-manifests.yaml
  tekton/kustomization.yaml
  tekton/operator-release-pipeline.yaml
  tekton/overlays/nightly-releases/fetch-nightly-components.yaml
  tekton/overlays/nightly-releases/kustomization.yaml
  tekton/overlays/nightly-releases/operator-nightly-release-pipeline.yaml
  tekton/overlays/versioned-releases/kustomization.yaml
  tekton/task-fetch-components.yaml
Labels: approved, lgtm, release-note, size/XXL

#380 Add METRICS_DOMAIN env in Deployments
  config/base/operator.yaml
  config/base/webhook.yaml
Labels: approved, size/XS, lgtm, release-note

#378 [OpenShift] Add triggers defaults in CR instead of transformers
  pkg/apis/operator/v1alpha1/tektonconfig_types.go
  pkg/apis/operator/v1alpha1/tektontrigger_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/common/common.go
  pkg/reconciler/kubernetes/tektonconfig/trigger/trigger.go
  pkg/reconciler/kubernetes/tektonconfig/trigger/trigger_test.go
  pkg/reconciler/kubernetes/tektontrigger/tektontrigger.go
  pkg/reconciler/openshift/tektonconfig/extension.go
  pkg/reconciler/openshift/tektonpipeline/extension.go
  pkg/reconciler/openshift/tektontrigger/extension.go
Labels: approved, lgtm, release-note, size/L

#383 Removes the manifests on cleaning up using `make clean`
  Makefile
Labels: approved, lgtm, size/S, release-note

#384 config: replace any wildcard verbs by a list
  config/base/role.yaml
  config/openshift/role.yaml
Labels: approved, lgtm, release-note, size/L

#386 [OpenShift] Fixes failures on OpenShift
  hack/fetch-releases.sh
Labels: approved, size/XS, lgtm, release-note

#377 [OpenShift] fixes the disable affinity assistant configuration
  pkg/apis/operator/v1alpha1/tektonpipeline_defaults.go
  pkg/apis/operator/v1alpha1/tektonpipeline_defaults_test.go
  pkg/reconciler/openshift/tektonpipeline/extension.go
Labels: approved, lgtm, size/S, release-note

#382 Use release version for `operator.tekton.dev/release` label value
  tekton/build-publish-images-manifests.yaml
Labels: approved, size/XS, lgtm, release-note, ok-to-test

#389 [OpenShift] Fixes rbac for Operator service account
  config/openshift/role.yaml
Labels: approved, size/XS, lgtm, release-note

#241 Add an inital ROADMAP for the operator
  ROADMAP.md
Labels: approved, lgtm, size/M, release-note-none
