Repository tektoncd/operator, pull requests merged in 2021-03, with the labels that each got.

#238 Add option to run tests on non-Intel architectures
  Makefile
  test/e2e-tests.sh
Labels: approved, lgtm, release-note-none, size/S

#244 Update component versions
  cmd/kubernetes/operator/kodata/tekton-dashboard/0.14.0/tekton-dashboard-release.yaml
  cmd/kubernetes/operator/kodata/tekton-pipeline/0.21.0/release.notags.yaml
  cmd/kubernetes/operator/kodata/tekton-trigger/0.11.2/release.notags.yaml
Labels: approved, lgtm, release-note, size/XXL

#234 Fix pipeline quickstart content
  cmd/openshift/operator/kodata/tekton-addon/0.0.1/optional/quickstarts/install-associate-pipeline-quickstart.yaml
Labels: approved, lgtm, ok-to-test, release-note, size/XS

#245 Add clustertriggerbinding for GitLab
  cmd/openshift/operator/kodata/tekton-addon/0.0.1/addons/01-clustertriggerbindings/gitlab.yaml
Labels: approved, lgtm, release-note, size/L

#243 Refactor release pipeline
  README.md
  tekton/README.md
  tekton/build-publish-images-manifests.yaml
  tekton/create-draft-operator-release.yaml
  tekton/koparse/koparse.py
  tekton/koparse/test_koparse.py
  tekton/koparse/test_release.yaml
  tekton/kustomization.yaml
  tekton/operator-release-pipeline.yaml
  tekton/pipelineresources.yaml
  tekton/publish-tekton-operator-task.yaml
  tekton/release-cheat-sheet.md
  tekton/release-pipeline.yaml
  tekton/setup-release-from-scratch.md
Labels: approved, lgtm, release-note, size/XXL

#248 Add documentation for proxy support
  docs/proxy.md
Labels: approved, lgtm, release-note, size/M

#250 Add an improved nightly release pipeline
  tekton/README.md
  tekton/bases/build-publish-images-manifests.yaml
  tekton/bases/kustomization.yaml
  tekton/overlays/nightly-releases/fetch-nightly-components.yaml
  tekton/overlays/nightly-releases/kustomization.yaml
  tekton/overlays/nightly-releases/operator-nightly-release-pipeline.yaml
  tekton/overlays/versioned-releases/kustomization.yaml
  tekton/overlays/versioned-releases/operator-release-pipeline.yaml
Labels: approved, lgtm, release-note, size/L

#251 Remove `operator-` prefix from nightly release pipeline
  tekton/overlays/nightly-releases/operator-nightly-release-pipeline.yaml
Labels: approved, lgtm, release-note, size/XS

#252 Fix operator nightly payload version naming
  tekton/overlays/nightly-releases/fetch-nightly-components.yaml
Labels: approved, lgtm, release-note, size/XS

#253 Fix wrong path in fetch nightly
  tekton/overlays/nightly-releases/fetch-nightly-components.yaml
Labels: approved, lgtm, release-note, size/XS

#256 Update tkn links for ConsoleCLIDownload
  cmd/openshift/operator/kodata/tekton-addon/0.0.1/addons/04-consolecli/console_cli_download_tkn.yaml
Labels: approved, lgtm, release-note, size/S

#259 Update workqueue name for annotation webhook
  pkg/reconciler/openshift/annotation/controller.go
Labels: approved, lgtm, release-note, size/XS

#257 Add ca cert volume mounts to taskrun pods
  pkg/reconciler/proxy/proxy.go
  pkg/reconciler/proxy/proxy_test.go
Labels: approved, lgtm, release-note, size/L

#240 openshift: move pipeline sa to restricted instead of anyuid
  pkg/reconciler/openshift/rbac/rbac.go
Labels: approved, lgtm, release-note, size/M

#260 remove duplicate sample tasks
  cmd/openshift/kodata/tekton-addon/0.0.1/optional/samples/tasksnippets/s2i-java-task-snippet.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/optional/samples/tasksnippets/s2i-python-task-snippet.yaml
Labels: approved, lgtm, release-note, size/M

#255 Add kn-apply ct and install kn related ct only on amd64
  cmd/openshift/operator/kodata/tekton-addon/0.0.1/addons/02-clustertasks/kn-apply/kn-apply-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/0.0.1/addons/02-clustertasks/kn-apply/kn-apply-v0-19-0-task.yaml
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/pipelinetemplates.go
  pkg/reconciler/openshift/tektonaddon/tektonaddon.go
Labels: approved, lgtm, release-note, size/M

#263 Update addons version
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/addons/01-clustertriggerbindings/bitbucket.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/addons/01-clustertriggerbindings/cluster-role.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/addons/01-clustertriggerbindings/cluster-rolebinding.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/addons/01-clustertriggerbindings/github.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/addons/01-clustertriggerbindings/gitlab.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/addons/02-clustertasks/buildah/buildah-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/addons/02-clustertasks/buildah/buildah-v0-19-0-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/addons/02-clustertasks/cluster-role.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/addons/02-clustertasks/cluster-rolebinding.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/addons/02-clustertasks/git-clone/git-clone-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/addons/02-clustertasks/git-clone/git-clone-v0-19-0-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/addons/02-clustertasks/kn/kn-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/addons/02-clustertasks/kn/kn-v0-19-0-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/addons/02-clustertasks/openshift-client/openshift-client-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/addons/02-clustertasks/openshift-client/openshift-client-v0-19-0-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/addons/02-clustertasks/s2i-dotnet/s2i-dotnet-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/addons/02-clustertasks/s2i-dotnet/s2i-dotnet-v0-19-0-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/addons/02-clustertasks/s2i-go/s2i-go-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/addons/02-clustertasks/s2i-go/s2i-go-v0-19-0-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/addons/02-clustertasks/s2i-java/s2i-java-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/addons/02-clustertasks/s2i-java/s2i-java-v0-19-0-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/addons/02-clustertasks/s2i-nodejs/s2i-nodejs-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/addons/02-clustertasks/s2i-nodejs/s2i-nodejs-v0-19-0-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/addons/02-clustertasks/s2i-perl/s2i-perl-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/addons/02-clustertasks/s2i-perl/s2i-perl-v0-19-0-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/addons/02-clustertasks/s2i-php/s2i-php-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/addons/02-clustertasks/s2i-php/s2i-php-v0-19-0-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/addons/02-clustertasks/s2i-python/s2i-python-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/addons/02-clustertasks/s2i-python/s2i-python-v0-19-0-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/addons/02-clustertasks/s2i-ruby/s2i-ruby-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/addons/02-clustertasks/s2i-ruby/s2i-ruby-v0-19-0-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/addons/02-clustertasks/skopeo-copy/skopeo-copy-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/addons/02-clustertasks/skopeo-copy/skopeo-copy-v0-19-0-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/addons/03-pipelines/cluster-role.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/addons/03-pipelines/role.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/addons/03-pipelines/rolebinding.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/addons/04-consolecli/console_cli_download_tkn.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/optional/quickstarts/install-associate-pipeline-quickstart.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/optional/samples/pipelinesamples/docker_build_deploy.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/optional/samples/pipelinesamples/s2i_build_deploy.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/optional/samples/pipelinesamples/simple_pipeline.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/optional/samples/tasksnippets/buildah-task-snippet.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/optional/samples/tasksnippets/openshift-client-task-snippet.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/optional/samples/tasksnippets/s2i-go-task-snippet.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/optional/samples/tasksnippets/s2i-java-task-snippet.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/optional/samples/tasksnippets/s2i-nodejs-task-snippet.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/optional/samples/tasksnippets/s2i-python-task-snippet.yaml
Labels: approved, lgtm, release-note, size/XS

#261 Fix e2e compilation issue for Openshift
  test/e2e/openshift/rbac_test.go
  test/resources/rbac.go
Labels: approved, lgtm, release-note, size/S

#264 Add pipeline v0.22.0 and triggers v0.12.1 for openshift
  cmd/openshift/operator/kodata/tekton-pipeline/0.22.0/00_tektoncd-pipeline-v0.22.0.yaml
  cmd/openshift/operator/kodata/tekton-pipeline/0.22.0/01-clusterrole.yaml
  cmd/openshift/operator/kodata/tekton-pipeline/0.22.0/02-rolebinding.yaml
  cmd/openshift/operator/kodata/tekton-trigger/v0.12.1/tektoncd-triggers-v0.12.1.yaml
Labels: approved, lgtm, release-note, size/XXL

#268 Remove obsolete Config CRD instance cleanup job
  cmd/openshift/operator/kodata/tekton-config/99-clean-up/01-tekton-config-post-install-jobs.yaml
  pkg/reconciler/openshift/tektonconfig/extension.go
  pkg/reconciler/openshift/tektonconfig/extension/openshift_cleanup.go
Labels: approved, lgtm, release-note, size/L

#269 Change base image for openshift platform
  .ko.yaml
Labels: approved, lgtm, release-note, size/XS

#270 Add changes to enable TLS encryption based on label
  pkg/reconciler/openshift/annotation/annotation.go
Labels: approved, lgtm, release-note, size/XS

#271 Update some release docs based on latest release 🧲
  README.md
  tekton/release-cheat-sheet.md
  tekton/setup-release-from-scratch.md
Labels: approved, lgtm, release-note-none, size/M

#272 Update folder name for 0.12.1
  cmd/openshift/operator/kodata/tekton-trigger/0.12.1/tektoncd-triggers-v0.12.1.yaml
Labels: approved, lgtm, release-note, size/XS

#274 openshift: move pipeline sa bounded scc back to anyuid
  pkg/reconciler/openshift/rbac/rbac.go
Labels: approved, lgtm, release-note, size/M
