Repository tektoncd/operator, pull requests merged in 2021-01, with the labels that each got.

#201 Add condition to verify existence of TektonConfig CR
  pkg/reconciler/openshift/tektonconfig/controller.go
Labels: approved, lgtm, release-note, size/XS

#204 Remove WATCH_NAMESPACE env from deployment yaml
  config/base/operator.yaml
Labels: approved, lgtm, release-note, size/XS

#203 Add permission to consolequickstarts
  config/base/role.yaml
  config/openshift/role.yaml
Labels: approved, lgtm, release-note, size/S

#199 Add label for ClusterTask and image replacement for Controller
  pkg/reconciler/common/testdata/test-inject-label-kind-set.yaml
  pkg/reconciler/common/testdata/test-inject-label-overwrite.yaml
  pkg/reconciler/common/testdata/test-inject-label.yaml
  pkg/reconciler/common/testdata/test-replace-addon-image.yaml
  pkg/reconciler/common/testdata/test-replace-image.yaml
  pkg/reconciler/common/testdata/test-replace-kind.yaml
  pkg/reconciler/common/transformers.go
  pkg/reconciler/common/transformers_test.go
  pkg/reconciler/openshift/tektonaddon/extension.go
  pkg/reconciler/openshift/tektonaddon/tektonaddon.go
  pkg/reconciler/openshift/tektonpipeline/extension.go
  pkg/reconciler/openshift/tektontrigger/extension.go
Labels: approved, lgtm, release-note, size/XL

#206 Remove unused CR from kubernetes config
  config/crs/kubernetes/addon/operator_v1alpha1_addon_cr.yaml
Labels: approved, lgtm, release-note, size/S

#202 webhook yaml
  cmd/proxy/main.go
  config/base/kustomization.yaml
  config/base/proxy_cluster_role.yaml
  config/base/proxy_cluster_role_binding.yaml
  config/base/proxy_role.yaml
  config/base/proxy_role_binding.yaml
  config/base/proxy_secret.yaml
  config/base/proxy_service.yaml
  config/base/proxy_service_account.yaml
  config/base/proxy_webhook.yaml
  config/base/proxy_webhook_config.yaml
  config/kubernetes/kustomization.yaml
  config/kubernetes/proxy_webhook.yaml
  config/openshift/kustomization.yaml
  config/openshift/proxy_cluster_role_binding.yaml
  config/openshift/proxy_role_binding.yaml
  config/openshift/proxy_webhook_config.yaml
Labels: approved, lgtm, release-note, size/L

#207 remove STORAGE_DRIVER env from buildah-pr
  cmd/openshift/kodata/tekton-addon/0.0.1/02-clustertasks/buildah-pr/buildah-pr-task.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/02-clustertasks/buildah-pr/buildah-pr-v0-19-0-task.yaml
Labels: approved, lgtm, release-note, size/S

#208 Remove CRDs during uninstallation of owner component
  pkg/reconciler/common/install.go
  pkg/reconciler/common/install_test.go
Labels: approved, lgtm, release-note, size/XS

#210 Update proxy reconciller for empty value env
  pkg/reconciler/proxy/proxy.go
Labels: approved, lgtm, release-note, size/M

#211 Improve seamless upgrade on openshift
  cmd/openshift/kodata/tekton-config/99-clean-up/01-tekton-config-post-install-jobs.yaml
  pkg/reconciler/common/install.go
Labels: approved, lgtm, release-note, size/M

#212 Change image url in cleanup job on OpenShift
  cmd/openshift/kodata/tekton-config/99-clean-up/01-tekton-config-post-install-jobs.yaml
Labels: approved, lgtm, release-note, size/XS

#214 fix buildah test failure
  cmd/openshift/kodata/tekton-addon/0.0.1/02-clustertasks/buildah/buildah-task.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/02-clustertasks/buildah/buildah-v0-19-0-task.yaml
Labels: approved, lgtm, release-note, size/S

#213 Improve autoinstall mechanism for OpenShift
  cmd/openshift/kodata/tekton-config/99-clean-up/01-tekton-config-post-install-jobs.yaml
  pkg/reconciler/openshift/tektonconfig/controller.go
  pkg/reconciler/openshift/tektonconfig/extension.go
Labels: approved, lgtm, release-note, size/L

#215 Handle `manifestival.ManifestFrom` errors
  pkg/reconciler/kubernetes/tektonconfig/controller.go
  pkg/reconciler/kubernetes/tektondashboard/controller.go
  pkg/reconciler/kubernetes/tektonpipeline/controller.go
  pkg/reconciler/kubernetes/tektontrigger/controller.go
  pkg/reconciler/openshift/rbac/controller.go
  pkg/reconciler/openshift/tektonaddon/controller.go
Labels: approved, lgtm, ok-to-test, release-note-none, size/M

#216 Add and Update tkn links in ConsoleCLIDownload
  cmd/openshift/kodata/tekton-addon/0.0.1/04-consolecli/console_cli_download_tkn.yaml
Labels: approved, lgtm, release-note, size/S

#217 Fix e2e tests script failure on OpenShift
  test/e2e-common.sh
Labels: approved, lgtm, release-note, size/XS

#222 Modify 0.19.0 pipeline release.yaml
  cmd/openshift/kodata/tekton-pipeline/0.19.0/tektoncd-pipeline-v0.19.0.yaml
Labels: approved, lgtm, release-note, size/XS

#223 use imagestream from internal registry
  cmd/openshift/kodata/tekton-addon/0.0.1/addons/02-clustertasks/s2i-perl-pr/s2i-perl-pr-task.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/addons/02-clustertasks/s2i-perl-pr/s2i-perl-pr-v0-19-0-task.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/addons/02-clustertasks/s2i-perl/s2i-perl-task.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/addons/02-clustertasks/s2i-perl/s2i-perl-v0-19-0-task.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/addons/02-clustertasks/s2i-python-3-pr/s2i-python-3-pr-task.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/addons/02-clustertasks/s2i-python-3-pr/s2i-python-3-pr-v0-19-0-task.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/addons/02-clustertasks/s2i-python-3/s2i-python-3-task.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/addons/02-clustertasks/s2i-python-3/s2i-python-3-v0-19-0-task.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/addons/02-clustertasks/s2i-ruby-pr/s2i-ruby-pr-task.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/addons/02-clustertasks/s2i-ruby-pr/s2i-ruby-pr-v0-19-0-task.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/addons/02-clustertasks/s2i-ruby/s2i-ruby-task.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/addons/02-clustertasks/s2i-ruby/s2i-ruby-v0-19-0-task.yaml
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/pipelinetemplates.go
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-perl-deployment-pr.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-perl-deployment.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-perl-knative-pr.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-perl-knative.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-perl-pr.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-perl.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-python-3-deployment-pr.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-python-3-deployment.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-python-3-knative-pr.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-python-3-knative.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-python-3-pr.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-python-3.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-ruby-deployment-pr.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-ruby-deployment.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-ruby-knative-pr.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-ruby-knative.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-ruby-pr.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-ruby.golden
Labels: approved, lgtm, release-note, size/M

#221 Restructure proxy installation
  cmd/kubernetes/kodata/proxy/proxy.yaml
  cmd/openshift/kodata/proxy/proxy.yaml
  config/base/kustomization.yaml
  config/base/operator.yaml
  config/base/proxy_cluster_role.yaml
  config/base/proxy_cluster_role_binding.yaml
  config/base/proxy_role.yaml
  config/base/proxy_role_binding.yaml
  config/base/proxy_secret.yaml
  config/base/proxy_service.yaml
  config/base/proxy_service_account.yaml
  config/base/proxy_webhook.yaml
  config/base/proxy_webhook_config.yaml
  config/kubernetes/kustomization.yaml
  config/kubernetes/proxy_webhook.yaml
  config/openshift/kustomization.yaml
  config/openshift/proxy_cluster_role_binding.yaml
  config/openshift/proxy_role_binding.yaml
  config/openshift/proxy_webhook_config.yaml
  pkg/reconciler/common/releases.go
  pkg/reconciler/kubernetes/tektonpipeline/tektonpipeline.go
  pkg/reconciler/openshift/tektonaddon/tektonaddon.go
  pkg/reconciler/openshift/tektonpipeline/extension.go
Labels: approved, lgtm, release-note, size/XL
