Repository tektoncd/operator, pull requests merged in 2021-05, with the labels that each got.

#303 Update knative deploy task
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/pipelinetemplates.go
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/buildah-knative.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-dotnet-knative.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-go-knative.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-java-knative.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-nodejs-knative.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-perl-knative.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-php-knative.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-python-knative.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-ruby-knative.golden
Labels: approved, lgtm, release-note, size/S

#284 Update proxy imlementation to give priority when proxy set at pipelinerun/taskrun
  pkg/reconciler/proxy/proxy.go
Labels: approved, lgtm, release-note, size/M

#308 Update plumbing dependency 🪧
  go.mod
  go.sum
  vendor/github.com/tektoncd/plumbing/scripts/e2e-tests.sh
  vendor/github.com/tektoncd/plumbing/scripts/library.sh
  vendor/modules.txt
Labels: approved, kind/misc, lgtm, release-note-none, size/M

#309 [OpenShift]Change secretname to use same as el servicename
  pkg/reconciler/openshift/annotation/annotation.go
Labels: approved, kind/bug, lgtm, release-note

#313 Fixes E2E test for TektonConfig
  test/e2e/common/tektonconfigdeployment_test.go
  test/e2e/openshift/rbac_test.go
  test/resources/tektonconfigs.go
Labels: approved, lgtm, release-note, size/S
