Repository tektoncd/operator, pull requests merged in 2021-04, with the labels that each got.

#275 Fix tiny typo in the main README 🙏
  README.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/XS

#277 Update tkn binary links to 0.17.1
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/addons/04-consolecli/console_cli_download_tkn.yaml
Labels: approved, lgtm, release-note, size/S

#276 Add docs link for v0.22.0-1
  README.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/XS

#279 Bump Community Task Versions for OpenShift
  pkg/reconciler/openshift/tektonaddon/tektonaddon.go
Labels: approved, lgtm, release-note, size/XS

#281 Update tkn links to 0.17.2
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/addons/04-consolecli/console_cli_download_tkn.yaml
Labels: approved, lgtm, release-note, size/S

#283 [openshift] Add mechamism to cleanup RBAC from TP1.2 builds
  pkg/reconciler/openshift/tektonconfig/extension/cleanup-clusterrole-rolebinding.go
Labels: approved, lgtm, release-note, size/S

#286 Bump pluming to latest main 🧲
  go.mod
  go.sum
  vendor/github.com/tektoncd/plumbing/.gitignore
  vendor/github.com/tektoncd/plumbing/CONTRIBUTING.md
  vendor/github.com/tektoncd/plumbing/DEVELOPMENT.md
  vendor/github.com/tektoncd/plumbing/README.md
  vendor/github.com/tektoncd/plumbing/adjustpermissions.py
  vendor/github.com/tektoncd/plumbing/scripts/README.md
  vendor/github.com/tektoncd/plumbing/scripts/deploy-release.sh
  vendor/github.com/tektoncd/plumbing/scripts/e2e-tests.sh
  vendor/github.com/tektoncd/plumbing/scripts/library.sh
  vendor/github.com/tektoncd/plumbing/scripts/presubmit-tests.sh
  vendor/modules.txt
Labels: approved, lgtm, release-note-none, size/L

#292 Add Savita as OWNER of the project 🦉
  OWNERS
Labels: approved, lgtm, release-note-none, size/XS

#295 Add 0.22.0-2 to README 🧾
  README.md
Labels: approved, kind/documentation, lgtm, release-note-none, size/XS

#290 Remove serving references in CRDs 🧣
  config/base/300-operator_v1alpha1_addon_crd.yaml
  config/base/300-operator_v1alpha1_config_crd.yaml
  config/base/300-operator_v1alpha1_dashboard_crd.yaml
  config/base/300-operator_v1alpha1_pipeline_crd.yaml
  config/base/300-operator_v1alpha1_trigger_crd.yaml
  pkg/reconciler/kubernetes/tektondashboard/tektondashboard.go
  pkg/reconciler/kubernetes/tektonpipeline/tektonpipeline.go
  pkg/reconciler/kubernetes/tektontrigger/tektontrigger.go
  pkg/reconciler/openshift/tektonaddon/tektonaddon.go
Labels: approved, kind/cleanup, lgtm, release-note-none, size/S

#297 Update pipeline quickstart content
  cmd/openshift/operator/kodata/tekton-addon/1.4.0/optional/quickstarts/install-associate-pipeline-quickstart.yaml
Labels: approved, lgtm, ok-to-test, release-note, size/S

#291 Update tekton payloads for kubernetes platform 📦
  cmd/kubernetes/operator/kodata/tekton-dashboard/0.16.0/tekton-dashboard-release.yaml
  cmd/kubernetes/operator/kodata/tekton-dashboard/0.16.1/tekton-dashboard-release.yaml
  cmd/kubernetes/operator/kodata/tekton-pipeline/0.22.0/release.notags.yaml
  cmd/kubernetes/operator/kodata/tekton-pipeline/0.23.0/release.notags.yaml
  cmd/kubernetes/operator/kodata/tekton-trigger/0.12.0/release.notags.yaml
  cmd/kubernetes/operator/kodata/tekton-trigger/0.12.1/release.notags.yaml
  cmd/kubernetes/operator/kodata/tekton-trigger/0.13.0/release.notags.yaml
  config/base/role.yaml
Labels: approved, lgtm, release-note, size/XXL
