Repository tektoncd/operator, pull requests merged in 2021-02, with the labels that each got.

#225 Add label on tekton namespace to avoid proxy webhook
  pkg/reconciler/common/proxy.go
  pkg/reconciler/kubernetes/tektonpipeline/tektonpipeline.go
  pkg/reconciler/proxy/proxy.go
Labels: approved, lgtm, release-note, size/S

#226 Set appropriate sa name in openshift-cleanup Job
  cmd/openshift/kodata/tekton-config/99-clean-up/01-tekton-config-post-install-jobs.yaml
Labels: approved, lgtm, release-note, size/XS

#227 use internal imagestream - java, go
  cmd/openshift/kodata/tekton-addon/0.0.1/addons/02-clustertasks/s2i-go-pr/s2i-go-pr-task.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/addons/02-clustertasks/s2i-go-pr/s2i-go-pr-v0-19-0-task.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/addons/02-clustertasks/s2i-go/s2i-go-task.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/addons/02-clustertasks/s2i-go/s2i-go-v0-19-0-task.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/addons/02-clustertasks/s2i-java-11-pr/s2i-java-11-pr-task.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/addons/02-clustertasks/s2i-java-11-pr/s2i-java-11-pr-v0-19-0-task.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/addons/02-clustertasks/s2i-java-11/s2i-java-11-task.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/addons/02-clustertasks/s2i-java-11/s2i-java-11-v0-19-0-task.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/addons/02-clustertasks/s2i-java-8-pr/s2i-java-8-pr-task.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/addons/02-clustertasks/s2i-java-8-pr/s2i-java-8-pr-v0-19-0-task.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/addons/02-clustertasks/s2i-java-8/s2i-java-8-task.yaml
  cmd/openshift/kodata/tekton-addon/0.0.1/addons/02-clustertasks/s2i-java-8/s2i-java-8-v0-19-0-task.yaml
Labels: approved, lgtm, release-note, size/S

#228 Fix label not getting added on namespace
  pkg/reconciler/common/proxy.go
  pkg/reconciler/common/proxy_test.go
  pkg/reconciler/common/testdata/test-namespace-inject.yaml
Labels: approved, lgtm, release-note-none, size/M

#229 Add non-root SCC to pipelines controller
  cmd/openshift/kodata/tekton-pipeline/0.19.0/00_tektoncd-pipeline-v0.19.0.yaml
  cmd/openshift/kodata/tekton-pipeline/0.19.0/01-clusterrole.yaml
  cmd/openshift/kodata/tekton-pipeline/0.19.0/02-rolebinding.yaml
Labels: approved, lgtm, release-note, size/S

#231 Add Image Replacement mechanism for Cleanup Job
  config/openshift/operator.yaml
  pkg/reconciler/common/transformers.go
  pkg/reconciler/openshift/tektonconfig/extension/openshift_cleanup.go
Labels: approved, lgtm, release-note, size/M

#232 [OpenShift] Fix metrics display issue
  pkg/reconciler/common/transformers.go
  pkg/reconciler/openshift/tektonpipeline/extension.go
Labels: approved, lgtm, release-note, size/L

#235 Enable usage of tektoncd catalog tasks for s390x and ppc6le in Openshift operator
  pkg/reconciler/openshift/tektonaddon/tektonaddon.go
Labels: approved, lgtm, release-note, size/S
