Repository tektoncd/operator, pull requests merged in 2021-11, with the labels that each got.

#482 [OpenShift] Adds SCC predicate in TektonInstallerSet
  pkg/reconciler/kubernetes/tektoninstallerset/install.go
Labels: approved, lgtm, size/S, release-note

#483 [CherryPick] [OpenShift] Adds SCC predicate in TektonInstallerSet
  pkg/reconciler/kubernetes/tektoninstallerset/install.go
Labels: approved, lgtm, size/S, release-note

#484 [release-v0.50.x] [OpenShift] Remove openshift-client from update-task
  hack/openshift/update-tasks.sh
Labels: approved, size/XS, lgtm, release-note-none

#485 [OpenShift] Remove openshift-client from update-task
  hack/openshift/update-tasks.sh
Labels: approved, size/XS, lgtm, release-note-none

#489 [v0.51.x] Use ./hack/feth-releases.sh for the release task…
  tekton/task-fetch-components.yaml
Labels: kind/bug, release-note, size/L

#488 [v0.50.x] Use ./hack/feth-releases.sh for the release task…
  tekton/task-fetch-components.yaml
Labels: kind/bug, release-note, size/L

#492 Bump Triggers to v0.17.1 👼
  test/config.sh
Labels: kind/bug, approved, size/XS, lgtm, release-note

#493 Suffix _VERSION to "config" versions env vars.
  Makefile
  test/config.sh
  test/e2e-common.sh
Labels: approved, lgtm, size/S, release-note-none, kind/misc

#494 Move TekonDashboard.md to TektonDashboard.md
  docs/TektonDashboard.md
Labels: approved, size/XS, lgtm, release-note-none

#487 Use ./hack/feth-releases.sh for the release task…
  tekton/task-fetch-components.yaml
Labels: kind/bug, approved, lgtm, release-note, size/L

#490 releases: update release cheat-sheet
  tekton/release-cheat-sheet.md
Labels: approved, lgtm, size/M, release-note-none, kind/misc

#495 Updates Operator for Results v0.3.1
  Makefile
  docs/TektonResult.md
  pkg/reconciler/kubernetes/tektonresult/tektonresult.go
  test/config.sh
  test/e2e/kubernetes/tektonresultdeployment_test.go
Labels: approved, lgtm, size/S, release-note

#499 [Openshift] Remove openshit-client as we manage this task directly
  hack/openshift/update-tasks.sh
Labels: approved, size/XS, lgtm, release-note

#500 [OpenShift] add rights to delete securitycontextconstraints
  config/openshift/base/role.yaml
Labels: approved, size/XS, lgtm, release-note

#502 [OpenShift] add rights to delete securitycontextconstraints
  config/openshift/base/role.yaml
Labels: approved, size/XS, lgtm, release-note

#503 fix resources not getting deleted for unique ns cron
  pkg/reconciler/common/prune.go
  pkg/reconciler/common/prune_test.go
Labels: approved, lgtm, release-note, size/L

#504 [Cherry-pick]fix resources not getting deleted for unique ns cron
  pkg/reconciler/common/prune.go
  pkg/reconciler/common/prune_test.go
Labels: approved, lgtm, release-note, size/L

#505 Move update spec calls to the end of reconciler
  pkg/reconciler/kubernetes/tektonpipeline/tektonpipeline.go
  pkg/reconciler/kubernetes/tektontrigger/tektontrigger.go
  pkg/reconciler/openshift/tektonconfig/extension.go
  pkg/reconciler/openshift/tektonconfig/rbac.go
  pkg/reconciler/openshift/tektonpipeline/extension.go
  pkg/reconciler/openshift/tektontrigger/extension.go
  pkg/reconciler/shared/tektonconfig/tektonconfig.go
Labels: approved, lgtm, size/M, release-note

#506 [cherry-pick] Move update spec calls to the end of reconciler
  pkg/reconciler/kubernetes/tektonpipeline/tektonpipeline.go
  pkg/reconciler/kubernetes/tektontrigger/tektontrigger.go
  pkg/reconciler/openshift/tektonconfig/extension.go
  pkg/reconciler/openshift/tektonconfig/rbac.go
  pkg/reconciler/openshift/tektonpipeline/extension.go
  pkg/reconciler/openshift/tektontrigger/extension.go
  pkg/reconciler/shared/tektonconfig/tektonconfig.go
Labels: approved, lgtm, size/M, release-note

#501 Validates component CR name in webhook
  pkg/apis/operator/v1alpha1/const.go
  pkg/apis/operator/v1alpha1/tektonaddon_validation.go
  pkg/apis/operator/v1alpha1/tektonaddon_validation_test.go
  pkg/apis/operator/v1alpha1/tektonconfig_validation.go
  pkg/apis/operator/v1alpha1/tektonconfig_validation_test.go
  pkg/apis/operator/v1alpha1/tektondashboard_validation.go
  pkg/apis/operator/v1alpha1/tektondashboard_validation_test.go
  pkg/apis/operator/v1alpha1/tektonpipeline_validation.go
  pkg/apis/operator/v1alpha1/tektonpipeline_validation_test.go
  pkg/apis/operator/v1alpha1/tektontrigger_validation.go
  pkg/apis/operator/v1alpha1/tektontrigger_validation_test.go
  pkg/reconciler/common/common.go
  pkg/reconciler/kubernetes/tektonconfig/extension.go
  pkg/reconciler/kubernetes/tektonconfig/extension/dashboard.go
  pkg/reconciler/kubernetes/tektonconfig/extension/dashboard_test.go
  pkg/reconciler/kubernetes/tektonpipeline/tektonpipeline.go
  pkg/reconciler/kubernetes/tektonresult/tektonresult.go
  pkg/reconciler/kubernetes/tektontrigger/tektontrigger.go
  pkg/reconciler/openshift/tektonaddon/tektonaddon.go
  pkg/reconciler/openshift/tektonconfig/extension.go
  pkg/reconciler/openshift/tektonconfig/extension/addon.go
  pkg/reconciler/openshift/tektonconfig/extension/addon_test.go
  pkg/reconciler/shared/tektonconfig/controller.go
  pkg/reconciler/shared/tektonconfig/instance.go
  pkg/reconciler/shared/tektonconfig/pipeline/pipeline.go
  pkg/reconciler/shared/tektonconfig/pipeline/pipeline_test.go
  pkg/reconciler/shared/tektonconfig/tektonconfig.go
  pkg/reconciler/shared/tektonconfig/trigger/trigger.go
  pkg/reconciler/shared/tektonconfig/trigger/trigger_test.go
  test/e2e/common/tektonconfigdeployment_test.go
  test/resources/tektonconfigs.go
Labels: approved, lgtm, release-note, size/L

#507 Fix table in operatorhub/*/README.md
  operatorhub/kubernetes/README.md
  operatorhub/openshift/README.md
Labels: approved, lgtm, size/M, release-note-none

#510 fix pruning enabled by default
  pkg/reconciler/shared/tektonconfig/instance.go
Labels: approved, size/XS, lgtm, release-note

#511 fix pruning enabled by default
  pkg/reconciler/shared/tektonconfig/instance.go
Labels: approved, size/XS, lgtm, release-note

#514 [OpenShift] Fix forbidden error for community tasks
  pkg/reconciler/openshift/tektonaddon/tektonaddon.go
Labels: approved, lgtm, size/S, release-note

#515 [OpenShift] Fix forbidden error for community tasks
  pkg/reconciler/openshift/tektonaddon/tektonaddon.go
Labels: approved, lgtm, size/S, release-note

#523 remove taskrun from default prune resource
  pkg/reconciler/shared/tektonconfig/instance.go
Labels: approved, size/XS, lgtm, release-note

#522 [Cherry-Pick] Fix usage of dynamic names in webhook configurations
  pkg/webhook/webhook.go
Labels: approved, lgtm, size/M, release-note

#521 Fix usage of dynamic names in webhook configurations
  pkg/webhook/webhook.go
Labels: approved, lgtm, size/M, release-note

#524 [cherry-pick] remove taskrun from default prune resource
  pkg/reconciler/shared/tektonconfig/instance.go
Labels: approved, size/XS, lgtm, release-note

#508 Add doc on Tektoncd Operator Release Versioning
  docs/README.md
  docs/release/README.md
Labels: approved, lgtm, size/M, release-note

#525 Cleanup: admissionReviewVersions v1beta1 was depreacated k8s v1.16
  cmd/kubernetes/webhook/kodata/validating-defaulting-webhook/500-webhooks.yaml
Labels: approved, size/XS, lgtm, release-note, kind/cleanup

#529 Skips adding owner reference in Webhook configuration
  pkg/reconciler/kubernetes/tektoninstallerset/transformer.go
Labels: approved, size/XS, lgtm, release-note

#532 Update release docs
  tekton/release-cheat-sheet.md
Labels: approved, lgtm, release-note, size/L

#519 Adds e2e tests for Operator features
  pkg/reconciler/kubernetes/tektonpipeline/tektonpipeline.go
  pkg/reconciler/kubernetes/tektontrigger/tektontrigger.go
  test/e2e-common.sh
  test/e2e-tests.sh
  test/e2e/common/tektonconfigdeployment_test.go
  test/resources/tektonconfigs.go
Labels: approved, lgtm, release-note, size/L

#535 [OpenShift] Add argocd-task-sync-and-wait task to community task
  pkg/reconciler/openshift/tektonaddon/tektonaddon.go
Labels: approved, size/XS, lgtm, release-note
