Repository tektoncd/operator, pull requests merged in 2021-07, with the labels that each got.

#342 Update git-clone 0.4 task for 1.5.0
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/02-clustertasks/git-clone/git-clone-1-5-0-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/02-clustertasks/git-clone/git-clone-task.yaml
  hack/openshift/update-tasks.sh
Labels: approved, lgtm, release-note-none, size/XS

#347 Update publish-image task
  tekton/bases/build-publish-images-manifests.yaml
Labels: approved, lgtm, release-note, size/XS

#345 Add proxy-webhook to the list of built images
  tekton/overlays/nightly-releases/operator-nightly-release-pipeline.yaml
Labels: approved, lgtm, release-note, size/XS

#348 Add sm43 as a reviewer
  OWNERS
Labels: approved, lgtm, release-note, size/XS

#349 Add namespace transformer for ClusterInterceptor
  pkg/reconciler/common/testdata/test-replace-namespace-in-cluster-interceptor.yaml
  pkg/reconciler/common/transformers.go
  pkg/reconciler/common/transformers_test.go
Labels: approved, lgtm, release-note-none, size/M

#341 Update Docs
  docs/TekonDashboard.md
  docs/TektonAddon.md
  docs/TektonConfig.md
  docs/TektonPipeline.md
  docs/TektonResult.md
  docs/TektonTrigger.md
Labels: approved, lgtm, release-note, size/L

#351 [Openshift] fixes addon sample pipelines
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/optional/samples/pipelinesamples/docker_build_deploy.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/optional/samples/pipelinesamples/s2i_build_deploy.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/optional/samples/pipelinesamples/simple_pipeline.yaml
Labels: approved, lgtm, release-note, size/M

#363 [OpenShift] fixes adding label in namespace in rbac creation
  pkg/reconciler/openshift/tektonconfig/rbac.go
Labels: approved, lgtm, release-note, size/XS

#359 fix pipelinetemplate not working
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/02-clustertasks/openshift-client/openshift-client-1-5-0-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/addons/02-clustertasks/openshift-client/openshift-client-task.yaml
  hack/openshift/update-tasks.sh
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/pipelinetemplates.go
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/buildah-deployment.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/buildah.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-dotnet-deployment.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-dotnet.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-go-deployment.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-go.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-java-deployment.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-java.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-nodejs-deployment.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-nodejs.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-perl-deployment.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-perl.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-php-deployment.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-php.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-python-deployment.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-python.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-ruby-deployment.golden
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/testdata/s2i-ruby.golden
Labels: approved, lgtm, release-note, size/M

#366 [OpenShift] Add a version label on namespace
  pkg/reconciler/openshift/tektonconfig/rbac.go
Labels: approved, lgtm, release-note, size/S

#364 fix autoprune not exectuing for second resource #38
  pkg/reconciler/common/prune.go
Labels: approved, lgtm, release-note, size/S

#367 Skip Tekton Result tests for Z and Power platforms
  test/e2e/kubernetes/tektonresultdeployment_test.go
Labels: approved, lgtm, release-note-none, size/XS

#338 Configure node selection for components using CR spec
  pkg/apis/operator/v1alpha1/tektonconfig_types.go
  pkg/apis/operator/v1alpha1/tektondashboard_types.go
  pkg/apis/operator/v1alpha1/tektonpipeline_types.go
  pkg/apis/operator/v1alpha1/tektontrigger_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/common/testdata/test-add-configurations.yaml
  pkg/reconciler/common/transformers.go
  pkg/reconciler/common/transformers_test.go
  pkg/reconciler/kubernetes/tektonconfig/extension/dashboard.go
  pkg/reconciler/kubernetes/tektonconfig/pipeline/pipeline.go
  pkg/reconciler/kubernetes/tektonconfig/trigger/trigger.go
  pkg/reconciler/kubernetes/tektondashboard/tektondashboard.go
  pkg/reconciler/kubernetes/tektonpipeline/tektonpipeline.go
  pkg/reconciler/kubernetes/tektontrigger/tektontrigger.go
  pkg/reconciler/openshift/tektonconfig/extension/addon.go
Labels: approved, lgtm, release-note, size/L

#356 [OpenShift] Update pipeline default in CR instead of transformers
  pkg/reconciler/openshift/tektonconfig/extension.go
  pkg/reconciler/openshift/tektonpipeline/extension.go
Labels: approved, lgtm, release-note, size/L
