Repository tektoncd/operator, pull requests merged in 2021-09, with the labels that each got.

#395 Updates development docs to correct the profiles and their respective Tekton Components
  DEVELOPMENT.md
Labels: approved, size/XS, lgtm, release-note

#397 Fix trigger installation issue
  config/base/role.yaml
  config/openshift/role.yaml
Labels: approved, size/XS, lgtm, release-note

#398 [OpenShift] Disable quay image replacement
  pkg/reconciler/openshift/common/testdata/test-prefix-images-expected.yaml
  pkg/reconciler/openshift/common/testdata/test-prefix-images-interceptor-expected.yaml
  pkg/reconciler/openshift/common/testdata/test-prefix-images-triggers-expected.yaml
  pkg/reconciler/openshift/common/transformer.go
  pkg/reconciler/openshift/common/transformer_test.go
  pkg/reconciler/openshift/tektonpipeline/extension.go
  pkg/reconciler/openshift/tektontrigger/extension.go
Labels: approved, lgtm, release-note, size/L

#387 [OpenShift] Read version to add in rbac resources from env
  config/base/operator.yaml
  pkg/reconciler/openshift/tektonconfig/extension.go
  pkg/reconciler/openshift/tektonconfig/rbac.go
Labels: approved, lgtm, size/S, release-note

#394 Removes the resources based on the profile set
  pkg/reconciler/kubernetes/tektonconfig/extension.go
  pkg/reconciler/kubernetes/tektonconfig/tektonconfig.go
  pkg/reconciler/openshift/tektonconfig/extension.go
Labels: approved, lgtm, size/M, release-note

#406 Update kustomization files to fix operator nightly issue
  config/kubernetes/300-operator_v1alpha1_dashboard_crd.yaml
  config/kubernetes/300-operator_v1alpha1_result_crd.yaml
  config/kubernetes/kustomization.yaml
  config/openshift/300-operator_v1alpha1_addon_crd.yaml
  config/openshift/kustomization.yaml
Labels: approved, lgtm, size/S, release-note

#402 Add readonly property to Tekton Dashboard component
  docs/TekonDashboard.md
  docs/TektonConfig.md
  hack/fetch-releases.sh
  pkg/apis/operator/v1alpha1/tektonconfig_types.go
  pkg/apis/operator/v1alpha1/tektondashboard_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/common/releases.go
  pkg/reconciler/kubernetes/tektonconfig/extension/dashboard.go
  tekton/task-fetch-components.yaml
  third_party/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
Labels: approved, lgtm, release-note, ok-to-test, size/L

#405 correct typo in code comments
  pkg/apis/operator/v1alpha1/register.go
  pkg/reconciler/kubernetes/tektonpipeline/tektonpipeline.go
Labels: approved, size/XS, lgtm, release-note, ok-to-test

#414 Fix move enable-api-fields to feature-flags CM
  pkg/apis/operator/v1alpha1/tektontrigger_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/kubernetes/tektontrigger/tektontrigger.go
Labels: approved, lgtm, size/M, release-note-none

#415 Set default value to TektonConfig object
  pkg/reconciler/shared/tektonconfig/instance.go
  pkg/reconciler/shared/tektonconfig/tektonconfig.go
Labels: approved, size/XS, lgtm

#416 Fixes hash annotation key while updating TektonInstallerSet
  pkg/reconciler/kubernetes/tektonpipeline/tektonpipeline.go
  pkg/reconciler/kubernetes/tektontrigger/tektontrigger.go
Labels: approved, size/XS, lgtm, release-note

#418 Configure Bundle Generation for Openshift
  config/crs/kubernetes/installerset/operator_v1alpha1_installerset_cr.yaml
  config/crs/kubernetes/kustomization.yaml
  config/crs/openshift/installerset/operator_v1alpha1_installerset_cr.yaml
  config/crs/openshift/kustomization.yaml
  operatorhub/kubernetes/README.md
  operatorhub/openshift/README.md
  operatorhub/openshift/config.yaml
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
  operatorhub/openshift/release-artifacts/bundle.Dockerfile
  operatorhub/openshift/release-artifacts/bundle/manifests/config-logging_v1_configmap.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator_v1_serviceaccount.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/operator.tekton.dev_tektonaddons.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/operator.tekton.dev_tektonconfigs.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/operator.tekton.dev_tektoninstallersets.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/operator.tekton.dev_tektonpipelines.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/operator.tekton.dev_tektontriggers.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/tekton-config-defaults_v1_configmap.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/tekton-operator-webhook-certs_v1_secret.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/tekton-operator-webhook_v1_service.yaml
  operatorhub/openshift/release-artifacts/bundle/metadata/annotations.yaml
  operatorhub/openshift/release-artifacts/bundle/tests/scorecard/config.yaml
Labels: approved, lgtm, release-note, size/XXL

#417 Updates Addon reconciler to use TektonInstallerSet
  go.mod
  pkg/apis/operator/v1alpha1/tektonaddon_lifecycle.go
  pkg/apis/operator/v1alpha1/tektonaddon_lifecycle_test.go
  pkg/apis/operator/v1alpha1/tektonaddon_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/kubernetes/tektoninstallerset/install.go
  pkg/reconciler/kubernetes/tektontrigger/tektontrigger.go
  pkg/reconciler/openshift/tektonaddon/controller.go
  pkg/reconciler/openshift/tektonaddon/extension.go
  pkg/reconciler/openshift/tektonaddon/tektonaddon.go
  pkg/reconciler/openshift/tektonaddon/transformer.go
  third_party/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/LICENSE
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/.import-restrictions
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.pb.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.proto
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/marshal.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/clientset.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/generated_expansion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/generated_expansion.go
  vendor/modules.txt
Labels: approved, lgtm, release-note, size/XXL

#422 Fix adding default namespace as subjects to openshift-pipelines-clusterinterceptors clusterrolebinding
  pkg/reconciler/openshift/tektonconfig/rbac.go
Labels: approved, size/XS, lgtm, release-note

#423 [OpenShift] Updates pipelines extension to use InstallerSet
  pkg/apis/operator/v1alpha1/tektonpipeline_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/kubernetes/tektoninstallerset/install.go
  pkg/reconciler/openshift/tektonpipeline/extension.go
  pkg/reconciler/openshift/tektonpipeline/installerset.go
Labels: approved, lgtm, release-note, size/L

#419 Add properties to configure Pipelines Metrics
  docs/TektonConfig.md
  docs/TektonPipeline.md
  pkg/apis/operator/v1alpha1/tektonpipeline_defaults.go
  pkg/apis/operator/v1alpha1/tektonpipeline_defaults_test.go
  pkg/apis/operator/v1alpha1/tektonpipeline_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/kubernetes/tektonpipeline/tektonpipeline.go
Labels: approved, lgtm, release-note, size/L

#428 Fixes AppendManifest used to read files from kodata
  pkg/reconciler/common/releases.go
  pkg/reconciler/common/releases_test.go
  pkg/reconciler/common/testdata/kodata/tekton-addon/0.0.2/01-clustertriggerbindings/bitbucket.yaml
  pkg/reconciler/common/testdata/kodata/tekton-addon/bitbucket-1.yaml
Labels: approved, lgtm, size/M, release-note

#430 Handles deletion of CRDs before deleting installer set
  pkg/reconciler/kubernetes/tektonpipeline/tektonpipeline.go
  pkg/reconciler/kubernetes/tektontrigger/tektontrigger.go
Labels: approved, lgtm, size/S, release-note
