Repository tektoncd/operator, pull requests merged in 2022-01, with the labels that each got.

#571 Add digest for static images
  operatorhub/openshift/config.yaml
Labels: approved, lgtm, size/S, release-note-none

#572 Remove gotest.tools v2 🦂
  go.mod
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/pipelinetemplates_test.go
  third_party/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
  vendor/gotest.tools/LICENSE
  vendor/gotest.tools/assert/assert.go
  vendor/gotest.tools/assert/cmp/compare.go
  vendor/gotest.tools/assert/cmp/result.go
  vendor/gotest.tools/assert/result.go
  vendor/gotest.tools/golden/golden.go
  vendor/gotest.tools/internal/difflib/LICENSE
  vendor/gotest.tools/internal/difflib/difflib.go
  vendor/gotest.tools/internal/format/diff.go
  vendor/gotest.tools/internal/format/format.go
  vendor/gotest.tools/internal/source/defers.go
  vendor/gotest.tools/internal/source/source.go
  vendor/gotest.tools/v3/golden/golden.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL, release-note-none

#570 Adds missing annotation `lastAppliedHashKey` in TektonInstaller Set for Tekton Dashboard
  pkg/reconciler/kubernetes/tektondashboard/tektondashboard.go
Labels: approved, lgtm, size/S, release-note

#563 Adds config map for operator version
  cmd/kubernetes/operator/kodata/info/operator-config.yaml
  cmd/openshift/operator/kodata/info/operator-config.yaml
  pkg/reconciler/kubernetes/tektonpipeline/controller.go
  pkg/reconciler/kubernetes/tektonpipeline/tektonpipeline.go
  pkg/reconciler/shared/tektonconfig/controller.go
  pkg/reconciler/shared/tektonconfig/tektonconfig.go
  tekton/build-publish-images-manifests.yaml
Labels: approved, lgtm, release-note, size/L

#579 Add v0.54.0 Docs
  Makefile
  README.md
  tekton/release-cheat-sheet.md
  test/config.sh
Labels: approved, lgtm, release-note, size/L

#594 Fixes make apply error due to variable changes
  Makefile
Labels: approved, size/XS, lgtm, release-note

#595 Removes obsolete installersets created during upgrades
  pkg/reconciler/kubernetes/tektoninstallerset/query.go
  pkg/reconciler/kubernetes/tektoninstallerset/query_test.go
  pkg/reconciler/kubernetes/tektonpipeline/tektonpipeline.go
  pkg/reconciler/kubernetes/tektontrigger/tektontrigger.go
Labels: approved, lgtm, size/M, release-note

#596 [OpenShift] fixes post pipelines installerSet creation
  pkg/reconciler/openshift/tektonpipeline/extension.go
Labels: approved, size/XS, lgtm, release-note

#597 [OpenShift] removes obsolete installerSets created for Addon during Upgrade
  pkg/reconciler/openshift/tektonaddon/tektonaddon.go
Labels: approved, size/XS, lgtm, release-note

#598 Fix build failure for addon e2e test
  test/e2e/openshift/tektonaddondeployment_test.go
Labels: approved, size/XS, lgtm, release-note

#592 Fix upgrade deadlock in Pipeline and Triggers
  pkg/reconciler/common/deadlockbreaker.go
  pkg/reconciler/kubernetes/tektonpipeline/tektonpipeline.go
  pkg/reconciler/kubernetes/tektontrigger/controller.go
  pkg/reconciler/kubernetes/tektontrigger/tektontrigger.go
Labels: approved, lgtm, release-note, size/L

#599 Fix versioned clustertask getting deleted during upgrade
  pkg/reconciler/kubernetes/tektoninstallerset/const.go
  pkg/reconciler/openshift/tektonaddon/const.go
  pkg/reconciler/openshift/tektonaddon/tektonaddon.go
Labels: approved, lgtm, release-note, size/L

#602 [cherry-pick] Fix versioned clustertask getting deleted during upgrade
  pkg/reconciler/kubernetes/tektoninstallerset/const.go
  pkg/reconciler/openshift/tektonaddon/const.go
  pkg/reconciler/openshift/tektonaddon/tektonaddon.go
Labels: approved, lgtm, release-note, size/L
