Repository tektoncd/operator, pull requests merged in 2022-12, with the labels that each got.

#1196 Updates helm charts for config resources changes
  chart/templates/kubernetes-crds.yaml
  chart/templates/openshift-crds.yaml
  chart/templates/rbac.yaml
Labels: approved, lgtm, size/M, release-note

#1167 Bump operator version
  chart/Chart.yaml
  chart/templates/kubernetes-crds.yaml
  chart/templates/openshift-crds.yaml
Labels: approved, lgtm, size/M, release-note, ok-to-test

#1200 Update the bump-payload-on-releases.yaml…
  .github/workflows/bump-payload-on-releases.yaml
Labels: approved, size/XS, lgtm, release-note-none

#1201 .github/workflows: trying to re-enable dynamic workflow
  .github/workflows/bump-payload-on-releases.yaml
Labels: approved, lgtm, size/S, release-note-none

#1211 .github/workflows: fix bump-payload-on-releases
  .github/workflows/bump-payload-on-releases.yaml
Labels: approved, size/XS, lgtm, release-note-none

#1216 .github/workflows: another fix on bump payload releases
  .github/workflows/bump-payload-on-releases.yaml
Labels: approved, size/XS, lgtm, release-note-none

#1210 e2e: disable communityclustertasks when clustertasks are disabled
  test/e2e/common/00_tektonconfigdeployment_test.go
Labels: approved, size/XS, lgtm, release-note, ok-to-test

#1218 Update Hub Docs based on new changes of Hub v1.11.1
  docs/TektonHub.md
Labels: approved, lgtm, size/M, release-note

#1220 Installerset client: fixes custom set update case
  pkg/reconciler/kubernetes/tektoninstallerset/client/update.go
  pkg/reconciler/kubernetes/tektoninstallerset/client/update_test.go
Labels: approved, lgtm, size/M, release-note

#1219 test: use `T.Setenv` to set env vars in tests
  pkg/apis/operator/v1alpha1/tektonconfig_default_test.go
  pkg/apis/operator/v1alpha1/tektonhub_default_test.go
  pkg/reconciler/common/prune_test.go
  pkg/reconciler/common/releases_test.go
  pkg/reconciler/common/stages_test.go
  pkg/reconciler/common/transformers_test.go
  pkg/reconciler/kubernetes/tektonconfig/extension/dashboard_test.go
  pkg/reconciler/openshift/tektonconfig/extension/addon_test.go
  pkg/reconciler/openshift/tektonconfig/extension/pipelinesascode_test.go
  pkg/reconciler/shared/tektonconfig/pipeline/pipeline_test.go
  pkg/reconciler/shared/tektonconfig/trigger/trigger_test.go
  pkg/webhook/webhook_init_test.go
Labels: approved, lgtm, size/M, release-note-none, ok-to-test, kind/cleanup

#1207 fix: setup pruner job with proper SecurityContext
  pkg/reconciler/common/prune.go
Labels: approved, size/XS, lgtm, release-note, ok-to-test

#1224 Fix imagereplacement transformer missing
  config/openshift/base/operator.yaml
  operatorhub/openshift/config.yaml
  pkg/reconciler/openshift/tektonaddon/clustertTask.go
  pkg/reconciler/openshift/tektonaddon/clustertTaskVersioned.go
Labels: approved, lgtm, size/S, release-note

#1195 Update ClusterInterceptor ClusterRoleBinding after the namespace removal
  config/openshift/base/role.yaml
  pkg/reconciler/openshift/tektonconfig/extension.go
  pkg/reconciler/openshift/tektonconfig/rbac.go
  vendor/knative.dev/pkg/client/injection/kube/informers/rbac/v1/clusterrolebinding/clusterrolebinding.go
  vendor/modules.txt
Labels: approved, lgtm, release-note, size/L

#1227 Freezing Component versions and updating version labels
  cmd/kubernetes/operator/kodata/webhook/webhook.yaml
  cmd/openshift/operator/kodata/webhook/webhook.yaml
  config/base/300-operator_v1alpha1_chain_crd.yaml
  config/base/300-operator_v1alpha1_config_crd.yaml
  config/base/300-operator_v1alpha1_hub_crd.yaml
  config/base/300-operator_v1alpha1_installer_set_crd.yaml
  config/base/300-operator_v1alpha1_pipeline_crd.yaml
  config/base/300-operator_v1alpha1_trigger_crd.yaml
  config/base/config-info.yaml
  config/base/operator.yaml
  config/kubernetes/base/300-operator_v1alpha1_dashboard_crd.yaml
  config/kubernetes/base/300-operator_v1alpha1_result_crd.yaml
  config/kubernetes/base/operator.yaml
  config/kubernetes/base/operator_service.yaml
  config/kubernetes/base/webhook.yaml
  config/openshift/base/300-operator_v1alpha1_addon_crd.yaml
  config/openshift/base/300-operator_v1alpha1_openshiftpipelinesascode_crd.yaml
  config/openshift/base/operator.yaml
  config/openshift/base/operator_service.yaml
  config/openshift/base/webhook.yaml
  config/webhooks/webhook-service.yaml
  config/webhooks/webhook.yaml
Labels: approved, lgtm, size/M, release-note

#1228 Bump pipelines-as-code version to 0.15.0
  components.yaml
Labels: approved, size/XS, lgtm, release-note

#1231 Fix tranformers are getting applied on reconciler resources
  pkg/reconciler/openshift/tektonaddon/clustertTask.go
  pkg/reconciler/openshift/tektonaddon/clustertTaskVersioned.go
  pkg/reconciler/openshift/tektonaddon/communityClusterTasks.go
  pkg/reconciler/openshift/tektonaddon/consolecli.go
  pkg/reconciler/openshift/tektonaddon/pipelinetemplate.go
  pkg/reconciler/openshift/tektonaddon/triggers.go
Labels: approved, lgtm, size/S, release-note

#1235 Bump pac to v0.15.0
  components.yaml
  go.mod
  go.sum
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
  third_party/github.com/fsnotify/fsnotify/LICENSE
  vendor/github.com/openshift-pipelines/pipelines-as-code/pkg/params/settings/config.go
  vendor/github.com/openshift-pipelines/pipelines-as-code/pkg/params/settings/default.go
  vendor/modules.txt
Labels: approved, lgtm, release-note, size/L

#1025 Define keep and keep-since simultaneously
  docs/TektonConfig.md
  pkg/apis/operator/v1alpha1/tektonconfig_validation.go
  pkg/reconciler/common/prune.go
  pkg/reconciler/common/prune_test.go
Labels: approved, lgtm, size/M, release-note, ok-to-test
