Repository tektoncd/operator, pull requests merged in 2022-06, with the labels that each got.

#818 Fix a buggy package reference
  test/resources/common.go
  test/resources/rbac.go
  test/resources/tektonaddons.go
  test/resources/tektonchains.go
  test/resources/tektonconfigs.go
  test/resources/tektondashboards.go
  test/resources/tektonpipelines.go
  test/resources/tektonresources.go
  test/resources/tektonresults.go
  test/resources/tektontriggers.go
  test/resources/verify.go
Labels: approved, lgtm, size/M, release-note

#821 Increase e2e poll timeout to 10min
  test/utils/config.go
Labels: approved, size/XS, lgtm, release-note

#822 Add a projects workflow 🧑‍⚕️
  .github/workflows/projects.yaml
Labels: size/S, release-note-none

#708 This will fix scheduling the cron jobs pod on infra node if configured
  pkg/reconciler/common/prune.go
  pkg/reconciler/common/prune_test.go
Labels: approved, lgtm, release-note, size/L

#828 [Cherry-pick] Checks and updates ownerRef of Hub-db pvc if Hub instance is already created
  pkg/reconciler/kubernetes/tektonhub/tektonhub.go
  pkg/reconciler/kubernetes/tektoninstallerset/tektoninstallerset.go
Labels: approved, lgtm, size/M, release-note

#827 Checks and updates ownerRef of Hub-db pvc if Hub instance is already created
  pkg/reconciler/kubernetes/tektonhub/tektonhub.go
  pkg/reconciler/kubernetes/tektoninstallerset/tektoninstallerset.go
Labels: approved, lgtm, size/M, release-note

#829 Find and replace of Hub version
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
  tekton/operator-release-pipeline.yaml
  tekton/task-fetch-components.yaml
Labels: approved, size/XS, lgtm, release-note-none

#830 Set version in TektonConfig status in main reconciler
  pkg/apis/operator/v1alpha1/const.go
  pkg/reconciler/common/transformer_injectlabel_test.go
  pkg/reconciler/kubernetes/tektonchain/tektonchain.go
  pkg/reconciler/openshift/tektonaddon/clustertTask.go
  pkg/reconciler/openshift/tektonaddon/pipelinesascode.go
  pkg/reconciler/openshift/tektonaddon/tektonaddon.go
  pkg/reconciler/openshift/tektonconfig/common.go
  pkg/reconciler/shared/tektonconfig/tektonconfig.go
  test/resources/cosign.go
Labels: approved, lgtm, size/S, release-note

#832 [Cherry-pick] Set version in TektonConfig status in main reconciler
  pkg/apis/operator/v1alpha1/const.go
  pkg/reconciler/common/certificates.go
  pkg/reconciler/common/certificates_test.go
  pkg/reconciler/kubernetes/tektonchain/tektonchain.go
  pkg/reconciler/kubernetes/tektondashboard/tektondashboard.go
  pkg/reconciler/kubernetes/tektoninstallerset/tektoninstallerset.go
  pkg/reconciler/kubernetes/tektonpipeline/tektonpipeline.go
  pkg/reconciler/kubernetes/tektontrigger/tektontrigger.go
  pkg/reconciler/openshift/common/cabundle_test.go
  pkg/reconciler/openshift/tektonaddon/clustertTask.go
  pkg/reconciler/openshift/tektonaddon/tektonaddon.go
  pkg/reconciler/openshift/tektonconfig/common.go
  pkg/reconciler/proxy/proxy.go
  pkg/reconciler/shared/tektonconfig/tektonconfig.go
  pkg/webhook/webhook_init_test.go
Labels: approved, lgtm, size/M, release-note

#825 Update the PipelinesAsCode reconciler to support latest version
  operatorhub/openshift/config.yaml
  pkg/reconciler/openshift/tektonaddon/pipelinesascode.go
  pkg/reconciler/openshift/tektonaddon/transformer.go
  pkg/reconciler/openshift/tektonaddon/transformer_test.go
Labels: kind/feature, approved, lgtm, release-note, size/L

#836 Fix buid-test errors
  hack/tools.go
  tools.go
Labels: approved, size/XS, lgtm, release-note

#834 Fixes the duplication of Hub installerset when there is an operator upgrade
  pkg/reconciler/kubernetes/tektonhub/controller.go
  pkg/reconciler/kubernetes/tektonhub/installerset.go
  pkg/reconciler/kubernetes/tektonhub/tektonhub.go
Labels: approved, lgtm, size/L

#838 [Cherry-pick] Refactors the check for Hub pvc and fixes the duplication of Hub installerset when there is an operator upgrade
  pkg/reconciler/kubernetes/tektonhub/controller.go
  pkg/reconciler/kubernetes/tektonhub/installerset.go
  pkg/reconciler/kubernetes/tektonhub/tektonhub.go
Labels: approved, lgtm, size/L

#843 Run pac deployments on infra node
  pkg/reconciler/openshift/tektonaddon/pipelinesascode.go
Labels: approved, size/XS, lgtm, release-note

#788 Fixes Hub version to `latest` in Makefile
  Makefile
  hack/fetch-releases.sh
Labels: approved, lgtm, size/S, release-note

#842 Add script for upgrade tests
  test/e2e-common.sh
  test/e2e-tests.sh
  test/upgrade-tests.sh
Labels: approved, lgtm, size/L

#841 Refactors update logic for TektonPipeline reconciler
  pkg/reconciler/kubernetes/tektonpipeline/tektonpipeline.go
  pkg/reconciler/shared/tektoninstallerset/install.go
  pkg/reconciler/shared/tektoninstallerset/install_test.go
Labels: approved, lgtm, size/L

#847 .github/workflows: remove pull_request from it
  .github/workflows/projects.yaml
Labels: approved, lgtm, size/S, release-note-none

#848 hack: setup a temporary gopath for codegen
  hack/setup-temporary-gopath.sh
  hack/update-codegen.sh
Labels: approved, lgtm, size/M, release-note-none, kind/misc

#840 Skip Tekton Chain tests for Z and Power platforms
  test/e2e/common/03_tektonchaindeployment_test.go
  test/e2e/common/04_tektonchainsgettingstartedtutorial_test.go
Labels: approved, size/XS, lgtm, release-note-none, ok-to-test

#826 Add dependabot to the repository
  .github/dependabot.yml
Labels: approved, lgtm, size/S, release-note-none, kind/misc

#850 Add graceful termination to webhook pods
  cmd/kubernetes/webhook/main.go
  cmd/openshift/webhook/main.go
  pkg/webhook/webhook_init.go
Labels: approved, lgtm, size/M, release-note

#858 [OpenShit] Skip RBAC setup in namespaces which are being deleted
  pkg/reconciler/openshift/tektonconfig/rbac.go
Labels: approved, size/XS, lgtm, release-note

#860 Update git-clone version to 0.6
  hack/openshift/fetch-tektoncd-catalog-tasks.sh
Labels: approved, size/XS, lgtm, release-note

#862 Update Red Hat images (s2i, ubi, buildah..)
  config/openshift/base/operator.yaml
  operatorhub/openshift/config.yaml
Labels: approved, lgtm, size/S, release-note

#797 [TektonConfig] Allows user to set priorityClassName parameter
  docs/TektonConfig.md
  pkg/apis/operator/v1alpha1/tektonconfig_types.go
  pkg/reconciler/common/transformers.go
  pkg/reconciler/common/transformers_test.go
Labels: approved, lgtm, size/S, release-note, ok-to-test

#864 Mutate all containers in openshift-pipelines-operators
  operatorhub/openshift/config.yaml
Labels: approved, size/XS, lgtm, release-note-none, priority/critical-urgent, kind/misc

#863 Fix chains secret getting overwritten on upgrade
  pkg/reconciler/kubernetes/tektonchain/tektonchain.go
Labels: approved, lgtm, release-note, size/L

#846 Adds Tekton Hub ownerRef for Hub components
  pkg/reconciler/kubernetes/tektonhub/tektonhub.go
Labels: approved, lgtm, size/S, release-note

#865 Update git-clone task version to 0.7
  hack/openshift/fetch-tektoncd-catalog-tasks.sh
Labels: approved, size/XS, lgtm, release-note

#866 [Openshift] Updates Hub pre-reconciler to manage Auth Url
  pkg/reconciler/openshift/tektonhub/extension.go
Labels: approved, lgtm, size/M, release-note

#874 Fix component versions in OperatorHub description
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
Labels: approved, lgtm, size/S, release-note-none
