Repository tektoncd/operator, pull requests merged in 2022-05, with the labels that each got.

#766 fixes fetch release script for pac
  hack/fetch-releases.sh
Labels: approved, size/XS, lgtm, release-note

#755 Add script for release branch creation
  hack/openshift/fetch-tektoncd-catalog-tasks.sh
  hack/release-commands.sh
  hack/release-common.sh
  hack/release-const.sh
  hack/release-freeze-component-versions.sh
  hack/release-setup-branch.sh
Labels: approved, lgtm, release-note, size/L

#761 addons/clustertasks: update images to latest...
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/buildah/buildah-task.yaml
  config/openshift/base/operator.yaml
  operatorhub/openshift/config.yaml
Labels: approved, lgtm, size/S, release-note

#777 Updates Hub version to 1.7.3
  Makefile
  test/config.sh
Labels: approved, size/XS, lgtm, release-note

#776 Improve e2e test tear down mechanism
  test/e2e/common/04_tektonchainsgettingstartedtutorial_test.go
  test/e2e/kubernetes/tektonresultdeployment_test.go
  test/utils/cleanup.go
  test/utils/e2e_flags.go
Labels: approved, lgtm, release-note, size/L

#780 Improve Deployment creation in InstallerSet reconciler
  pkg/reconciler/kubernetes/tektoninstallerset/install.go
Labels: approved, lgtm, size/S, release-note

#781 Filter out PodSecurityPolicy from manifests ✂️
  pkg/reconciler/kubernetes/tektoninstallerset/install.go
  pkg/reconciler/kubernetes/tektoninstallerset/install_test.go
Labels: approved, size/XS, lgtm, release-note

#627 Add Helm chart for installing Tekton Operator
  .yamllint
  chart/.helmignore
  chart/Chart.yaml
  chart/README.md
  chart/templates/NOTES.txt
  chart/templates/_helpers.tpl
  chart/templates/config.yaml
  chart/templates/deployment.yaml
  chart/templates/kubernetes-crds.yaml
  chart/templates/openshift-crds.yaml
  chart/templates/rbac.yaml
  chart/templates/secret.yaml
  chart/templates/service.yaml
  chart/values.yaml
Labels: approved, lgtm, release-note, size/XXL, ok-to-test

#789 Make sure we push to the right branch
  hack/release-common.sh
Labels: approved, size/XS, lgtm, release-note-none

#790 Add a mechanism to ensure targetNamespace is deleted up in e2e tests
  test/e2e-tests.sh
  test/e2e/common/00_tektonconfigdeployment_test.go
  test/e2e/common/01_tektonpipelinedeployment_test.go
  test/e2e/common/02_tektontriggerdeployment_test.go
  test/e2e/common/03_tektonchaindeployment_test.go
  test/e2e/common/04_tektonchainsgettingstartedtutorial_test.go
  test/e2e/kubernetes/tektondashboarddeployment_test.go
  test/e2e/kubernetes/tektonresultdeployment_test.go
  test/utils/cleanup.go
Labels: approved, lgtm, size/M, release-note

#799 Add honorLabels to the pipelines ServiceMonitor
  cmd/openshift/operator/kodata/openshift-monitoring/00-monitoring.yaml
Labels: approved, size/XS, lgtm, release-note-none

#798 Add honorLabels to the pipelines ServiceMonitor
  cmd/openshift/operator/kodata/openshift-monitoring/00-monitoring.yaml
Labels: approved, size/XS, lgtm, release-note

#796 Add honorLabels to the pipelines ServiceMonitor
  cmd/openshift/operator/kodata/openshift-monitoring/00-monitoring.yaml
Labels: approved, size/XS, lgtm, release-note-none

#804 [release-v0.55.x] Add quickstart for configuring pipeline metrics levels
  cmd/openshift/operator/kodata/tekton-addon/optional/quickstarts/configure-pipeline-metrics-quickstart.yaml
Labels: approved, lgtm, size/M, release-note, ok-to-test

#803 [release-0.50.x] - Add quickstart for configuring pipeline metrics levels
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/optional/quickstarts/configure-pipeline-metrics-quickstart.yaml
Labels: approved, lgtm, size/M, release-note, ok-to-test

#808 [release-0.50.x] Add a warning message for changing metrics level configuration
  cmd/openshift/operator/kodata/tekton-addon/1.5.0/optional/quickstarts/configure-pipeline-metrics-quickstart.yaml
Labels: approved, size/XS, lgtm, release-note, ok-to-test

#801 Add quickstart for configuring pipeline metrics levels
  cmd/openshift/operator/kodata/tekton-addon/optional/quickstarts/configure-pipeline-metrics-quickstart-yaml
Labels: approved, lgtm, size/M, release-note, ok-to-test

#807 [release-0.55] Add a warning message for changing metrics level configuration
  cmd/openshift/operator/kodata/tekton-addon/optional/quickstarts/configure-pipeline-metrics-quickstart.yaml
Labels: approved, size/XS, lgtm, release-note, ok-to-test

#812 Install kn tasks only on architectures with knative client
  pkg/reconciler/openshift/tektonaddon/pipelinetemplates/pipelinetemplates.go
  pkg/reconciler/openshift/tektonaddon/tektonaddon.go
Labels: approved, lgtm, size/M, release-note-none, ok-to-test

#811 Updates Hub CR to prevent loss of data on operator upgradation
  pkg/reconciler/kubernetes/tektonhub/tektonhub.go
Labels: approved, lgtm, size/M, release-note

#814 [Cherry-pick] Updates Hub CR to prevent loss of data on operator upgradation
  pkg/reconciler/kubernetes/tektonhub/tektonhub.go
Labels: approved, lgtm, size/M, release-note

#817 [cherry-pick] move prune commands to single container
  pkg/reconciler/common/prune.go
  pkg/reconciler/common/prune_test.go
Labels: approved, lgtm, release-note, size/L

#815 Replace polling based logic in reconcilers with requeue
  pkg/reconciler/common/common.go
  pkg/reconciler/kubernetes/tektonconfig/extension.go
  pkg/reconciler/kubernetes/tektonconfig/extension/dashboard.go
  pkg/reconciler/kubernetes/tektonconfig/extension/dashboard_test.go
  pkg/reconciler/openshift/tektonconfig/extension.go
  pkg/reconciler/openshift/tektonconfig/extension/addon.go
  pkg/reconciler/openshift/tektonconfig/extension/addon_test.go
  pkg/reconciler/shared/tektonconfig/pipeline/pipeline.go
  pkg/reconciler/shared/tektonconfig/pipeline/pipeline_test.go
  pkg/reconciler/shared/tektonconfig/tektonconfig.go
  pkg/reconciler/shared/tektonconfig/trigger/trigger.go
  pkg/reconciler/shared/tektonconfig/trigger/trigger_test.go
  test/e2e/common/00_tektonconfigdeployment_test.go
  test/utils/cleanup.go
  test/utils/config.go
Labels: approved, lgtm, release-note, size/XL
