Repository tektoncd/operator, pull requests merged in 2022-08, with the labels that each got.

#949 Add support for --local for ko
  DEVELOPMENT.md
  Makefile
Labels: approved, size/XS, lgtm, release-note, ok-to-test

#956 Bump tekton pipelines to v0.37.3
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
  test/config.sh
Labels: approved, size/XS, lgtm, release-note

#933 Add a workflow to automatically bump versions on main
  .github/workflows/bump-payload-on-main.yaml
  .github/workflows/bump-payload-on-releases.yaml
Labels: approved, lgtm, size/M, release-note-none

#954 Fix the validation in tektonpipeline and tektontrigger
  pkg/apis/operator/v1alpha1/tektonpipeline_validation.go
  pkg/apis/operator/v1alpha1/tektonpipeline_validation_test.go
  pkg/apis/operator/v1alpha1/tektontrigger_validation.go
  pkg/apis/operator/v1alpha1/tektontrigger_validation_test.go
Labels: approved, lgtm, size/M, release-note

#958 [cherry-pick] Run maven and openshift-client as non-root
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/maven/maven-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/openshift-client/openshift-client-task.yaml
Labels: approved, size/XS, lgtm, release-note

#959 [cherry-pick] Run maven and openshift-client as non-root
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/maven/maven-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/openshift-client/openshift-client-task.yaml
Labels: approved, size/XS, lgtm, release-note

#953 fix secret detach from SA
  pkg/reconciler/openshift/tektonconfig/extension.go
  pkg/reconciler/openshift/tektonconfig/rbac.go
Labels: approved, lgtm, size/M, release-note

#957 Run maven and openshift-client as non-root
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/maven/maven-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/openshift-client/openshift-client-task.yaml
Labels: approved, size/XS, lgtm, release-note

#963 [Cherry-pick] [OpenShit] fix secret detach from SA
  pkg/reconciler/openshift/tektonconfig/extension.go
  pkg/reconciler/openshift/tektonconfig/rbac.go
Labels: approved, lgtm, size/M, release-note

#964 [Cherry-pick] [OpenShit] fix secret detach from SA
  pkg/reconciler/openshift/tektonconfig/extension.go
  pkg/reconciler/openshift/tektonconfig/rbac.go
Labels: approved, lgtm, size/M, release-note

#960 [Cherry-pick] [OpenShit] Skip RBAC setup in namespaces which are being deleted
  pkg/reconciler/openshift/tektonconfig/rbac.go
Labels: approved, size/XS, lgtm, release-note

#967 Update pac version to 0.10.2
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
  tekton/operator-release-pipeline.yaml
  tekton/task-fetch-components.yaml
  test/config.sh
Labels: approved, lgtm, size/S, release-note

#975 Bump catalog task versions to latest
  hack/openshift/fetch-tektoncd-catalog-tasks.sh
Labels: approved, lgtm, size/S, release-note

#976 Bump to tektoncd/pipeline to v0.37.4
  go.mod
  go.sum
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
  test/config.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S, release-note

#977 [Cherry Pick] Bump catalog task versions to latest
  hack/openshift/fetch-tektoncd-catalog-tasks.sh
Labels: approved, lgtm, size/S, release-note

#983 Bump golangci-lint to v1.47.2 to support Go 1.18
  .gitignore
  Makefile
Labels: approved, lgtm, size/S, release-note-none, kind/misc

#981 [Cherry-pick] Fixes pac in addon for config(nodeselector, tolerations) changes
  pkg/reconciler/openshift/tektonaddon/clustertTask.go
  pkg/reconciler/openshift/tektonaddon/clustertTaskVersioned.go
  pkg/reconciler/openshift/tektonaddon/communityClusterTasks.go
  pkg/reconciler/openshift/tektonaddon/extension.go
  pkg/reconciler/openshift/tektonaddon/installerset.go
  pkg/reconciler/openshift/tektonaddon/pipelinesascode.go
  pkg/reconciler/openshift/tektonaddon/pipelinetemplate.go
  pkg/reconciler/openshift/tektonaddon/triggers.go
  third_party/github.com/hashicorp/go-rootcerts/rootcerts_base.go
  third_party/github.com/hashicorp/go-sockaddr/ifaddrs.go
  third_party/github.com/hashicorp/go-sockaddr/route_info_android.go
  third_party/github.com/hashicorp/go-sockaddr/route_info_bsd.go
  third_party/github.com/hashicorp/go-sockaddr/route_info_default.go
  third_party/github.com/hashicorp/go-sockaddr/route_info_linux.go
  third_party/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
Labels: approved, lgtm, size/M, release-note

#982 Fixes pac in addon for config(nodeselector, tolerations) changes
  pkg/reconciler/openshift/tektonaddon/clustertTask.go
  pkg/reconciler/openshift/tektonaddon/clustertTaskVersioned.go
  pkg/reconciler/openshift/tektonaddon/communityClusterTasks.go
  pkg/reconciler/openshift/tektonaddon/extension.go
  pkg/reconciler/openshift/tektonaddon/installerset.go
  pkg/reconciler/openshift/tektonaddon/pipelinesascode.go
  pkg/reconciler/openshift/tektonaddon/pipelinetemplate.go
  pkg/reconciler/openshift/tektonaddon/triggers.go
  third_party/github.com/hashicorp/go-rootcerts/rootcerts_base.go
  third_party/github.com/hashicorp/go-sockaddr/ifaddrs.go
  third_party/github.com/hashicorp/go-sockaddr/route_info_android.go
  third_party/github.com/hashicorp/go-sockaddr/route_info_bsd.go
  third_party/github.com/hashicorp/go-sockaddr/route_info_default.go
  third_party/github.com/hashicorp/go-sockaddr/route_info_linux.go
  third_party/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
Labels: approved, lgtm, size/M, release-note

#978 Fix to update Hub ConfigMap values
  pkg/reconciler/kubernetes/tektonhub/installerset.go
  pkg/reconciler/kubernetes/tektonhub/tektonhub.go
Labels: approved, lgtm, release-note, size/L

#989 [0.60.x] [cherry-pick] Allow specifying maxOpenShiftVersion for CSV
  operatorhub/tools/bundle.py
Labels: approved, size/XS, lgtm, release-note-none

#984 [Cherry-Pick] Fix to update Hub ConfigMap values
  pkg/reconciler/kubernetes/tektonhub/installerset.go
  pkg/reconciler/kubernetes/tektonhub/tektonhub.go
Labels: approved, lgtm, release-note, size/L

#993 [OpenShift] updates the OSP icon 😇
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
Labels: approved, lgtm, release-note, size/L

#994 [Cherry-pick] [OpenShift] updates the OSP icon 😇
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
Labels: approved, lgtm, release-note, size/L

#991 [Cherry-pick] [OpenShift] removes obselete service monitor rbac from bundle
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-operator-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-operator-read_rbac.authorization.k8s.io_v1_role.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-operators-prometheus-k8s-read-binding_rbac.authorization.k8s.io_v1_rolebinding.yaml
Labels: size/M, release-note

#961 [Cherry-pick] [OpenShit] Skip RBAC setup in namespaces which are being deleted
  pkg/reconciler/openshift/tektonconfig/rbac.go
Labels: approved, size/XS, release-note

#995 [Cherry-pick] [OpenShift] removes obselete service monitor rbac from bundle
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-operator-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-operator-read_rbac.authorization.k8s.io_v1_role.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-operators-prometheus-k8s-read-binding_rbac.authorization.k8s.io_v1_rolebinding.yaml
Labels: approved, lgtm, size/M, release-note

#992 Fixing bump-payloads github workflows
  .github/workflows/bump-payload-on-main.yaml
  .github/workflows/bump-payload-on-releases.yaml
Labels: approved, lgtm, size/S, release-note-none, kind/misc

#997 [CP] [0.60.x] Set HOME to /tekton/home for nonroot tasks
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/maven/maven-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/openshift-client/openshift-client-task.yaml
Labels: approved, lgtm, size/S, release-note

#999 [OpenShift] updates hub link icon to new OSP icon
  cmd/openshift/operator/kodata/openshift/tekton-hub/01-consolelink-hub.yaml
Labels: approved, lgtm, release-note, size/L

#1000 [Cherry-pick] [OpenShift] updates hub link icon to new OSP icon
  cmd/openshift/operator/kodata/openshift/tekton-hub/01-consolelink-hub.yaml
Labels: approved, lgtm, release-note, size/L

#996 Set HOME to /tekton/home for nonroot tasks
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/maven/maven-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/openshift-client/openshift-client-task.yaml
Labels: approved, lgtm, size/S, release-note

#1001 .github/workflows: fixing committer & author
  .github/workflows/bump-payload-on-main.yaml
  .github/workflows/bump-payload-on-releases.yaml
Labels: approved, lgtm, size/S, release-note-none, kind/misc

#1002 .github/workflows: re-add token to bump-payload-on-releases
  .github/workflows/bump-payload-on-releases.yaml
Labels: approved, size/XS, lgtm, release-note-none, kind/misc

#892 Updates Hub docs based on the new changes of Hub v1.8.0
  docs/TektonHub.md
Labels: approved, lgtm, size/M, release-note

#1003 [Cherry-pick] Fix hub ui configmap not getting created properly
  pkg/apis/operator/v1alpha1/tektonhub_lifecycle.go
  pkg/apis/operator/v1alpha1/tektonhub_lifecycle_test.go
  pkg/reconciler/kubernetes/tektonhub/installerset.go
  pkg/reconciler/kubernetes/tektonhub/tektonhub.go
Labels: approved, lgtm, release-note, size/L

#990 [OpenShift] removes obselete service monitor rbac from bundle
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-operator-monitor_monitoring.coreos.com_v1_servicemonitor.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-operator-read_rbac.authorization.k8s.io_v1_role.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-operators-prometheus-k8s-read-binding_rbac.authorization.k8s.io_v1_rolebinding.yaml
Labels: approved, lgtm, size/M, release-note

#1004 Fix hub ui configmap not getting created properly
  pkg/apis/operator/v1alpha1/tektonhub_lifecycle.go
  pkg/apis/operator/v1alpha1/tektonhub_lifecycle_test.go
  pkg/reconciler/kubernetes/tektonhub/installerset.go
  pkg/reconciler/kubernetes/tektonhub/tektonhub.go
Labels: approved, lgtm, release-note, size/L

#906 Removes deprecated fields
  go.mod
  pkg/apis/operator/v1alpha1/tektonpipeline_defaults.go
  pkg/apis/operator/v1alpha1/tektonpipeline_defaults_test.go
  pkg/apis/operator/v1alpha1/tektonpipeline_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/M, release-note

#1007 .github/workflows : trying to use sign-off
  .github/workflows/bump-payload-on-main.yaml
  .github/workflows/bump-payload-on-releases.yaml
Labels: approved, size/XS, lgtm, release-note-none, kind/misc

#1006 Setups workflow to create helm chart releases
  .github/workflows/helm-release.yaml
Labels: approved, lgtm, size/M, release-note

#1016 Fix expression in fetch component release task
  tekton/task-fetch-components.yaml
Labels: approved, size/XS, lgtm, release-note-none

#1019 Update helm chart for v0.61.0 release
  chart/Chart.yaml
  chart/templates/deployment.yaml
  chart/templates/kubernetes-crds.yaml
  chart/templates/openshift-crds.yaml
  chart/templates/secret.yaml
Labels: approved, lgtm, release-note, size/L

#1020 Changes helm chart name to tekton-operator
  chart/Chart.yaml
Labels: approved, size/XS, lgtm, release-note

#1017 Fix yamllint warnings
  .github/workflows/bump-payload-on-main.yaml
  .github/workflows/bump-payload-on-releases.yaml
  .github/workflows/helm-release.yaml
  .github/workflows/projects.yaml
  .yamllint
  chart/values.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/buildah/buildah-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/04-consolecli/console_cli_download_tkn.yaml
  cmd/openshift/operator/kodata/tekton-addon/pipelines-as-code-templates/rbac.yaml
  config/base/300-operator_v1alpha1_installer_set_crd.yaml
  config/base/300-operator_v1alpha1_pipeline_crd.yaml
  config/crs/kubernetes/config/all/operator_v1alpha1_config_cr.yaml
  config/crs/kubernetes/config/basic/operator_v1alpha1_config_cr.yaml
  config/crs/kubernetes/config/lite/operator_v1alpha1_config_cr.yaml
  config/crs/openshift/config/basic/operator_v1alpha1_config_cr.yaml
  config/crs/openshift/config/lite/operator_v1alpha1_config_cr.yaml
  config/kubernetes/base/300-operator_v1alpha1_dashboard_crd.yaml
  config/kubernetes/base/operator.yaml
  config/kubernetes/base/operator_service.yaml
  config/kubernetes/base/webhook.yaml
  config/openshift/base/operator.yaml
  config/openshift/base/operator_service.yaml
  operatorhub/kubernetes/config.yaml
  operatorhub/kubernetes/manifests/bases/tektoncd-operator.clusterserviceversion.template.yaml
  operatorhub/openshift/config.yaml
  pkg/reconciler/common/testdata/inject-label/01-sample-tektoncd-pipelines-release.yaml
  pkg/reconciler/common/testdata/inject-label/02-no-predicates-test-expected-result.yaml
  pkg/reconciler/common/testdata/inject-label/03-with-skipchecks-test-expected-result.yaml
  pkg/reconciler/common/testdata/inject-label/04-operand-label-expected-result.yaml
  pkg/reconciler/common/testdata/inject-label/05-existing-labels-release.yaml
  pkg/reconciler/common/testdata/inject-label/06-existing-labels-release-expected.yaml
  pkg/reconciler/common/testdata/test-add-configurations.yaml
  pkg/reconciler/common/testdata/test-fetch-version-from-crds.yaml
  pkg/reconciler/common/testdata/test-inject-label-kind-set.yaml
  pkg/reconciler/common/testdata/test-replace-addon-image.yaml
  pkg/reconciler/common/testdata/test-replace-cm-values.yaml
  pkg/reconciler/common/testdata/test-replace-image.yaml
  pkg/reconciler/common/testdata/test-replace-kind.yaml
  pkg/reconciler/common/testdata/test_delete_obsolete_resources/dummy.release.notags.yaml
  pkg/reconciler/kubernetes/tektoninstallerset/testdata/test-crd.yaml
  pkg/reconciler/kubernetes/tektoninstallerset/testdata/test-non-crd.yaml
  pkg/reconciler/openshift/tektonaddon/testdata/test-versioned-clustertask-name-expected.yaml
  pkg/reconciler/openshift/tektonaddon/testdata/test-versioned-clustertask-name.yaml
  pkg/reconciler/openshift/tektonhub/testdata/update-db-deployment.yaml
Labels: approved, lgtm, release-note-none, size/L

#1024 .git/workflows: use the right job name 🙃
  .github/workflows/bump-payload-on-releases.yaml
Labels: approved, size/XS, lgtm, release-note-none, kind/misc

#1023 Update ko to use latest with go 1.18 as 0.9.x isn't compatible
  Makefile
Labels: approved, size/XS, lgtm, release-note

#1030 Make dockerconfig workspace optional to keep backward compatible
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/buildah/buildah-task.yaml
Labels: approved, size/XS, lgtm, release-note
