Repository tektoncd/operator, pull requests merged in 2022-09, with the labels that each got.

#1029 TektonInstallerSet Improvement: uses hash to decide updating a resource
  pkg/reconciler/kubernetes/tektoninstallerset/install.go
  pkg/reconciler/kubernetes/tektoninstallerset/install_test.go
  pkg/reconciler/kubernetes/tektoninstallerset/tektoninstallerset.go
  third_party/github.com/hashicorp/go-retryablehttp/README.md
  third_party/github.com/hashicorp/go-retryablehttp/client.go
  third_party/github.com/hashicorp/go-rootcerts/rootcerts_base.go
  third_party/github.com/hashicorp/go-secure-stdlib/parseutil/parsepath.go
  third_party/github.com/hashicorp/go-sockaddr/ifaddrs.go
  third_party/github.com/hashicorp/go-sockaddr/route_info_android.go
  third_party/github.com/hashicorp/go-sockaddr/route_info_bsd.go
  third_party/github.com/hashicorp/go-sockaddr/route_info_default.go
  third_party/github.com/hashicorp/go-sockaddr/route_info_linux.go
  third_party/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
  third_party/github.com/thlib/go-timezone-local/tzlocal/LICENSE
  vendor/go.uber.org/zap/zaptest/observer/logged_entry.go
  vendor/go.uber.org/zap/zaptest/observer/observer.go
  vendor/modules.txt
Labels: approved, lgtm, release-note, size/XL

#1040 Use the correct repository URL for openshift CSV
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
Labels: approved, size/XS, lgtm, release-note, kind/misc

#1039 [Openshift] Add clustertriggerbinding for bitbucket cloud
  cmd/openshift/operator/kodata/tekton-addon/addons/01-clustertriggerbindings/bitbucket-cloud.yaml
Labels: approved, lgtm, size/M, release-note

#1042 Exit script with PIPESTATUS instead of exit code
  operatorhub/tools/bundle.py
Labels: approved, size/XS, lgtm, release-note-none

#1044 Add ApplyCABundles transformer to PAC
  pkg/reconciler/openshift/tektonaddon/pipelinesascode.go
Labels: approved, size/XS, lgtm, release-note

#1050 .github/workflows: Trying to fix workflows
  .github/workflows/bump-payload-on-releases.yaml
  .github/workflows/projects.yaml
Labels: approved, lgtm, size/M, release-note-none

#1052 .github/workflows: remove dependency on commented job
  .github/workflows/bump-payload-on-releases.yaml
Labels: approved, size/XS, lgtm, release-note-none

#1053 .github/workflows: fix workflow_dispatch…
  .github/workflows/bump-payload-on-releases.yaml
Labels: approved, size/XS, lgtm, release-note-none

#1035 Skip fetching release file if already exist with required version
  Makefile
  hack/fetch-releases.sh
Labels: approved, lgtm, size/S, release-note

#1063 Bump tektoncd/pipeline component to 0.40.0…
  components.yaml
  config/base/role.yaml
Labels: approved, size/XS, lgtm, release-note-none

#1066 Adds piyush-garg as owner :)
  OWNERS
Labels: approved, size/XS, lgtm, release-note

#1071 Bump hub to v1.10.0 in components.nightly.yaml
  components.nightly.yaml
Labels: approved, size/XS, lgtm, release-note-none, kind/misc

#1069 Release: update release cheat-sheet…
  hack/release-commands.sh
  hack/release-common.sh
  hack/release-const.sh
  hack/release-freeze-component-versions.sh
  hack/release-setup-branch.sh
  tekton/release-cheat-sheet.md
  tekton/task-fetch-components.yaml
Labels: approved, lgtm, size/XL, release-note-none

#809 Fix warning on OCP 4.11 cluster for operator install
  cmd/openshift/operator/kodata/tekton-addon/addons/05-tkncliserve/tkn_cli_serve.yaml
  cmd/openshift/operator/kodata/webhook/webhook.yaml
  config/openshift/base/operator.yaml
  config/openshift/base/webhook.yaml
Labels: approved, lgtm, size/M, release-note

#965 Merge in changes from builah catalog task 0.4
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/buildah/buildah-task.yaml
Labels: approved, size/XS, lgtm, release-note, ok-to-test

#1075 PAC: creates pipelinerun templates in openshift namespace
  pkg/reconciler/openshift/tektonaddon/pipelinesascode.go
Labels: approved, lgtm, size/S, release-note

#1077 Cleanup: removes obsolete func from TektonComponent
  pkg/apis/operator/v1alpha1/common.go
  pkg/apis/operator/v1alpha1/tektonaddon_lifecycle.go
  pkg/apis/operator/v1alpha1/tektonchain_lifecycle.go
  pkg/apis/operator/v1alpha1/tektonconfig_lifecycle.go
  pkg/apis/operator/v1alpha1/tektondashboard_lifecycle.go
  pkg/apis/operator/v1alpha1/tektonhub_lifecycle.go
  pkg/apis/operator/v1alpha1/tektonpipeline_lifecycle.go
  pkg/apis/operator/v1alpha1/tektonresult_lifecycle.go
  pkg/apis/operator/v1alpha1/tektontrigger_lifecycle.go
  pkg/reconciler/common/deployments.go
  pkg/reconciler/common/install.go
  pkg/reconciler/common/releases.go
  pkg/reconciler/common/stages.go
  pkg/reconciler/common/transformers.go
  pkg/reconciler/kubernetes/tektondashboard/tektondashboard.go
  pkg/reconciler/kubernetes/tektonresult/tektonresult.go
Labels: approved, lgtm, release-note, size/L

#1078 Allow config.json, .dockerconfigjson in buildah ClusterTask
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/buildah/buildah-task.yaml
Labels: approved, lgtm, size/S, release-note

#1074 [Cherry-pick] PAC: creates pipelinerun templates in openshift namespace
  pkg/reconciler/openshift/tektonaddon/pipelinesascode.go
Labels: approved, lgtm, size/S, release-note
