Repository tektoncd/operator, pull requests merged in 2022-03, with the labels that each got.

#635 Add ServiceMonitor for Triggers metrics
  cmd/openshift/operator/kodata/openshift-monitoring/01-trigger-monitoring.yaml
Labels: approved, lgtm, size/M, release-note-none

#638 Updates Addon finalizer to delete all installerSet by label
  pkg/reconciler/openshift/tektonaddon/tektonaddon.go
Labels: approved, lgtm, size/S, release-note

#639 Disabling removed feature flags in Pipleines v0.33.0
  docs/TektonPipeline.md
  pkg/apis/operator/v1alpha1/tektonpipeline_defaults.go
  pkg/apis/operator/v1alpha1/tektonpipeline_defaults_test.go
  pkg/apis/operator/v1alpha1/tektonpipeline_types.go
Labels: approved, lgtm, size/M, release-note

#640 Update pac version to v0.5.3
  Makefile
Labels: approved, size/XS, lgtm, release-note

#644 Updates TektonConfig CRD to show installed operator version
  config/base/300-operator_v1alpha1_config_crd.yaml
Labels: approved, size/XS, lgtm, release-note

#642 Updates argocd-task-sync-and-wait tasks to v0.2
  pkg/reconciler/openshift/tektonaddon/clustertTask.go
Labels: approved, size/XS, lgtm, release-note

#646 remove maven task from community tasks list
  pkg/reconciler/openshift/tektonaddon/clustertTask.go
Labels: approved, size/XS, lgtm, release-note

#647 change cmd/ko to ko
  Makefile
Labels: approved, size/XS, lgtm, release-note

#645 Improves error handling in TektonHub and reorder the job in TektonInstallerSet
  pkg/reconciler/kubernetes/tektonhub/tektonhub.go
  pkg/reconciler/kubernetes/tektoninstallerset/install.go
  pkg/reconciler/kubernetes/tektoninstallerset/install_test.go
  pkg/reconciler/kubernetes/tektoninstallerset/tektoninstallerset.go
Labels: approved, lgtm, size/M, release-note

#649 [OpenShift] filter out namespace from pac manifest
  pkg/reconciler/openshift/tektonaddon/pipelinesascode.go
Labels: approved, size/XS, lgtm, release-note

#650 Add config owner reference while creating components
  pkg/reconciler/kubernetes/tektonconfig/extension/dashboard.go
  pkg/reconciler/shared/tektonconfig/pipeline/pipeline.go
  pkg/reconciler/shared/tektonconfig/trigger/trigger.go
Labels: approved, lgtm, size/S, release-note

#479 Adds Hub UI Component in operator
  config/base/300-operator_v1alpha1_hub_crd.yaml
  hack/fetch-releases.sh
  pkg/apis/operator/v1alpha1/tektonhub_defaults.go
  pkg/apis/operator/v1alpha1/tektonhub_lifecycle.go
  pkg/apis/operator/v1alpha1/tektonhub_lifecycle_test.go
  pkg/apis/operator/v1alpha1/tektonhub_types.go
  pkg/apis/operator/v1alpha1/tektonhub_validation.go
  pkg/reconciler/kubernetes/tektonhub/tektonhub.go
  pkg/reconciler/openshift/tektonhub/extension.go
Labels: approved, lgtm, release-note, size/L

#636 Updates Hub Db deployment in case of Openshift
  config/openshift/base/operator.yaml
  pkg/reconciler/common/transformers.go
  pkg/reconciler/kubernetes/tektonhub/tektonhub.go
  pkg/reconciler/openshift/tektonhub/extension.go
  pkg/reconciler/openshift/tektonhub/extension_test.go
  pkg/reconciler/openshift/tektonhub/testdata/update-db-deployment.yaml
Labels: approved, lgtm, release-note, size/L

#648 Mount CA bundles in Tekton components as well
  pkg/reconciler/common/certificates.go
  pkg/reconciler/openshift/common/cabundle.go
  pkg/reconciler/openshift/common/cabundle_test.go
  pkg/reconciler/proxy/proxy.go
  pkg/reconciler/proxy/proxy_test.go
Labels: approved, lgtm, release-note-none, size/L

#634 [OpenShift] Fix RBAC bugs
  pkg/reconciler/openshift/tektonconfig/common.go
  pkg/reconciler/openshift/tektonconfig/extension.go
  pkg/reconciler/openshift/tektonconfig/rbac.go
  pkg/reconciler/shared/tektonconfig/controller.go
  test/e2e/common/00_tektonconfigdeployment_test.go
Labels: approved, lgtm, release-note, size/L

#653 Add unit tests for SSL certs behavior
  pkg/reconciler/common/certificates_test.go
Labels: approved, lgtm, release-note-none, size/L

#657 Make TektonChain out of all profile
  docs/README.md
  docs/TektonChain.md
  docs/TektonConfig.md
  pkg/reconciler/kubernetes/tektonchain/controller.go
  pkg/reconciler/shared/tektonconfig/chain/chain.go
  pkg/reconciler/shared/tektonconfig/chain/chain_test.go
  pkg/reconciler/shared/tektonconfig/controller.go
  pkg/reconciler/shared/tektonconfig/tektonconfig.go
  test/e2e/common/00_tektonconfigdeployment_test.go
Labels: approved, lgtm, release-note, size/L

#659 Add chains image env for openshift
  operatorhub/openshift/config.yaml
Labels: approved, size/XS, lgtm, release-note-none

#662 Fix fetch-release.sh 👼
  hack/fetch-releases.sh
Labels: approved, size/XS, lgtm, release-note-none

#661 Fixes the db name in transformer in case of openshift
  pkg/reconciler/openshift/tektonhub/extension.go
  pkg/reconciler/openshift/tektonhub/testdata/update-db-deployment.yaml
Labels: approved, lgtm, size/S, release-note

#660 Add hub image env for openshift
  config/openshift/base/operator.yaml
  operatorhub/openshift/config.yaml
  pkg/reconciler/common/transformers.go
  pkg/reconciler/kubernetes/tektonhub/tektonhub.go
Labels: approved, lgtm, size/M, release-note-none

#658 Option to disable community tasks
  config/crs/openshift/config/all/operator_v1alpha1_config_cr.yaml
  pkg/apis/operator/v1alpha1/const.go
  pkg/apis/operator/v1alpha1/tektonaddon_default_test.go
  pkg/apis/operator/v1alpha1/tektonaddon_validation.go
  pkg/apis/operator/v1alpha1/tektonconfig_default_test.go
  pkg/reconciler/openshift/tektonaddon/clustertTask.go
  pkg/reconciler/openshift/tektonaddon/communityClusterTasks.go
  pkg/reconciler/openshift/tektonaddon/const.go
  pkg/reconciler/openshift/tektonaddon/tektonaddon.go
  test/resources/tektonaddons.go
  test/resources/tektonconfigs.go
Labels: approved, lgtm, release-note, size/L

#663 Adds Hub and Chains CRD as internal objects on Openshift
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
Labels: approved, size/XS, lgtm, release-note

#669 Fixes the value for `REDIRECT_URI` in the Hub UI configMap
  pkg/reconciler/kubernetes/tektonhub/tektonhub.go
Labels: approved, size/XS, lgtm, release-note

#668 Catch generate_bundle() error and exit
  operatorhub/tools/bundle.py
Labels: approved, size/XS, lgtm, release-note-none

#674 Add new transformer for triggers on openshift
  Makefile
  pkg/reconciler/common/transformers.go
  pkg/reconciler/openshift/tektontrigger/extension.go
  pkg/reconciler/openshift/tektontrigger/testdata/test-replace-image.yaml
  pkg/reconciler/openshift/tektontrigger/testdata/test-replace-kind.yaml
  pkg/reconciler/openshift/tektontrigger/transformers.go
  pkg/reconciler/openshift/tektontrigger/transformers_test.go
Labels: approved, lgtm, release-note, size/L

#675 [Cherry-pick] Add new transformer for triggers on openshift
  Makefile
  pkg/reconciler/common/transformers.go
  pkg/reconciler/openshift/tektontrigger/extension.go
  pkg/reconciler/openshift/tektontrigger/testdata/test-replace-image.yaml
  pkg/reconciler/openshift/tektontrigger/testdata/test-replace-kind.yaml
  pkg/reconciler/openshift/tektontrigger/transformers.go
  pkg/reconciler/openshift/tektontrigger/transformers_test.go
Labels: approved, lgtm, release-note, size/L

#671 [cherry-pick] Catch generate_bundle() error and exit
  operatorhub/tools/bundle.py
Labels: approved, size/XS, lgtm, release-note-none

#664 Replace PAC images in TriggerTemplates
  operatorhub/openshift/config.yaml
  pkg/reconciler/common/transformers.go
  pkg/reconciler/openshift/tektonaddon/pipelinesascode.go
  pkg/reconciler/openshift/tektonaddon/testdata/test-triggertemplate-taskrun.yaml
  pkg/reconciler/openshift/tektonaddon/transformer.go
  pkg/reconciler/openshift/tektonaddon/transformer_test.go
Labels: approved, lgtm, size/XXL, release-note-none

#666 [cherry-pick] Replace PAC images in TriggerTemplates
  operatorhub/openshift/config.yaml
  pkg/reconciler/common/transformers.go
  pkg/reconciler/openshift/tektonaddon/pipelinesascode.go
  pkg/reconciler/openshift/tektonaddon/testdata/test-triggertemplate-taskrun.yaml
  pkg/reconciler/openshift/tektonaddon/transformer.go
  pkg/reconciler/openshift/tektonaddon/transformer_test.go
Labels: approved, lgtm, size/XXL, release-note-none

#667 Update Hub docs to add additional info to get all resources
  docs/TektonHub.md
Labels: approved, lgtm, size/M, release-note

#684 [cherry-pick] Remove redundant 'UpdateStatus()' calls
  pkg/reconciler/kubernetes/tektondashboard/tektondashboard.go
  pkg/reconciler/kubernetes/tektonhub/installerset.go
  pkg/reconciler/kubernetes/tektonpipeline/tektonpipeline.go
  pkg/reconciler/kubernetes/tektontrigger/tektontrigger.go
  pkg/reconciler/openshift/tektonconfig/common.go
  pkg/reconciler/openshift/tektonpipeline/installerset.go
Labels: approved, lgtm, size/M, release-note

#683 Remove redundant 'UpdateStatus()' calls
  pkg/reconciler/kubernetes/tektondashboard/tektondashboard.go
  pkg/reconciler/kubernetes/tektonhub/installerset.go
  pkg/reconciler/kubernetes/tektonpipeline/tektonpipeline.go
  pkg/reconciler/kubernetes/tektontrigger/tektontrigger.go
  pkg/reconciler/openshift/tektonconfig/common.go
  pkg/reconciler/openshift/tektonpipeline/installerset.go
Labels: approved, lgtm, size/M, release-note

#685 [cherry-pick] adds missing provider lablels in the clustertasks
  pkg/reconciler/openshift/tektonaddon/clustertTask.go
  pkg/reconciler/openshift/tektonaddon/clustertTaskVersioned.go
Labels: approved, size/XS, lgtm, release-note

#680 adds missing provider lablels in the clustertasks
  pkg/reconciler/openshift/tektonaddon/clustertTask.go
  pkg/reconciler/openshift/tektonaddon/clustertTaskVersioned.go
Labels: approved, size/XS, lgtm, release-note

#687 Updates pac version to 0.5.4
  Makefile
Labels: approved, size/XS, lgtm, release-note

#673 Creates the operator version configMap in the operator namespace
  config/base/kustomization.yaml
  config/base/operator-config.yaml
  pkg/reconciler/kubernetes/tektonpipeline/tektonpipeline.go
  pkg/reconciler/shared/tektonconfig/tektonconfig.go
Labels: approved, lgtm, size/M, release-note

#689 [Cherry-pick] Creates the operator version configMap in the operator namespace
  config/base/kustomization.yaml
  config/base/operator-config.yaml
  pkg/reconciler/kubernetes/tektonpipeline/tektonpipeline.go
  pkg/reconciler/shared/tektonconfig/tektonconfig.go
Labels: approved, lgtm, size/M, release-note

#700 Use CI image `ko` instead of trying to install it
  test/e2e-common.sh
Labels: approved, size/XS, lgtm, release-note-none, kind/misc

#699 [openshift] change maven task image
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/maven/maven-task.yaml
Labels: approved, size/XS, lgtm, release-note

#691 [openshift] Replace version with a variable in docs link
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
Labels: approved, size/XS, lgtm, release-note

#697 Updates hub version to 1.7.1 and fixes variables
  Makefile
  test/config.sh
  test/e2e-common.sh
  test/resources/verify.go
Labels: approved, lgtm, size/S, release-note

#701 Freeze ko version to v0.9.3
  Makefile
Labels: approved, lgtm, size/S, release-note

#695 Add replacement environment variable for `workingdirinit-image`
  operatorhub/openshift/config.yaml
Labels: approved, size/XS, lgtm, release-note

#693 [openshift] Add ubi-minimal to fetch-latest-sha script
  config/openshift/base/operator.yaml
  hack/openshift/update-image-sha.sh
  operatorhub/openshift/config.yaml
Labels: approved, lgtm, size/S, release-note

#707 Freeze ko version to v0.9.3
  Makefile
Labels: approved, lgtm, size/S, release-note

#696 [cherry-pick]Add replacement environment variable for `workingdirinit-image`
  operatorhub/openshift/config.yaml
Labels: approved, size/XS, lgtm, release-note

#703 [CP] [openshift] change maven task image
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/maven/maven-task.yaml
Labels: approved, size/XS, lgtm, release-note

#692 [cherry-pick][openshift] Replace version with a variable in docs link
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
Labels: approved, size/XS, lgtm, release-note

#706 [cherry-pick] Improve error log in tektonconfig instance creation
  pkg/reconciler/shared/tektonconfig/instance.go
Labels: approved, size/XS, lgtm, release-note

#709 Remove go get in favour of go install
  Makefile
Labels: approved, size/XS, lgtm, release-note-none

#702 Removes security context for Hub Api deployment in case of openshift
  pkg/reconciler/openshift/common/testdata/test-remove-fs-group-expected.yaml
  pkg/reconciler/openshift/common/testdata/test-remove-fs-group.yaml
  pkg/reconciler/openshift/common/transformer.go
  pkg/reconciler/openshift/common/transformer_test.go
  pkg/reconciler/openshift/tektonhub/extension.go
Labels: approved, lgtm, release-note, size/L

#704 [Cherry-pick] Removes security context for Hub Api deployment in case of openshift
  pkg/reconciler/openshift/common/testdata/test-remove-fs-group-expected.yaml
  pkg/reconciler/openshift/common/testdata/test-remove-fs-group.yaml
  pkg/reconciler/openshift/common/transformer.go
  pkg/reconciler/openshift/common/transformer_test.go
  pkg/reconciler/openshift/tektonhub/extension.go
Labels: approved, lgtm, release-note, size/L

#715 Add operator info configmap rbac
  config/base/config-info.yaml
  config/base/config-info_role.yaml
  config/base/config-info_role_binding.yaml
  config/base/kustomization.yaml
  pkg/reconciler/common/targetnamespace.go
  pkg/reconciler/common/targetnamespace_test.go
  tekton/build-publish-images-manifests.yaml
Labels: approved, lgtm, release-note, size/L

#716 [Cherry-pick] Add operator info configmap rbac
  config/base/config-info.yaml
  config/base/config-info_role.yaml
  config/base/config-info_role_binding.yaml
  config/base/kustomization.yaml
  pkg/reconciler/common/targetnamespace.go
  pkg/reconciler/common/targetnamespace_test.go
  tekton/build-publish-images-manifests.yaml
Labels: approved, lgtm, release-note, size/L

#713 Replace imperative Requeue calls with a declarative Requeue event
  pkg/apis/operator/v1alpha1/const.go
  pkg/reconciler/kubernetes/tektonchain/controller.go
  pkg/reconciler/kubernetes/tektonchain/tektonchain.go
  pkg/reconciler/kubernetes/tektondashboard/controller.go
  pkg/reconciler/kubernetes/tektondashboard/tektondashboard.go
  pkg/reconciler/kubernetes/tektonhub/controller.go
  pkg/reconciler/kubernetes/tektonhub/tektonhub.go
  pkg/reconciler/kubernetes/tektoninstallerset/controller.go
  pkg/reconciler/kubernetes/tektoninstallerset/tektoninstallerset.go
  pkg/reconciler/kubernetes/tektonpipeline/controller.go
  pkg/reconciler/kubernetes/tektonpipeline/tektonpipeline.go
  pkg/reconciler/kubernetes/tektontrigger/controller.go
  pkg/reconciler/kubernetes/tektontrigger/tektontrigger.go
  pkg/reconciler/openshift/tektonaddon/communityClusterTasks.go
  pkg/reconciler/openshift/tektonaddon/controller.go
  pkg/reconciler/openshift/tektonaddon/tektonaddon.go
  pkg/reconciler/shared/tektonconfig/controller.go
  pkg/reconciler/shared/tektonconfig/tektonconfig.go
Labels: approved, lgtm, release-note, size/L

#714 [cherry-pick] Replace imperative Requeue calls with a declarative Requeue event
  pkg/apis/operator/v1alpha1/const.go
  pkg/reconciler/kubernetes/tektonchain/controller.go
  pkg/reconciler/kubernetes/tektonchain/tektonchain.go
  pkg/reconciler/kubernetes/tektondashboard/controller.go
  pkg/reconciler/kubernetes/tektondashboard/tektondashboard.go
  pkg/reconciler/kubernetes/tektonhub/controller.go
  pkg/reconciler/kubernetes/tektonhub/tektonhub.go
  pkg/reconciler/kubernetes/tektoninstallerset/controller.go
  pkg/reconciler/kubernetes/tektoninstallerset/tektoninstallerset.go
  pkg/reconciler/kubernetes/tektonpipeline/controller.go
  pkg/reconciler/kubernetes/tektonpipeline/tektonpipeline.go
  pkg/reconciler/kubernetes/tektontrigger/controller.go
  pkg/reconciler/kubernetes/tektontrigger/tektontrigger.go
  pkg/reconciler/openshift/tektonaddon/communityClusterTasks.go
  pkg/reconciler/openshift/tektonaddon/controller.go
  pkg/reconciler/openshift/tektonaddon/tektonaddon.go
  pkg/reconciler/shared/tektonconfig/controller.go
  pkg/reconciler/shared/tektonconfig/tektonconfig.go
Labels: approved, lgtm, release-note, size/L

#712 Add a script to replace verion labels during a release
  hack/release-common.sh
  hack/release-setup-branch.sh
Labels: approved, lgtm, size/M, release-note

#720 [Cherry-pick] Adds console link instance for Hub
  cmd/openshift/operator/kodata/openshift/tekton-hub/01-consolelink-hub.yaml
  config/openshift/base/role.yaml
  pkg/reconciler/kubernetes/tektoninstallerset/install.go
  pkg/reconciler/openshift/tektonaddon/const.go
  pkg/reconciler/openshift/tektonhub/extension.go
Labels: approved, lgtm, release-note, size/L

#719 Adds console link instance for Hub
  cmd/openshift/operator/kodata/openshift/tekton-hub/01-consolelink-hub.yaml
  config/openshift/base/role.yaml
  pkg/reconciler/kubernetes/tektoninstallerset/install.go
  pkg/reconciler/openshift/tektonaddon/const.go
  pkg/reconciler/openshift/tektonhub/extension.go
Labels: approved, lgtm, release-note, size/L

#721 Updates the ConsoleLink logo from TektonHub to Openshift Pipelines
  cmd/openshift/operator/kodata/openshift/tekton-hub/01-consolelink-hub.yaml
Labels: approved, lgtm, size/M, release-note

#722 Updates the ConsoleLink section for Tekton Hub
  cmd/openshift/operator/kodata/openshift/tekton-hub/01-consolelink-hub.yaml
Labels: approved, size/XS, lgtm, release-note

#726 update pac to v0.5.5
  Makefile
  test/config.sh
Labels: approved, size/XS, lgtm, release-note

#724 [openshift] Use label selectors to find RBAC instalelr set name
  pkg/reconciler/openshift/tektonconfig/common.go
  pkg/reconciler/openshift/tektonconfig/rbac.go
Labels: approved, lgtm, size/M, release-note

#728 Fix quotes in version config map
  config/base/config-info.yaml
Labels: approved, size/XS, lgtm, release-note

#731 Bump PAC image tag in tests
  pkg/reconciler/openshift/tektonaddon/testdata/test-triggertemplate-taskrun.yaml
Labels: approved, lgtm, size/S, release-note-none

#723 [Cherry-pick] Updates the ConsoleLink section for Tekton Hub
  cmd/openshift/operator/kodata/openshift/tekton-hub/01-consolelink-hub.yaml
Labels: approved, size/XS, lgtm, release-note

#725 [cherry-pick][openshift] Use label selectors to find RBAC instalelr set name
  pkg/reconciler/openshift/tektonconfig/common.go
  pkg/reconciler/openshift/tektonconfig/rbac.go
Labels: approved, lgtm, size/M, release-note

#730 Bump PAC and Hub versions
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
  tekton/operator-release-pipeline.yaml
  tekton/task-fetch-components.yaml
Labels: approved, lgtm, size/S, release-note-none

#732 [cherry-pick] Bump PAC image tag in tests
  pkg/reconciler/openshift/tektonaddon/testdata/test-triggertemplate-taskrun.yaml
Labels: approved, lgtm, size/S, release-note-none

#735 [cherry-pick][openshift] Shell image/cherry pick
  config/openshift/base/operator.yaml
  operatorhub/openshift/config.yaml
Labels: approved, size/XS, lgtm, release-note

#734 [openshift] Add redhat.io ubi-minimal as SHELL_IMAGE
  config/openshift/base/operator.yaml
  operatorhub/openshift/config.yaml
Labels: approved, size/XS, lgtm, release-note
