Repository tektoncd/operator, pull requests merged in 2022-10, with the labels that each got.

#1082 Remove unused issue template
  .github/issue-template.md
Labels: approved, lgtm, size/S, release-note-none, kind/misc

#1041 [s2i tasks] - support env vars to be set during build time
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-dotnet/s2i-dotnet-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-go/s2i-go-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-java/s2i-java-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-nodejs/s2i-nodejs-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-perl/s2i-perl-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-php/s2i-php-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-python/s2i-python-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-ruby/s2i-ruby-task.yaml
Labels: approved, lgtm, release-note, ok-to-test, size/L

#1084 tektonconfig/{pipeline,trigger} should not take TektonConfig as args.
  pkg/reconciler/shared/tektonconfig/pipeline/pipeline.go
  pkg/reconciler/shared/tektonconfig/pipeline/pipeline_test.go
  pkg/reconciler/shared/tektonconfig/tektonconfig.go
  pkg/reconciler/shared/tektonconfig/trigger/trigger.go
  pkg/reconciler/shared/tektonconfig/trigger/trigger_test.go
  test/resources/rbac.go
Labels: approved, lgtm, release-note-none, size/L, kind/misc

#1090 removing printing of env-vars from S2i tasks
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-dotnet/s2i-dotnet-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-go/s2i-go-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-java/s2i-java-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-nodejs/s2i-nodejs-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-perl/s2i-perl-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-php/s2i-php-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-python/s2i-python-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-ruby/s2i-ruby-task.yaml
Labels: approved, lgtm, size/M, release-note

#1093 Install tektoncd/pipeline 0.37.5
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
  test/config.sh
Labels: approved, size/XS, lgtm, release-note

#1094 Fix the warnings for Pruner
  pkg/reconciler/common/prune.go
Labels: approved, lgtm, size/S, release-note

#1096 Add transformer to fix warnings for PSA
  pkg/reconciler/openshift/common/testdata/test-add-psa-expected.yaml
  pkg/reconciler/openshift/common/testdata/test-add-psa.yaml
  pkg/reconciler/openshift/common/transformer.go
  pkg/reconciler/openshift/common/transformer_test.go
  pkg/reconciler/openshift/tektonaddon/pipelinesascode.go
  pkg/reconciler/openshift/tektonchain/extension.go
  pkg/reconciler/openshift/tektonhub/extension.go
  pkg/reconciler/openshift/tektonpipeline/extension.go
  pkg/reconciler/openshift/tektontrigger/extension.go
Labels: approved, lgtm, release-note, size/L

#1097 Fix tkn serve cli pod PSA warning
  cmd/openshift/operator/kodata/tekton-addon/addons/05-tkncliserve/tkn_cli_serve.yaml
Labels: approved, size/XS, lgtm, release-note

#1080 Move platform defaulting to webhook and avoid api calls in reconciler
  config/openshift/base/webhook.yaml
  pkg/apis/operator/v1alpha1/common.go
  pkg/apis/operator/v1alpha1/tektontrigger_defaults.go
  pkg/reconciler/openshift/tektonconfig/extension.go
  pkg/reconciler/openshift/tektontrigger/extension.go
Labels: approved, lgtm, size/M, release-note

#1104 Add a releases.md file for the operator
  docs/release/README.md
  releases.md
Labels: approved, lgtm, size/M, release-note-none

#1081 🙃 Adds E2E Tests for Hub 🙃
  test/e2e/common/05_tektonhubdeployment_test.go
  test/e2e/common/testdata/db.yaml
  test/e2e/common/testdata/secret.yaml
  test/resources/tektonhub.go
  test/utils/clients.go
  test/utils/e2e_flags.go
  test/utils/names.go
Labels: approved, lgtm, release-note, size/L

#1109 skip fetching release if exist for hub and pac
  hack/fetch-releases.sh
Labels: approved, lgtm, size/M, release-note

#1116 Fix clean manifest
  Makefile
Labels: approved, size/XS, lgtm, release-note

#1118 Remove seccompprofile from deployments of operands
  cmd/openshift/operator/kodata/tekton-addon/addons/05-tkncliserve/tkn_cli_serve.yaml
  cmd/openshift/operator/kodata/webhook/webhook.yaml
  pkg/reconciler/common/prune.go
  pkg/reconciler/openshift/common/testdata/test-add-psa-expected.yaml
  pkg/reconciler/openshift/common/transformer.go
Labels: approved, lgtm, size/S, release-note

#1119 fixes s2i-java tasks: missing param
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-java/s2i-java-task.yaml
Labels: approved, size/XS, lgtm, release-note

#1111 Fix postgres:13 sha256 image with multi-arched image
  pkg/reconciler/openshift/tektonhub/testdata/update-db-deployment.yaml
  test/e2e/common/testdata/db.yaml
Labels: approved, size/XS, lgtm, release-note, ok-to-test

#1123 fix deletion of resource which is breaking the pod
  pkg/reconciler/kubernetes/tektoninstallerset/install.go
  pkg/reconciler/kubernetes/tektoninstallerset/tektoninstallerset.go
Labels: approved, lgtm, size/S, release-note
