Repository tektoncd/operator, pull requests merged in 2022-02, with the labels that each got.

#605 [OpenShift] Fix e2e test failure
  pkg/reconciler/openshift/tektonaddon/tektonaddon.go
Labels: approved, lgtm, size/S, release-note

#606 [OpenShift] Fix e2e tests
  pkg/reconciler/openshift/tektonaddon/tektonaddon.go
  test/e2e/common/tektonconfigdeployment_test.go
  test/e2e/openshift/tektonaddondeployment_test.go
Labels: approved, size/XS, lgtm, release-note

#608 [cherry-pick] Fix TektonPipeline Ready check
  pkg/reconciler/common/common.go
Labels: approved, lgtm, size/S, release-note-none

#612 Replace fmt.Sprintf() with labels.NewSelector() for building labelselectors
  pkg/reconciler/common/labels.go
  pkg/reconciler/common/labels_test.go
  pkg/reconciler/kubernetes/tektondashboard/tektondashboard.go
  pkg/reconciler/kubernetes/tektoninstallerset/query_test.go
  pkg/reconciler/kubernetes/tektonpipeline/tektonpipeline.go
  pkg/reconciler/kubernetes/tektontrigger/tektontrigger.go
  pkg/reconciler/openshift/tektonaddon/extension.go
  pkg/reconciler/openshift/tektonaddon/tektonaddon.go
  pkg/reconciler/openshift/tektonpipeline/extension.go
  test/e2e/common/tektonconfigdeployment_test.go
  test/resources/tektonaddons.go
Labels: approved, lgtm, release-note, size/L

#613 Improve Operator upgrade mechanism
  Makefile
  pkg/apis/operator/v1alpha1/const.go
  pkg/reconciler/common/common.go
  pkg/reconciler/common/initcontroller.go
  pkg/reconciler/kubernetes/tektondashboard/controller.go
  pkg/reconciler/kubernetes/tektondashboard/tektondashboard.go
  pkg/reconciler/kubernetes/tektoninstallerset/const.go
  pkg/reconciler/kubernetes/tektoninstallerset/install.go
  pkg/reconciler/kubernetes/tektoninstallerset/query.go
  pkg/reconciler/kubernetes/tektoninstallerset/query_test.go
  pkg/reconciler/kubernetes/tektonpipeline/controller.go
  pkg/reconciler/kubernetes/tektonpipeline/tektonpipeline.go
  pkg/reconciler/kubernetes/tektontrigger/controller.go
  pkg/reconciler/kubernetes/tektontrigger/tektontrigger.go
  pkg/reconciler/openshift/tektonaddon/controller.go
  pkg/reconciler/openshift/tektonaddon/extension.go
  pkg/reconciler/openshift/tektonaddon/tektonaddon.go
  pkg/reconciler/openshift/tektonconfig/common.go
  pkg/reconciler/openshift/tektonconfig/extension/addon.go
  pkg/reconciler/openshift/tektonconfig/rbac.go
  pkg/reconciler/openshift/tektonpipeline/extension.go
  pkg/reconciler/openshift/tektonpipeline/installerset.go
  pkg/reconciler/shared/tektonconfig/controller.go
  pkg/reconciler/shared/tektonconfig/pipeline/pipeline.go
  pkg/reconciler/shared/tektonconfig/tektonconfig.go
  pkg/reconciler/shared/tektonconfig/trigger/trigger.go
  test/e2e-common.sh
  test/e2e-tests.sh
  test/e2e/common/tektonconfigdeployment_test.go
  test/resources/tektonaddons.go
Labels: approved, lgtm, release-note, size/XL

#616 Fix flaky test behavior
  pkg/reconciler/common/labels_test.go
Labels: approved, size/XS, lgtm, release-note

#614 Update labels of tekton dashboard installersets
  pkg/reconciler/kubernetes/tektondashboard/tektondashboard.go
  test/e2e/kubernetes/tektondashboarddeployment_test.go
  test/resources/tektonaddons.go
  test/resources/tektondashboards.go
Labels: approved, lgtm, size/M, release-note

#618 Add PAC_VERSION to config.sh file
  test/config.sh
Labels: approved, size/XS, lgtm, release-note-none

#619 Update tektoncd/results to 0.4.0
  Makefile
  test/config.sh
Labels: approved, size/XS, lgtm, release-note

#620 Improve TekktonInstallerSet Reconciler
  pkg/reconciler/kubernetes/tektoninstallerset/install.go
  pkg/reconciler/kubernetes/tektoninstallerset/install_test.go
  pkg/reconciler/kubernetes/tektoninstallerset/tektoninstallerset.go
Labels: approved, lgtm, release-note, size/L

#621 [cherry-pick] 0.50.x Improve TekktonInstallerSet Reconciler
  pkg/reconciler/kubernetes/tektoninstallerset/install.go
  pkg/reconciler/kubernetes/tektoninstallerset/install_test.go
  pkg/reconciler/kubernetes/tektoninstallerset/tektoninstallerset.go
Labels: approved, lgtm, release-note, size/L

#617 [openshift] add maven clustertask
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/maven/maven-task.yaml
  pkg/reconciler/openshift/tektonaddon/tektonaddon.go
Labels: approved, lgtm, release-note, size/L

#631 Fixes operator pod restart on changing addon params
  pkg/reconciler/openshift/tektonaddon/tektonaddon.go
Labels: approved, lgtm, size/S, release-note

#600 Updates tektonPipeline to make it independent of tektonConfig
  pkg/reconciler/common/targetnamespace.go
  pkg/reconciler/common/targetnamespace_test.go
  pkg/reconciler/common/testdata/kodata/info/test-create-operator-version-config-map.yaml
  pkg/reconciler/kubernetes/tektonpipeline/tektonpipeline.go
  pkg/reconciler/shared/tektonconfig/tektonconfig.go
Labels: approved, lgtm, release-note, size/L

#632 [OpenShift] Refactors TektonAddon reconciler
  pkg/reconciler/openshift/tektonaddon/clustertTask.go
  pkg/reconciler/openshift/tektonaddon/clustertTaskVersioned.go
  pkg/reconciler/openshift/tektonaddon/installerset.go
  pkg/reconciler/openshift/tektonaddon/pipelinesascode.go
  pkg/reconciler/openshift/tektonaddon/pipelinetemplate.go
  pkg/reconciler/openshift/tektonaddon/tektonaddon.go
  pkg/reconciler/openshift/tektonaddon/triggers.go
Labels: approved, lgtm, release-note, size/XXL
