Repository tektoncd/operator, pull requests merged in 2022-07, with the labels that each got.

#875 update default value for PAC_VERSION
  tekton/task-fetch-components.yaml
Labels: approved, size/XS, lgtm, release-note

#877 Rename Rolebinding and Roles for metrics
  config/openshift/base/operator_servicemonitor.yaml
Labels: approved, size/XS, lgtm, release-note-none

#878 Rename Rolebinding and Roles for metrics
  config/openshift/base/operator_servicemonitor.yaml
Labels: approved, size/XS, lgtm, release-note-none

#886 Update pac version to 0.10.1
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
  test/config.sh
Labels: approved, size/XS, lgtm, release-note

#884 [release-v0.60.x] Update tkn download URLs, add arm64
  pkg/reconciler/openshift/tektonaddon/testdata/test-console-cli-expected.yaml
  pkg/reconciler/openshift/tektonaddon/transformer.go
Labels: approved, lgtm, size/M, release-note-none, ok-to-test

#889 [cherry pick] Bump tkn to 0.24.0 in ConsoleCLIDownload
  pkg/reconciler/openshift/tektonaddon/extension.go
Labels: approved, size/XS, lgtm, release-note-none

#890 [Cherry-pick] Fix chains secret getting overwritten on upgrade
  pkg/reconciler/kubernetes/tektonchain/tektonchain.go
Labels: approved, lgtm, release-note, size/L

#894 OpenShift: Update links in CSV
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
  pkg/reconciler/platform/config_internal_test.go
  pkg/reconciler/platform/config_test.go
  pkg/reconciler/platform/platform.go
  pkg/reconciler/platform/platform_internal_test.go
  pkg/reconciler/platform/types_test.go
Labels: approved, lgtm, size/M, release-note

#895 [Cherry-pick] OpenShift: Update links in CSV
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
  pkg/reconciler/platform/config_internal_test.go
  pkg/reconciler/platform/config_test.go
  pkg/reconciler/platform/platform.go
  pkg/reconciler/platform/platform_internal_test.go
  pkg/reconciler/platform/types_test.go
Labels: approved, lgtm, size/M, release-note

#888 Bump tkn to 0.24.0 in ConsoleCLIDownload
  pkg/reconciler/openshift/tektonaddon/extension.go
Labels: approved, size/XS, lgtm, release-note-none

#897 [v0.60.x] Bump tektoncd/pipeline to 0.37.2
  go.mod
  go.sum
  test/config.sh
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/openapi_generated.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/result_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/result_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/swagger.json
  vendor/modules.txt
Labels: approved, lgtm, size/S, release-note

#896 README.md: add missing releases
  README.md
Labels: approved, size/XS, lgtm, release-note-none

#909 Removes PropagationPolicy for resource deletion
  pkg/reconciler/kubernetes/tektoninstallerset/tektoninstallerset.go
Labels: approved, size/XS, lgtm, release-note

#911 [Cherry-pick] Removes PropagationPolicy for resource deletion
  pkg/reconciler/kubernetes/tektoninstallerset/tektoninstallerset.go
Labels: approved, size/XS, lgtm, release-note

#910 [Cherry-pick] Removes PropagationPolicy for resource deletion
  pkg/reconciler/kubernetes/tektoninstallerset/tektoninstallerset.go
Labels: approved, size/XS, lgtm, release-note

#912 Add job replacement tranform in tekton hub
  pkg/reconciler/kubernetes/tektonhub/tektonhub.go
Labels: approved, size/XS, lgtm, release-note

#914 [Cherry-pick] Add job replacement transform in tekton hub
  pkg/reconciler/kubernetes/tektonhub/tektonhub.go
Labels: size/XS, lgtm, release-note

#913 [Cherry-pick] Add job replacement transform in tekton hub
  pkg/reconciler/kubernetes/tektonhub/tektonhub.go
Labels: approved, size/XS, lgtm, release-note

#915 Dev: adds `make test lint` to run unit test and lint
  .github/pull_request_template.md
  Makefile
Labels: approved, lgtm, size/M, release-note

#928 Add a components.nightly.yaml for nightlies build
  components.nightly.yaml
Labels: approved, lgtm, size/S, release-note-none, kind/misc

#904 Combining the 3 steps of buildah task to use single step
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/buildah/buildah-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-dotnet/s2i-dotnet-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-go/s2i-go-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-java/s2i-java-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-nodejs/s2i-nodejs-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-perl/s2i-perl-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-php/s2i-php-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-python/s2i-python-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-ruby/s2i-ruby-task.yaml
Labels: approved, lgtm, release-note, size/L

#936 Adds missing MetricsDomain env for operator container
  config/kubernetes/base/operator.yaml
  config/openshift/base/operator.yaml
Labels: approved, size/XS, lgtm, release-note

#937 [Cherry-pick] Adds missing MetricsDomain env for operator container
  config/kubernetes/base/operator.yaml
  config/openshift/base/operator.yaml
Labels: approved, size/XS, lgtm, release-note

#941 [Cherry-pick] Increasing QPS limit to 50 to improve installation
  pkg/reconciler/platform/platform.go
Labels: approved, size/XS, lgtm, release-note

#940 Increasing QPS limit to 50 to improve installation
  pkg/reconciler/platform/platform.go
Labels: approved, size/XS, lgtm, release-note

#938 [Cherry-pick] Add env to replace the s2i-java env step
  config/openshift/base/operator.yaml
  operatorhub/openshift/config.yaml
Labels: approved, lgtm, size/S, release-note

#939 Add env to replace the s2i-java env step
  config/openshift/base/operator.yaml
  operatorhub/openshift/config.yaml
Labels: approved, lgtm, size/S, release-note

#942 [cherry-pick] Combining the 3 steps of buildah and all s2i task to use single step
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/buildah/buildah-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-dotnet/s2i-dotnet-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-go/s2i-go-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-java/s2i-java-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-nodejs/s2i-nodejs-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-perl/s2i-perl-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-php/s2i-php-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-python/s2i-python-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-ruby/s2i-ruby-task.yaml
Labels: approved, lgtm, release-note, size/L

#922 s2i ClusterTask: option to provide container registry credentials in a workspace
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-dotnet/s2i-dotnet-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-go/s2i-go-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-java/s2i-java-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-nodejs/s2i-nodejs-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-perl/s2i-perl-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-php/s2i-php-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-python/s2i-python-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-ruby/s2i-ruby-task.yaml
Labels: approved, lgtm, size/M, release-note, ok-to-test

#934 openshift: update all image references
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-dotnet/s2i-dotnet-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-go/s2i-go-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-java/s2i-java-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-nodejs/s2i-nodejs-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-perl/s2i-perl-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-php/s2i-php-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-python/s2i-python-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-ruby/s2i-ruby-task.yaml
  config/openshift/base/operator.yaml
  hack/openshift/update-image-sha.sh
  operatorhub/openshift/config.yaml
Labels: approved, lgtm, size/M, release-note-none, ok-to-test

#943 buildah ClusterTask: option to provide container registry credentials in a workspace
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/buildah/buildah-task.yaml
Labels: approved, size/XS, lgtm, release-note, ok-to-test

#944 [release-v0.60.x] openshift: update all image references
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-dotnet/s2i-dotnet-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-go/s2i-go-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-java/s2i-java-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-nodejs/s2i-nodejs-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-perl/s2i-perl-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-php/s2i-php-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-python/s2i-python-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-ruby/s2i-ruby-task.yaml
  config/openshift/base/operator.yaml
  hack/openshift/update-image-sha.sh
  operatorhub/openshift/config.yaml
Labels: approved, lgtm, size/M, release-note-none, ok-to-test

#885 Refactors Hub reconciler for easy upgrade and logic if user uses his database
  pkg/apis/operator/v1alpha1/const.go
  pkg/reconciler/kubernetes/tektonhub/installerset.go
  pkg/reconciler/kubernetes/tektonhub/tektonhub.go
Labels: approved, lgtm, release-note, size/L

#921 Updates the hub api secret by setting the AUTH_BASE_URL from Hub status
  pkg/reconciler/openshift/tektonhub/extension.go
Labels: approved, lgtm, size/S, release-note

#935 [Dev] Add makefile target to setup local dev with kind and docker
  Makefile
  hack/dev/kind/install.sh
  hack/dev/kind/kind.yaml
Labels: approved, lgtm, release-note, size/L

#945 [Cherry-pick] Refactors Hub reconciler for easy upgrade and logic if user uses his database
  pkg/apis/operator/v1alpha1/const.go
  pkg/reconciler/kubernetes/tektonhub/installerset.go
  pkg/reconciler/kubernetes/tektonhub/tektonhub.go
Labels: approved, lgtm, release-note, size/L

#947 Fix mark-for-deletion label format
  pkg/reconciler/shared/tektonconfig/tektonconfig.go
Labels: approved, size/XS, lgtm, release-note

#946 [Cherry-pick] Updates the hub api secret by setting the AUTH_BASE_URL from Hub status
  pkg/reconciler/openshift/tektonhub/extension.go
Labels: approved, lgtm, size/S, release-note

#948 Fix mark-for-deletion label format
  pkg/reconciler/shared/tektonconfig/tektonconfig.go
Labels: approved, size/XS, lgtm, release-note
