Repository tektoncd/operator, pull requests merged in 2022-11, with the labels that each got.

#1129 fix deletion of resource which is breaking the pod
  pkg/reconciler/kubernetes/tektoninstallerset/install.go
  pkg/reconciler/kubernetes/tektoninstallerset/install_test.go
  pkg/reconciler/kubernetes/tektoninstallerset/tektoninstallerset.go
Labels: approved, lgtm, size/M, release-note

#1134 Update plumbing to latest to fix CI
  go.mod
  go.sum
  vendor/github.com/tektoncd/plumbing/.gitignore
  vendor/github.com/tektoncd/plumbing/scripts/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S, release-note-none

#1130 Removes obsolete installer sets on upgrade
  pkg/reconciler/kubernetes/tektoninstallerset/client/obsolete_sets.go
  pkg/reconciler/kubernetes/tektonpipeline/reconcile.go
  pkg/reconciler/kubernetes/tektontrigger/reconcile.go
  third_party/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
  third_party/github.com/letsencrypt/boulder/core/proto/core.pb.go
  third_party/github.com/letsencrypt/boulder/sa/proto/sa.pb.go
  third_party/github.com/letsencrypt/boulder/sa/proto/sa_grpc.pb.go
Labels: approved, lgtm, size/M, release-note

#1125 [OpenShift] Creates OpenShiftPipelinesAsCode through TektonConfig
  pkg/apis/operator/v1alpha1/openshift_platform.go
  pkg/apis/operator/v1alpha1/tektonaddon_defaults.go
  pkg/apis/operator/v1alpha1/tektonaddon_types.go
  pkg/apis/operator/v1alpha1/tektonconfig_default_test.go
  pkg/apis/operator/v1alpha1/tektonconfig_defaults.go
  pkg/apis/operator/v1alpha1/tektonconfig_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/openshift/tektonconfig/extension.go
  pkg/reconciler/openshift/tektonconfig/extension/pipelinesascode.go
  pkg/reconciler/openshift/tektonconfig/extension/pipelinesascode_test.go
  third_party/github.com/tektoncd/operator/LICENSE
Labels: approved, lgtm, release-note, size/XL

#1140 [v0.62.x] Update plumbing to latest to fix CI
  go.mod
  go.sum
  vendor/github.com/tektoncd/plumbing/.gitignore
  vendor/github.com/tektoncd/plumbing/scripts/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/S, release-note-none, kind/misc

#1141 [v0.60.x] Update plumbing to latest to fix CI
  go.mod
  go.sum
  vendor/github.com/tektoncd/plumbing/.gitignore
  vendor/github.com/tektoncd/plumbing/adjustpermissions.py
  vendor/github.com/tektoncd/plumbing/scripts/e2e-tests.sh
  vendor/github.com/tektoncd/plumbing/scripts/library.sh
  vendor/modules.txt
Labels: approved, lgtm, size/M, release-note-none, kind/misc

#1139 Bump tkn to 0.24.1 in ConsoleCLIDownload
  pkg/reconciler/openshift/tektonaddon/extension.go
Labels: approved, size/XS, lgtm, release-note

#1149 Update pipeline-scc to not allow privilege escalation
  cmd/openshift/operator/kodata/openshift/00-prereconcile/openshift-pipelines-scc.yaml
Labels: approved, size/XS, lgtm, release-note

#1156 [OpenShift] move pipelines scc to rbac installer set
  pkg/reconciler/openshift/tektonconfig/common.go
  pkg/reconciler/openshift/tektonpipeline/extension.go
Labels: approved, lgtm, size/S, release-note

#1162 Refactors Tekton Dashboard reconciler to use tektoninstallerset client
  pkg/reconciler/common/nometrics.go
  pkg/reconciler/kubernetes/tektonconfig/extension/dashboard.go
  pkg/reconciler/kubernetes/tektonconfig/extension/dashboard_test.go
  pkg/reconciler/kubernetes/tektondashboard/controller.go
  pkg/reconciler/kubernetes/tektondashboard/finalize.go
  pkg/reconciler/kubernetes/tektondashboard/reconcile.go
  pkg/reconciler/kubernetes/tektondashboard/tektondashboard.go
  pkg/reconciler/kubernetes/tektondashboard/transform.go
  pkg/reconciler/openshift/openshiftpipelinesascode/controller.go
Labels: approved, lgtm, release-note, size/XL

#1166 Add Operator Icon to the readme
  README.md
  tekton-operator.png
Labels: approved, size/XS, lgtm, release-note

#1171 Provides option to configure external logs for dashboard
  docs/TektonDashboard.md
  pkg/apis/operator/v1alpha1/tektondashboard_types.go
  pkg/reconciler/common/testdata/test-dashboard-deployment.yaml
  pkg/reconciler/common/transformers.go
  pkg/reconciler/common/transformers_test.go
  pkg/reconciler/kubernetes/tektonconfig/extension/dashboard.go
  pkg/reconciler/kubernetes/tektondashboard/finalize.go
  pkg/reconciler/kubernetes/tektondashboard/transform.go
Labels: approved, lgtm, release-note, size/L

#1172 Remove Tekton Dashboard obselete installerset on upgrade
  pkg/reconciler/kubernetes/tektondashboard/reconcile.go
  pkg/reconciler/kubernetes/tektoninstallerset/client/obsolete_sets.go
Labels: approved, lgtm, size/S, release-note

#1176 [Cherrypick] [1.8.3] [OpenShift] move pipelines scc to rbac installer set
  pkg/reconciler/openshift/tektonconfig/common.go
  pkg/reconciler/openshift/tektonpipeline/extension.go
Labels: approved, lgtm, size/S, release-note

#1180 Fix some little thing in e2e scripts.
  test/e2e-common.sh
  test/e2e-tests.sh
Labels: approved, lgtm, size/S, release-note-none

#1177 Make devconsole resources install based on availability
  go.mod
  go.sum
  pkg/reconciler/openshift/tektonaddon/controller.go
  pkg/reconciler/openshift/tektonaddon/openshiftConsole.go
  pkg/reconciler/openshift/tektonaddon/tektonaddon.go
  third_party/github.com/LICENSE
  third_party/github.com/hashicorp/golang-lru/simplelru/lru_interface.go
  third_party/github.com/letsencrypt/boulder/core/proto/core.pb.go
  third_party/github.com/letsencrypt/boulder/sa/proto/sa.pb.go
  third_party/github.com/letsencrypt/boulder/sa/proto/sa_grpc.pb.go
  third_party/k8s.io/apiextensions-apiserver/pkg/LICENSE
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/.import-restrictions
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.pb.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/generated.proto
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/marshal.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/types_jsonschema.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.conversion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.deepcopy.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.defaults.go
  vendor/k8s.io/apiextensions-apiserver/pkg/apis/apiextensions/v1beta1/zz_generated.prerelease-lifecycle.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/clientset.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/scheme/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/generated_expansion.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/generated_expansion.go
  vendor/modules.txt
Labels: approved, lgtm, release-note, size/XXL

#1186 Fix apiversion for devconsole CRDs
  pkg/reconciler/openshift/tektonaddon/openshiftConsole.go
Labels: approved, size/XS, lgtm, release-note

#1184 e2e: use kind to run tests on the CI
  test/e2e-tests-kind-prow.env
Labels: approved, size/XS, lgtm, release-note-none, kind/misc

#1188 Bump pac and cli versions
  components.yaml
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
  pkg/reconciler/openshift/tektonaddon/consolecli.go
Labels: approved, size/XS, lgtm, release-note

#1192 Update README and releases docs.
  README.md
  docs/install.md
  releases.md
  tekton/release-cheat-sheet.md
Labels: approved, lgtm, release-note-none, size/L

#1194 Adds `resource-verification-mode` and `enable-provenance-in-status` fields for Pipelines
  pkg/apis/operator/v1alpha1/tektonpipeline_defaults.go
  pkg/apis/operator/v1alpha1/tektonpipeline_defaults_test.go
  pkg/apis/operator/v1alpha1/tektonpipeline_types.go
  pkg/apis/operator/v1alpha1/tektonpipeline_validation.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/S, release-note
