Repository tektoncd/operator, pull requests merged in 2022-04, with the labels that each got.

#738 [cherr-pick] Fix ConsoleQuickStart description
  cmd/openshift/operator/kodata/tekton-addon/optional/quickstarts/install-associate-pipeline-quickstart.yaml
Labels: approved, size/XS, lgtm, release-note-none

#737 Fix ConsoleQuickStart description
  cmd/openshift/operator/kodata/tekton-addon/optional/quickstarts/install-associate-pipeline-quickstart.yaml
Labels: approved, size/XS, lgtm, release-note-none

#741 Update tkn, pac ConsoleCLIDownload links to 0.23.1
  cmd/openshift/operator/kodata/tekton-addon/addons/04-consolecli/console_cli_download_tkn.yaml
  pkg/reconciler/openshift/tektonaddon/extension.go
  pkg/reconciler/openshift/tektonaddon/testdata/test-console-cli-expected.yaml
  pkg/reconciler/openshift/tektonaddon/transformer.go
  pkg/reconciler/openshift/tektonaddon/transformer_test.go
Labels: approved, lgtm, release-note-none, size/L

#742 [cherry-pick] Update tkn, pac ConsoleCLIDownload links to 0.23.1
  cmd/openshift/operator/kodata/tekton-addon/addons/04-consolecli/console_cli_download_tkn.yaml
  pkg/reconciler/openshift/tektonaddon/extension.go
  pkg/reconciler/openshift/tektonaddon/testdata/test-console-cli-expected.yaml
  pkg/reconciler/openshift/tektonaddon/transformer.go
  pkg/reconciler/openshift/tektonaddon/transformer_test.go
Labels: approved, lgtm, release-note-none, size/L

#743 Add concaf to approvers
  OWNERS
Labels: approved, size/XS, lgtm, release-note-none

#744 Update pac to v0.5.7
  Makefile
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
  tekton/operator-release-pipeline.yaml
  tekton/task-fetch-components.yaml
  test/config.sh
Labels: approved, lgtm, size/S, release-note

#678 Update release pipelines
  tekton/operator-release-pipeline.yaml
  tekton/task-fetch-components.yaml
Labels: approved, lgtm, size/S, release-note

#745 [openshift] Fix upgrade: Tektonconfig staying in Ready: False
  pkg/reconciler/openshift/tektonconfig/common.go
  pkg/reconciler/openshift/tektonconfig/rbac.go
Labels: approved, lgtm, size/M, release-note

#746 [cherry-pick] [openshift] Fix upgrade: Tektonconfig staying in Ready: False
  pkg/reconciler/openshift/tektonconfig/common.go
  pkg/reconciler/openshift/tektonconfig/rbac.go
Labels: approved, lgtm, size/M

#740 Update fetch script to use stable tag for pac by default
  Makefile
  hack/fetch-releases.sh
  pkg/reconciler/common/certificates.go
  pkg/reconciler/common/certificates_test.go
  pkg/reconciler/kubernetes/tektondashboard/tektondashboard.go
  pkg/reconciler/kubernetes/tektoninstallerset/tektoninstallerset.go
  pkg/reconciler/kubernetes/tektonpipeline/tektonpipeline.go
  pkg/reconciler/kubernetes/tektontrigger/tektontrigger.go
  pkg/reconciler/openshift/common/cabundle_test.go
  pkg/reconciler/openshift/tektonaddon/tektonaddon.go
  pkg/reconciler/openshift/tektonaddon/transformer.go
  pkg/reconciler/openshift/tektonaddon/transformer_test.go
  pkg/reconciler/openshift/tektonconfig/common.go
  pkg/reconciler/proxy/proxy.go
  pkg/reconciler/shared/tektonconfig/tektonconfig.go
  pkg/webhook/webhook_init_test.go
  test/config.sh
  test/e2e/common/00_tektonconfigdeployment_test.go
  test/e2e/common/01_tektonpipelinedeployment_test.go
  test/e2e/common/02_tektontriggerdeployment_test.go
  test/e2e/kubernetes/tektondashboarddeployment_test.go
  test/e2e/kubernetes/tektonresultdeployment_test.go
  test/e2e/openshift/tektonaddondeployment_test.go
Labels: approved, lgtm, size/M, release-note

#747 Updates Hub version to v1.7.2 and minor fixes in TektonHub docs
  Makefile
  docs/TektonHub.md
  test/config.sh
Labels: approved, lgtm, size/S, release-note

#750 [Cherry-pick] Updates Hub version to v1.7.2 and minor fixes in TektonHub docs
  Makefile
  docs/TektonHub.md
  test/config.sh
Labels: approved, lgtm, size/M, release-note

#682 Refactor TektonResults to use TektonInstallerSets
  pkg/apis/operator/v1alpha1/tektonresult_lifecycle.go
  pkg/apis/operator/v1alpha1/tektonresult_lifecycle_test.go
  pkg/apis/operator/v1alpha1/tektonresult_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/kubernetes/tektoninstallerset/install.go
  pkg/reconciler/kubernetes/tektonresult/controller.go
  pkg/reconciler/kubernetes/tektonresult/installerset.go
  pkg/reconciler/kubernetes/tektonresult/tektonresult.go
Labels: approved, lgtm, release-note, size/L

#753 Update PAC to v0.5.9
  Makefile
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
  tekton/operator-release-pipeline.yaml
  tekton/task-fetch-components.yaml
  test/config.sh
Labels: approved, lgtm, size/S, release-note

#757 Update pac to v0.5.10
  Makefile
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
  tekton/operator-release-pipeline.yaml
  tekton/task-fetch-components.yaml
  test/config.sh
Labels: approved, lgtm, size/S, release-note

#758 Add arm64 to supported architectures
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
Labels: approved, size/XS, lgtm, release-note

#760 Update version for Chains, Results and Hub
  tekton/operator-release-pipeline.yaml
Labels: approved, size/XS, lgtm, release-note

#754 Modify TektonAddon and TektonDashboard to avoid using polling
  pkg/reconciler/kubernetes/tektonconfig/extension.go
  pkg/reconciler/kubernetes/tektonconfig/extension/dashboard.go
  pkg/reconciler/kubernetes/tektonconfig/extension/dashboard_test.go
  pkg/reconciler/kubernetes/tektondashboard/tektondashboard.go
  pkg/reconciler/openshift/tektonconfig/extension.go
  pkg/reconciler/openshift/tektonconfig/extension/addon.go
  pkg/reconciler/openshift/tektonconfig/extension/addon_test.go
Labels: approved, lgtm, release-note, size/L
