Repository tektoncd/operator, pull requests merged in 2023-02, with the labels that each got.

#1301 Revert https://github.com/tektoncd/operator/pull/1271
  pkg/reconciler/openshift/openshiftpipelinesascode/extension.go
Labels: approved, lgtm, size/S, release-note

#1305 Make the webhook accepts pod from pac
  pkg/reconciler/proxy/proxy.go
Labels: approved, size/XS, lgtm, release-note

#1314 Bumps Pac and Hub Version in CSV
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
Labels: approved, size/XS, lgtm, release-note

#1313 add development environment support to podman runtime
  DEVELOPMENT.md
  Makefile
  hack/dev/kind/install.sh
  hack/dev/kind/kind.yaml
Labels: approved, lgtm, release-note, ok-to-test, size/L

#1326 clean leftover pruner cron jobs
  pkg/reconciler/common/prune.go
Labels: approved, lgtm, size/S, release-note-none, ok-to-test

#1331 Remove kubeconfigwriter reference from the CSV
  operatorhub/openshift/config.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
Labels: approved, lgtm, size/S, release-note-none

#1294 Adds support of custom logo in the Tekton Hub
  pkg/apis/operator/v1alpha1/tektonhub_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/kubernetes/tektonhub/tektonhub.go
Labels: approved, lgtm, size/M, release-note

#1337 Fix the Development guide link in Readme
  README.md
Labels: approved, size/XS, lgtm, release-note-none, kind/misc

#1341 removing max openshift version from adding it to CSV due to the scor…
  operatorhub/openshift/release-artifacts/bundle/metadata/properties.yaml
  operatorhub/tools/bundle.py
Labels: approved, size/XS, lgtm, release-note

#1345 fix build test failures, happens after plumbing pr-1369
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/reconciler/common/proxy.go
  pkg/reconciler/common/proxy_test.go
  pkg/reconciler/kubernetes/tektonhub/tektonhub.go
  pkg/reconciler/openshift/tektonaddon/transformer.go
  third_party/github.com/fsnotify/fsnotify/LICENSE
  third_party/github.com/go-jose/go-jose/v3/LICENSE
  third_party/github.com/go-jose/go-jose/v3/json/LICENSE
  third_party/github.com/hashicorp/go-retryablehttp/README.md
  third_party/github.com/hashicorp/go-retryablehttp/client.go
  third_party/github.com/letsencrypt/boulder/core/objects.go
  third_party/github.com/letsencrypt/boulder/core/util.go
  third_party/github.com/letsencrypt/boulder/errors/errors.go
  third_party/github.com/letsencrypt/boulder/features/featureflag_string.go
  third_party/github.com/letsencrypt/boulder/features/features.go
  third_party/github.com/letsencrypt/boulder/sa/proto/sa.pb.go
  third_party/github.com/letsencrypt/boulder/sa/proto/sa.proto
  third_party/github.com/letsencrypt/boulder/sa/proto/sa_grpc.pb.go
Labels: approved, lgtm, size/XXL, release-note-none
