Repository tektoncd/operator, pull requests merged in 2023-08, with the labels that each got.

#1629 Bump git-init image sha to 1.10.5
  operatorhub/openshift/config.yaml
Labels: approved, size/XS, lgtm, release-note

#1637 Changing Shell Image from UBI-minimal to shell image
  operatorhub/openshift/config.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
Labels: kind/bug, approved, size/XS, lgtm, release-note

#1636 support TEKTON_HUB_API and ARTIFACT_HUB_API environment in tekton-pipelines-remote-resolvers controller
  docs/TektonConfig.md
  pkg/reconciler/kubernetes/tektonpipeline/transform.go
  pkg/reconciler/kubernetes/tektonpipeline/transform_test.go
Labels: approved, lgtm, release-note, size/L

#1639 Update version in the CSV
  components.yaml
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
Labels: approved, size/XS, lgtm, release-note

#1641 Fixes the namespaces while getting chains-config configmap and order of installerset creation in chains
  pkg/reconciler/kubernetes/tektonchain/tektonchain.go
  pkg/reconciler/shared/tektonconfig/tektonconfig.go
Labels: approved, lgtm, release-note, size/L

#1660 Bump golangcilint to v0.54.2
  Makefile
Labels: approved, size/XS, lgtm, release-note

#1661 Bump components and clustertasks for v0.68.0 release
  components.yaml
  hack/openshift/fetch-tektoncd-catalog-tasks.sh
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
Labels: approved, lgtm, size/S, release-note

#1669 exclude deployments replicas from hash compute
  pkg/reconciler/kubernetes/tektoninstallerset/install.go
Labels: approved, size/XS, lgtm, release-note-none
