Repository tektoncd/operator, pull requests merged in 2023-04, with the labels that each got.

#1433 [release-v0.63.x] fix build test failures, happens after plumbing pr-1369
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/reconciler/common/proxy.go
  pkg/reconciler/common/proxy_test.go
  pkg/reconciler/kubernetes/tektonhub/tektonhub.go
  pkg/reconciler/openshift/tektonaddon/transformer.go
Labels: approved, lgtm, size/M, release-note-none

#1434 Change the value on upgrade for embedded status
  pkg/reconciler/shared/tektonconfig/tektonconfig.go
Labels: approved, lgtm, size/S, release-note

#1278 Fix RBAC
  chart/templates/rbac.yaml
Labels: approved, lgtm, size/S, release-note, ok-to-test

#1395 Adds recently added storage and signers related artifacts to Chains Spec
  pkg/apis/operator/v1alpha1/tektonchain_types.go
  pkg/apis/operator/v1alpha1/tektonchain_validation.go
  pkg/apis/operator/v1alpha1/tektonchain_validation_test.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, release-note, size/L

#1448 Removes pull-request init and imagedigestexporter
  operatorhub/openshift/config.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
Labels: approved, lgtm, size/S, release-note

#1336 fix: helm chart fail when set Values.operator.operatorName
  chart/templates/deployment.yaml
Labels: approved, size/XS, lgtm, release-note-none, ok-to-test

#1388 Update RBAC in Helm chart to match Kustomize manifests
  chart/templates/rbac.yaml
Labels: approved, lgtm, release-note, size/XL, ok-to-test

#1329 fix proxy update reconcile issue
  pkg/reconciler/kubernetes/tektonchain/tektonchain.go
  pkg/reconciler/kubernetes/tektondashboard/transform.go
  pkg/reconciler/kubernetes/tektoninstallerset/install.go
  pkg/reconciler/kubernetes/tektonpipeline/transform.go
  pkg/reconciler/kubernetes/tektonresult/tektonresult.go
  pkg/reconciler/kubernetes/tektontrigger/transform.go
  pkg/reconciler/openshift/openshiftpipelinesascode/transform.go
Labels: approved, lgtm, size/M, release-note-none

#1455 fix deployment reconcile issue
  pkg/reconciler/kubernetes/tektoninstallerset/install.go
Labels: approved, lgtm, size/S, release-note-none

#1322 redesigned the pruner reconciler to fix multiple issue
  config/base/role.yaml
  config/pruner/00-pruner.yaml
  docs/TektonConfig.md
  go.mod
  hack/fetch-releases.sh
  pkg/apis/operator/v1alpha1/const.go
  pkg/apis/operator/v1alpha1/tektonconfig_types.go
  pkg/reconciler/common/prune.go
  pkg/reconciler/common/prune_test.go
  pkg/reconciler/common/releases.go
  pkg/reconciler/common/testdata/test-replace-namespace-in-cluster-role-binding.yaml
  pkg/reconciler/common/testdata/test-replace-namespace-in-service-account.yaml
  pkg/reconciler/common/transformers.go
  pkg/reconciler/common/transformers_test.go
  pkg/reconciler/openshift/tektonconfig/extension.go
  pkg/reconciler/shared/hash/hash.go
  pkg/reconciler/shared/tektonconfig/installerset_pruner.go
  pkg/reconciler/shared/tektonconfig/tektonconfig.go
  vendor/github.com/pmezard/go-difflib/LICENSE
  vendor/github.com/pmezard/go-difflib/difflib/difflib.go
  vendor/github.com/stretchr/testify/LICENSE
  vendor/github.com/stretchr/testify/assert/assertion_compare.go
  vendor/github.com/stretchr/testify/assert/assertion_compare_can_convert.go
  vendor/github.com/stretchr/testify/assert/assertion_compare_legacy.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go
  vendor/github.com/stretchr/testify/assert/assertion_format.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_forward.go
  vendor/github.com/stretchr/testify/assert/assertion_forward.go.tmpl
  vendor/github.com/stretchr/testify/assert/assertion_order.go
  vendor/github.com/stretchr/testify/assert/assertions.go
  vendor/github.com/stretchr/testify/assert/doc.go
  vendor/github.com/stretchr/testify/assert/errors.go
  vendor/github.com/stretchr/testify/assert/forward_assertions.go
  vendor/github.com/stretchr/testify/assert/http_assertions.go
  vendor/golang.org/x/mod/sumdb/dirhash/hash.go
  vendor/modules.txt
Labels: approved, lgtm, release-note, size/XXL, ok-to-test
