Repository tektoncd/operator, pull requests merged in 2023-01, with the labels that each got.

#1237 Bump payloads (pipeline -> 0.42) and fix rbac.
  components.yaml
  config/base/role.yaml
Labels: approved, size/XS, lgtm, release-note

#1234 Adds script for release branch creation and replace version labels
  hack/release-setup-branch.sh
  hack/release.sh
Labels: approved, lgtm, release-note, size/L

#1241 Set hack/release-setup-branch.sh as executable
  hack/release-setup-branch.sh
Labels: approved, size/XS, lgtm, release-note-none

#1242 .github/workflows: fix the set-matrix job
  .github/workflows/bump-payload-on-releases.yaml
Labels: approved, size/XS, lgtm, release-note-none

#1244 Bump pipeline payload to 0.43.0
  components.yaml
  config/base/role.yaml
Labels: approved, size/XS, lgtm, release-note-none

#1249 Bump pac to v0.15.1 and update versions in CSV for PAC and chains
  go.mod
  go.sum
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
  vendor/github.com/openshift-pipelines/pipelines-as-code/pkg/params/settings/config.go
  vendor/github.com/openshift-pipelines/pipelines-as-code/pkg/params/settings/default.go
  vendor/modules.txt
Labels: approved, lgtm, size/M, release-note

#1257 Bump chart version to 0.64.0
  chart/Chart.yaml
  chart/templates/kubernetes-crds.yaml
  chart/templates/openshift-crds.yaml
Labels: approved, lgtm, size/M, release-note, ok-to-test

#1265 Bump Hub version to v1.11.2 in CSV
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
Labels: approved, size/XS, lgtm, release-note

#1268 Bump pac to v0.15.2 and update version in CSV
  go.mod
  go.sum
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
  vendor/modules.txt
Labels: approved, lgtm, size/S, release-note

#1254 Update git-clone task to 0.9
  hack/openshift/fetch-tektoncd-catalog-tasks.sh
Labels: approved, size/XS, lgtm, release-note, ok-to-test

#1270 Adds docs for resolvers
  docs/TektonConfig.md
Labels: approved, lgtm, size/M, release-note

#1295 Bump dashboard to 0.32.0 and fix release url
  components.yaml
  hack/fetch-releases.sh
Labels: approved, lgtm, size/S, release-note
