Repository tektoncd/operator, pull requests merged in 2023-05, with the labels that each got.

#1454 Configures the installation of TektonChain through TektonConfig
  pkg/apis/operator/v1alpha1/tektonconfig_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/kubernetes/tektondashboard/reconcile.go
  pkg/reconciler/kubernetes/tektonpipeline/reconcile.go
  pkg/reconciler/openshift/tektonpipeline/extension.go
  pkg/reconciler/shared/tektonconfig/chain/chain.go
  pkg/reconciler/shared/tektonconfig/chain/chain_test.go
  pkg/reconciler/shared/tektonconfig/controller.go
  pkg/reconciler/shared/tektonconfig/tektonconfig.go
Labels: approved, lgtm, release-note, size/L

#1458 add support to pipelines controller's performance flags
  docs/TektonConfig.md
  docs/TektonPipeline.md
  pkg/apis/operator/v1alpha1/tektonpipeline_types.go
  pkg/apis/operator/v1alpha1/tektonpipeline_validation.go
  pkg/apis/operator/v1alpha1/tektonpipeline_validation_test.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/common/utils.go
  pkg/reconciler/common/utils_test.go
  pkg/reconciler/kubernetes/tektonpipeline/transform.go
  pkg/reconciler/kubernetes/tektonpipeline/transform_test.go
  pkg/reconciler/shared/tektonconfig/pipeline/pipeline.go
Labels: approved, lgtm, release-note, size/XL

#1466 Update TektonChain docs
  docs/TektonChain.md
  docs/TektonConfig.md
Labels: approved, lgtm, size/S, release-note

#1470 allow beta in pipeline validation in enable-api-fields
  pkg/apis/operator/v1alpha1/tektonpipeline_validation.go
  pkg/apis/operator/v1alpha1/tektonpipeline_validation_test.go
Labels: approved, lgtm, size/M, release-note-none

#1464 Handles type for Transparency field in TektonChain spec
  pkg/apis/operator/v1alpha1/tektonchain_types.go
  pkg/apis/operator/v1alpha1/tektonchain_validation.go
Labels: approved, lgtm, size/M, release-note

#1465 allow to disable global pruner job and completely disable pruner feature
  docs/TektonConfig.md
  pkg/apis/operator/v1alpha1/const.go
  pkg/apis/operator/v1alpha1/tektonconfig_defaults.go
  pkg/apis/operator/v1alpha1/tektonconfig_types.go
  pkg/apis/operator/v1alpha1/tektonconfig_validation.go
  pkg/apis/operator/v1alpha1/tektonconfig_validation_test.go
  pkg/apis/operator/v1alpha1/tektonhub_validation_test.go
  pkg/reconciler/common/prune.go
  pkg/reconciler/common/prune_test.go
  pkg/reconciler/shared/tektonconfig/instance.go
  pkg/reconciler/shared/tektonconfig/tektonconfig.go
Labels: approved, lgtm, release-note, size/L

#1099 Add CodeQL analysis to the operator
  .github/workflows/codeql-analysis.yml
Labels: approved, lgtm, size/M, release-note-none

#1485 fix incorrect conversion between integer types
  pkg/reconciler/common/prune.go
Labels: approved, size/XS, lgtm, release-note-none

#1486 Update versions to latest
  components.yaml
  config/kubernetes/base/operator.yaml
  config/openshift/base/operator.yaml
  go.mod
  go.sum
  operatorhub/kubernetes/config.yaml
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
  pkg/reconciler/openshift/tektonaddon/consolecli.go
  vendor/github.com/tektoncd/triggers/pkg/apis/config/allowed_types.go
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1beta1/cluster_trigger_binding_defaults.go
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1beta1/event_listener_validation.go
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1beta1/openapi_generated.go
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1beta1/swagger.json
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1beta1/trigger_binding_defaults.go
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1beta1/trigger_binding_validation.go
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1beta1/trigger_template_defaults.go
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1beta1/trigger_template_validation.go
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1beta1/trigger_types.go
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1beta1/trigger_validation.go
  vendor/github.com/tektoncd/triggers/pkg/apis/triggers/v1beta1/zz_generated.deepcopy.go
  vendor/modules.txt
Labels: approved, lgtm, release-note, size/XL

#1442 Fix/update e2e tests to support OpenShift environment
  .gitignore
  pkg/apis/operator/v1alpha1/tektonhub_defaults.go
  pkg/apis/operator/v1alpha1/tektonhub_lifecycle.go
  pkg/apis/operator/v1alpha1/tektonhub_lifecycle_test.go
  pkg/apis/operator/v1alpha1/tektonhub_types.go
  pkg/apis/operator/v1alpha1/tektonhub_validation.go
  pkg/apis/operator/v1alpha1/tektonhub_validation_test.go
  pkg/reconciler/kubernetes/tektonhub/tektonhub.go
  pkg/reconciler/kubernetes/tektoninstallerset/controller.go
  test/e2e/common/00_tektonconfigdeployment_test.go
  test/e2e/common/04_tektonchainsgettingstartedtutorial_test.go
  test/e2e/common/05_tektonhubdeployment_test.go
  test/e2e/common/testdata/chain_tutorial_task_output_image.yaml
  test/e2e/common/testdata/hub_externaldb.yaml
  test/e2e/common/testdata/hub_externaldb_secret.yaml
  test/resources/debug_commands.go
  test/resources/deployment.go
  test/resources/job.go
  test/resources/namespace.go
  test/resources/pod.go
  test/resources/rbac.go
  test/resources/tektonchains.go
  test/resources/tektonconfigs.go
  test/resources/tektonhub.go
  test/utils/config.go
  test/utils/env.go
  test/utils/logger.go
  test/utils/names.go
  vendor/github.com/stretchr/testify/require/doc.go
  vendor/github.com/stretchr/testify/require/forward_requirements.go
  vendor/github.com/stretchr/testify/require/require.go
  vendor/github.com/stretchr/testify/require/require.go.tmpl
  vendor/github.com/stretchr/testify/require/require_forward.go
  vendor/github.com/stretchr/testify/require/require_forward.go.tmpl
  vendor/github.com/stretchr/testify/require/requirements.go
  vendor/github.com/stretchr/testify/suite/doc.go
  vendor/github.com/stretchr/testify/suite/interfaces.go
  vendor/github.com/stretchr/testify/suite/stats.go
  vendor/github.com/stretchr/testify/suite/suite.go
  vendor/knative.dev/pkg/client/injection/kube/informers/core/v1/serviceaccount/serviceaccount.go
  vendor/knative.dev/pkg/client/injection/kube/informers/rbac/v1/clusterrole/clusterrole.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL, release-note-none

#1491 Update results to v0.6.0
  components.yaml
Labels: approved, size/XS, lgtm, release-note-none, kind/misc

#1480 Add doc changes for PipelinesAsCode
  docs/OpenShiftPipelinesAsCode.md
  docs/README.md
  docs/TektonAddon.md
  docs/TektonConfig.md
  docs/install.md
Labels: approved, lgtm, release-note, size/L

#1495 Fix the image in config for CSV generation
  operatorhub/openshift/config.yaml
Labels: approved, size/XS, lgtm, release-note-none, kind/misc

#1508 update pruner documentation
  docs/TektonConfig.md
Labels: approved, lgtm, size/S, release-note-none

#1512 Bump pac to v0.19.1
  components.yaml
  go.mod
  go.sum
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
  vendor/modules.txt
Labels: approved, lgtm, size/S, release-note

#1513 Bump pac to v0.19.1
  components.yaml
  go.mod
  go.sum
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
  vendor/modules.txt
Labels: approved, lgtm, size/S, release-note

#1519 Update Chains and Add Results to CSV
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
Labels: approved, size/XS, lgtm, release-note-none, kind/misc

#1523 Docs: update roadmap file name in README.md
  README.md
Labels: approved, size/XS, lgtm, release-note, ok-to-test
