Repository tektoncd/operator, pull requests merged in 2023-10, with the labels that each got.

#1758 Add list nodes rule for kubernetes-rbac
  chart/templates/kubernetes-rbac.yaml
Labels: approved, size/XS, lgtm, release-note, ok-to-test

#1738 enable chains testcases on s390x
  test/e2e/common/03_tektonchaindeployment_test.go
  test/e2e/common/04_tektonchainsgettingstartedtutorial_test.go
Labels: approved, size/XS, lgtm, release-note-none

#1762 make pruner image configurable and allow for custom labels for operator deployment
  chart/templates/_helpers.tpl
  chart/templates/deployment.yaml
  chart/values.yaml
Labels: approved, lgtm, size/M, release-note, ok-to-test

#1767 Makefile: fix bump-bugfix target
  Makefile
Labels: approved, size/XS, lgtm, release-note-none

#1790 sync with operand versions
  components.yaml
  go.mod
  go.sum
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
  pkg/reconciler/openshift/tektonaddon/consolecli.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/constant.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1/pipelinerun_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1/taskrun_validation.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/server.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: approved, lgtm, release-note-none, size/L

#1795 Bump tektoncd/hub to v1.13.2
  components.yaml
Labels: approved, size/XS, lgtm, release-note-none

#1800 [v0.68.x] sync pipeline task images sha - openshift - sync number 2
  config/openshift/base/operator.yaml
  operatorhub/openshift/config.yaml
Labels: approved, lgtm, size/S, release-note-none

#1804 [v0.68.x] update tkn and helm version
  .github/workflows/helm-release.yaml
  chart/Chart.yaml
  chart/templates/deployment.yaml
  config/kubernetes/base/operator.yaml
  config/openshift/base/operator.yaml
  operatorhub/kubernetes/config.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/tektoncd-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/S, release-note-none

#1805 execute GH action release of helm chart only on new tag
  .github/workflows/helm-release.yaml
Labels: approved, size/XS, lgtm, release-note-none

#1806 [v0.67.x] sync clustertask images sha and bump cli version
  config/openshift/base/operator.yaml
  operatorhub/openshift/config.yaml
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
  pkg/reconciler/openshift/tektonaddon/consolecli.go
Labels: approved, lgtm, size/S, release-note-none

#1807 [v0.65.x] sync operand versions and clustertask images
  config/openshift/base/operator.yaml
  operatorhub/openshift/config.yaml
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
  pkg/reconciler/openshift/tektonaddon/consolecli.go
Labels: approved, lgtm, size/M, release-note-none

#1809 [v0.68.x] prepare for 0.68.1 patch release
  chart/templates/kubernetes-crds.yaml
  chart/templates/openshift-crds.yaml
  cmd/kubernetes/operator/kodata/webhook/webhook.yaml
  cmd/openshift/operator/kodata/webhook/webhook.yaml
  config/base/300-operator_v1alpha1_chain_crd.yaml
  config/base/300-operator_v1alpha1_config_crd.yaml
  config/base/300-operator_v1alpha1_hub_crd.yaml
  config/base/300-operator_v1alpha1_installer_set_crd.yaml
  config/base/300-operator_v1alpha1_pipeline_crd.yaml
  config/base/300-operator_v1alpha1_result_crd.yaml
  config/base/300-operator_v1alpha1_trigger_crd.yaml
  config/base/config-info.yaml
  config/base/operator.yaml
  config/kubernetes/base/300-operator_v1alpha1_dashboard_crd.yaml
  config/kubernetes/base/operator.yaml
  config/kubernetes/base/operator_service.yaml
  config/kubernetes/base/webhook.yaml
  config/openshift/base/300-operator_v1alpha1_addon_crd.yaml
  config/openshift/base/300-operator_v1alpha1_openshiftpipelinesascode_crd.yaml
  config/openshift/base/operator.yaml
  config/openshift/base/operator_service.yaml
  config/openshift/base/webhook.yaml
  config/webhooks/webhook-service.yaml
  config/webhooks/webhook.yaml
Labels: approved, lgtm, release-note-none, size/L

#1810 [v0.67.x]update sha of images
  config/openshift/base/operator.yaml
  operatorhub/openshift/config.yaml
Labels: approved, size/XS, lgtm, release-note-none

#1816 [v0.67.x] update clustertask source-to-image-rhel8 path and sha
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-dotnet/s2i-dotnet-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-go/s2i-go-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-java/s2i-java-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-nodejs/s2i-nodejs-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-perl/s2i-perl-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-php/s2i-php-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-python/s2i-python-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-ruby/s2i-ruby-task.yaml
  config/openshift/base/operator.yaml
  hack/openshift/update-image-sha.sh
  operatorhub/openshift/config.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
Labels: approved, lgtm, size/M, release-note-none
