Repository tektoncd/operator, pull requests merged in 2023-06, with the labels that each got.

#1526 [0.67.x] Fix Image Transforms for Results
  pkg/reconciler/common/testdata/test-replace-statefulset-image.yaml
  pkg/reconciler/common/transformers.go
  pkg/reconciler/common/transformers_test.go
  pkg/reconciler/kubernetes/tektonresult/transform.go
Labels: kind/bug, approved, lgtm, release-note-none, size/L

#1516 improve pruner documentation
  docs/TektonConfig.md
Labels: approved, lgtm, size/S, release-note-none

#1535 Bump pipeline and dasbhoard payloads
  components.yaml
  config/base/role.yaml
  config/openshift/base/role.yaml
Labels: approved, lgtm, size/S, release-note

#1536 Add jkandasa to approvers
  OWNERS
Labels: approved, lgtm, size/S, release-note-none

#1524 add docs for read-only mode
  docs/TektonDashboard.md
Labels: approved, lgtm, size/S, release-note-none, ok-to-test

#1539 Fix Transformers for Results Configuration
  pkg/apis/operator/v1alpha1/tektonresult_types.go
  pkg/reconciler/kubernetes/tektonresult/testdata/api-config.yaml
  pkg/reconciler/kubernetes/tektonresult/transform_test.go
Labels: kind/bug, approved, lgtm, size/M, release-note-none

#1530 add openshift monitoring label to targetNamespace
  pkg/reconciler/common/targetnamespace.go
  pkg/reconciler/common/targetnamespace_test.go
  pkg/reconciler/kubernetes/tektonhub/tektonhub.go
  pkg/reconciler/kubernetes/tektonpipeline/reconcile.go
  pkg/reconciler/openshift/tektonpipeline/extension.go
  pkg/reconciler/shared/tektonconfig/tektonconfig.go
Labels: kind/bug, approved, lgtm, size/XL, release-note-none

#1522 Update helm chart from v0.64 to v0.67
  chart/Chart.yaml
  chart/templates/deployment.yaml
  chart/templates/kubernetes-crds.yaml
  chart/templates/kubernetes-rbac.yaml
  chart/templates/openshift-crds.yaml
  chart/templates/openshift-rbac.yaml
  chart/templates/rbac.yaml
Labels: approved, lgtm, size/XXL, release-note-none, ok-to-test

#1534 Exposes `MONGO_SERVER_URL` as env in Tekton Chain
  docs/TektonChain.md
  docs/TektonConfig.md
  pkg/apis/operator/v1alpha1/tektonchain_types.go
  pkg/apis/operator/v1alpha1/tektonchain_validation.go
  pkg/apis/operator/v1alpha1/tektonchain_validation_test.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/kubernetes/tektonchain/tektonchain.go
Labels: approved, lgtm, release-note, size/L

#1558 Bump jib-maven to 0.5
  config/openshift/base/operator.yaml
  hack/openshift/update-image-sha.sh
  operatorhub/openshift/config.yaml
  pkg/reconciler/openshift/tektonaddon/communityClusterTasks.go
Labels: approved, lgtm, size/S, release-note

#1564 Update versions to latest in csv
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
Labels: approved, size/XS, lgtm, release-note

#1565 Updates CLI version
  pkg/reconciler/openshift/tektonaddon/consolecli.go
Labels: approved, size/XS, lgtm, release-note

#1566 Updates CLI version
  pkg/reconciler/openshift/tektonaddon/consolecli.go
Labels: approved, size/XS, lgtm, release-note

#1567 allow extra fields in copy configMap transformer
  pkg/reconciler/common/transformers.go
  pkg/reconciler/common/transformers_test.go
  pkg/reconciler/openshift/openshiftpipelinesascode/transform.go
Labels: approved, lgtm, size/M, release-note-none

#1570 Adds results crd to be included in csv and bundle
  operatorhub/openshift/release-artifacts/bundle/manifests/operator.tekton.dev_tektonresults.yaml
Labels: approved, lgtm, size/M, release-note

#1574 Fix maxOpenShiftVersion for 0.67.x
  operatorhub/openshift/release-artifacts/bundle/metadata/properties.yaml
Labels: approved, size/XS, lgtm, do-not-merge/release-note-label-needed

#1578 Adds Results CR in openshift kustomization
  config/crs/openshift/kustomization.yaml
Labels: approved, size/XS, lgtm, release-note

#1573 Updated CRS for for Result
  config/crs/kubernetes/result/operator_v1alpha1_result_cr.yaml
  config/crs/openshift/result/operator_v1alpha1_result_cr.yaml
Labels: approved, lgtm, size/S, release-note, kind/misc

#1586 Move ./cmd/tool commands to a package
  cmd/tool/commands/bump.go
  cmd/tool/commands/check.go
  cmd/tool/commands/components.go
  cmd/tool/main.go
Labels: size/S, release-note-none

#1572 Update Doc for TektonResult (Logging and DB)
  docs/TektonResult.md
Labels: approved, lgtm, kind/documentation, size/M, release-note
