Repository tektoncd/operator, pull requests merged in 2023-09, with the labels that each got.

#1598 Add Metrics for TektonChains
  pkg/reconciler/kubernetes/tektonchain/controller.go
  pkg/reconciler/kubernetes/tektonchain/metrics.go
  pkg/reconciler/kubernetes/tektonchain/tektonchain.go
Labels: kind/feature, approved, lgtm, release-note, size/L

#1667 Add docs for SCC configuration
  docs/SCCConfig.md
Labels: approved, lgtm, release-note-none, size/L

#1671 reconcile pruner resources on targetNamespace change
  pkg/reconciler/shared/tektonconfig/installerset_pruner.go
Labels: approved, lgtm, size/S, release-note-none

#1677 Bumps Hub to v1.14.0
  components.yaml
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
Labels: approved, size/XS, lgtm, release-note

#1678 Bump Results and Dashboard
  components.yaml
Labels: approved, size/XS, lgtm, release-note, kind/misc

#1599 Add Metrics for TektonResult
  pkg/reconciler/common/initcontroller.go
  pkg/reconciler/kubernetes/tektonresult/controller.go
  pkg/reconciler/kubernetes/tektonresult/metrics.go
  pkg/reconciler/kubernetes/tektonresult/metrics_test.go
  pkg/reconciler/kubernetes/tektonresult/tektonresult.go
  vendor/knative.dev/pkg/metrics/metricstest/metricstest.go
  vendor/knative.dev/pkg/metrics/metricstest/resource_metrics.go
  vendor/knative.dev/pkg/metrics/testing/config.go
  vendor/modules.txt
Labels: kind/feature, approved, lgtm, release-note, size/XL

#1680 Enable TektonResults access by system:authenticated user
  config/base/tekton_result_role.yaml
  config/base/tekton_result_role_binding.yaml
Labels: kind/feature, approved, lgtm, size/M, release-note

#1676 Reject incorrect SCC configuration
  cmd/openshift/operator/kodata/webhook/webhook.yaml
  cmd/openshift/proxy-webhook/main.go
  pkg/apis/operator/v1alpha1/tektonconfig_validation.go
  pkg/common/scc.go
  pkg/common/scc_test.go
  pkg/reconciler/openshift/const.go
  pkg/reconciler/openshift/namespace/controller.go
  pkg/reconciler/openshift/namespace/namespace.go
  pkg/reconciler/openshift/tektonconfig/common.go
  pkg/reconciler/openshift/tektonconfig/extension.go
  pkg/reconciler/openshift/tektonconfig/rbac.go
Labels: approved, lgtm, release-note, size/XL

#1682 Access to Results Service and Route for system:authenticated user
  cmd/openshift/operator/kodata/tekton-addon/addons/06-results/cluster-role.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/06-results/cluster-rolebinding.yaml
Labels: kind/feature, approved, lgtm, size/M, release-note-none

#1652 Add Google Creds for Results
  docs/TektonResult.md
  pkg/apis/operator/v1alpha1/tektonresult_types.go
  pkg/reconciler/kubernetes/tektonresult/testdata/api-config.yaml
  pkg/reconciler/kubernetes/tektonresult/testdata/api-deployment-gcs.yaml
  pkg/reconciler/kubernetes/tektonresult/transform.go
  pkg/reconciler/kubernetes/tektonresult/transform_test.go
Labels: kind/feature, approved, lgtm, release-note, size/L

#1684 Remove Results Service Access for system:authenticated user
  cmd/openshift/operator/kodata/tekton-addon/addons/06-results/cluster-role.yaml
Labels: approved, size/XS, lgtm, release-note-none

#1654 Add support for External DB in Tekton Results
  docs/TektonResult.md
  pkg/apis/operator/v1alpha1/tektonresult_types.go
  pkg/reconciler/kubernetes/tektonresult/filter.go
  pkg/reconciler/kubernetes/tektonresult/filter_test.go
  pkg/reconciler/kubernetes/tektonresult/tektonresult.go
  pkg/reconciler/kubernetes/tektonresult/testdata/db-statefulset.yaml
  pkg/reconciler/kubernetes/tektonresult/transform_test.go
Labels: kind/feature, approved, lgtm, release-note-none, size/L

#1664 Add informer for statefulset workloads
  pkg/apis/operator/v1alpha1/tektoninstallerset_lifecycle.go
  pkg/apis/operator/v1alpha1/tektoninstallerset_lifecycle_test.go
  pkg/reconciler/kubernetes/tektoninstallerset/client/main_set_test.go
  pkg/reconciler/kubernetes/tektoninstallerset/controller.go
  pkg/reconciler/kubernetes/tektoninstallerset/install.go
  pkg/reconciler/kubernetes/tektoninstallerset/install_test.go
  pkg/reconciler/kubernetes/tektoninstallerset/tektoninstallerset.go
  vendor/knative.dev/pkg/client/injection/kube/informers/apps/v1/statefulset/statefulset.go
  vendor/knative.dev/pkg/client/injection/kube/informers/apps/v1/statefulset/statefulset_expansion.go
  vendor/modules.txt
Labels: kind/feature, approved, lgtm, release-note, size/L

#1685 Adding events image env for openshift
  operatorhub/openshift/config.yaml
Labels: approved, size/XS, lgtm, release-note-none

#1675 introduce upgrade mechanism and add upgrade patch to v1 storage migration
  pkg/apis/operator/v1alpha1/const.go
  pkg/apis/operator/v1alpha1/tektonconfig_lifecycle.go
  pkg/apis/operator/v1alpha1/tektonconfig_lifecycle_test.go
  pkg/reconciler/shared/tektonconfig/controller.go
  pkg/reconciler/shared/tektonconfig/tektonconfig.go
  pkg/reconciler/shared/tektonconfig/upgrade/helper/storage_version_migrator.go
  pkg/reconciler/shared/tektonconfig/upgrade/helper/storage_version_migrator_test.go
  pkg/reconciler/shared/tektonconfig/upgrade/post_upgrade.go
  pkg/reconciler/shared/tektonconfig/upgrade/pre_upgrade.go
  pkg/reconciler/shared/tektonconfig/upgrade/pre_upgrade_test.go
  pkg/reconciler/shared/tektonconfig/upgrade/upgrade.go
  pkg/reconciler/shared/tektonconfig/upgrade/upgrade_test.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/fake/clientset_generated.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/fake/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/fake/register.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/fake/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/fake/fake_apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1/fake/fake_customresourcedefinition.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/fake/doc.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/fake/fake_apiextensions_client.go
  vendor/k8s.io/apiextensions-apiserver/pkg/client/clientset/clientset/typed/apiextensions/v1beta1/fake/fake_customresourcedefinition.go
  vendor/k8s.io/client-go/dynamic/fake/simple.go
  vendor/knative.dev/pkg/apiextensions/storageversion/migrator.go
  vendor/modules.txt
Labels: kind/bug, approved, lgtm, size/XXL, release-note-none

#1688 update image sha to prepare release
  chart/templates/deployment.yaml
  config/kubernetes/base/operator.yaml
  config/openshift/base/operator.yaml
  operatorhub/kubernetes/config.yaml
  operatorhub/openshift/config.yaml
Labels: approved, lgtm, size/M, release-note-none

#1690 Bump pac to v0.21.0
  components.yaml
  go.mod
  go.sum
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
  vendor/github.com/openshift-pipelines/pipelines-as-code/pkg/params/settings/config.go
  vendor/github.com/openshift-pipelines/pipelines-as-code/pkg/params/settings/default.go
  vendor/github.com/openshift-pipelines/pipelines-as-code/pkg/params/settings/validation.go
  vendor/modules.txt
Labels: approved, lgtm, size/M, release-note

#1691 Update properties.yaml to 4.15
  operatorhub/openshift/release-artifacts/bundle/metadata/properties.yaml
Labels: approved, size/XS, lgtm, release-note-none

#1693 allow operator to manage resources in pipelinesascode.tekton.dev group
  config/openshift/base/role.yaml
  pkg/reconciler/shared/tektonconfig/upgrade/post_upgrade.go
Labels: approved, size/XS, lgtm, release-note-none

#1697 Downgrade maxOpenShift version to 4.14
  operatorhub/openshift/release-artifacts/bundle/metadata/properties.yaml
Labels: approved, size/XS, lgtm, release-note, kind/misc

#1701 Fix clean not removing pruner file
  Makefile
Labels: approved, lgtm, size/S, release-note

#1709 Fix the version configmap for results
  pkg/reconciler/kubernetes/tektonresult/controller.go
Labels: approved, size/XS, lgtm, release-note-none

#1711 Freezing Component versions and updating version labels
  cmd/kubernetes/operator/kodata/webhook/webhook.yaml
  cmd/openshift/operator/kodata/webhook/webhook.yaml
  config/base/300-operator_v1alpha1_chain_crd.yaml
  config/base/300-operator_v1alpha1_config_crd.yaml
  config/base/300-operator_v1alpha1_hub_crd.yaml
  config/base/300-operator_v1alpha1_installer_set_crd.yaml
  config/base/300-operator_v1alpha1_pipeline_crd.yaml
  config/base/300-operator_v1alpha1_result_crd.yaml
  config/base/300-operator_v1alpha1_trigger_crd.yaml
  config/base/config-info.yaml
  config/base/operator.yaml
  config/kubernetes/base/300-operator_v1alpha1_dashboard_crd.yaml
  config/kubernetes/base/operator.yaml
  config/kubernetes/base/operator_service.yaml
  config/kubernetes/base/webhook.yaml
  config/openshift/base/300-operator_v1alpha1_addon_crd.yaml
  config/openshift/base/300-operator_v1alpha1_openshiftpipelinesascode_crd.yaml
  config/openshift/base/operator.yaml
  config/openshift/base/operator_service.yaml
  config/openshift/base/webhook.yaml
  config/webhooks/webhook-service.yaml
  config/webhooks/webhook.yaml
Labels: approved, lgtm, size/M, release-note

#1713 Filter service and cm of Postgres for externalDB
  pkg/reconciler/kubernetes/tektonresult/filter.go
  pkg/reconciler/kubernetes/tektonresult/filter_test.go
  pkg/reconciler/kubernetes/tektonresult/tektonresult.go
  pkg/reconciler/kubernetes/tektonresult/testdata/db-statefulset.yaml
Labels: approved, lgtm, size/M, release-note

#1718 Fix TektonResult CR not showing version
  pkg/reconciler/common/initcontroller.go
  pkg/reconciler/kubernetes/tektonresult/installerset.go
  pkg/reconciler/kubernetes/tektonresult/tektonresult.go
Labels: approved, size/XS, lgtm, release-note-none

#1715 update version to 0.68.0 in helm chart
  chart/Chart.yaml
  chart/templates/kubernetes-crds.yaml
  chart/templates/openshift-crds.yaml
Labels: approved, lgtm, size/M, release-note-none, ok-to-test

#1724 Validate SCC exists before admission
  cmd/openshift/proxy-webhook/main.go
  pkg/apis/operator/v1alpha1/tektonconfig_validation.go
  pkg/reconciler/openshift/namespace/controller.go
  pkg/reconciler/openshift/namespace/namespace.go
  pkg/reconciler/openshift/tektonconfig/extension.go
  pkg/reconciler/openshift/tektonconfig/rbac.go
  test/e2e/openshift/tektonaddondeployment_test.go
Labels: approved, lgtm, size/M, release-note-none

#1725 Fix TektonResult read access
  config/base/kustomization.yaml
  config/base/tekton_result_role.yaml
Labels: approved, size/XS, lgtm, release-note-none

#1731 Sort SCCs from most restrictive to least
  pkg/apis/operator/v1alpha1/tektonconfig_validation.go
  pkg/common/scc.go
  pkg/common/scc_test.go
  pkg/reconciler/openshift/namespace/namespace.go
  pkg/reconciler/openshift/tektonconfig/rbac.go
Labels: approved, lgtm, size/M, release-note-none

#1735 Add tests for non-existent SCC and default SCCs
  test/e2e/common/00_tektonconfigdeployment_test.go
Labels: approved, lgtm, size/M, release-note-none

#1739 Update git-init image
  operatorhub/openshift/config.yaml
Labels: approved, size/XS, lgtm, release-note

#1734 fix tektonConfig pre upgrade trigger logic
  pkg/apis/operator/v1alpha1/const.go
  pkg/apis/operator/v1alpha1/tektonconfig_lifecycle.go
  pkg/apis/operator/v1alpha1/tektonconfig_lifecycle_test.go
  pkg/reconciler/shared/tektonconfig/tektonconfig.go
  pkg/reconciler/shared/tektonconfig/upgrade/upgrade.go
  pkg/reconciler/shared/tektonconfig/upgrade/upgrade_test.go
Labels: approved, lgtm, release-note-none, size/L

#1741 Disable `pipelines-scc` validation for SCC.Default
  pkg/apis/operator/v1alpha1/tektonconfig_validation.go
Labels: approved, size/XS, lgtm, release-note-none

#1747 Remove Password and sensitive fields from properties
  docs/TektonResult.md
  pkg/apis/operator/v1alpha1/tektonresult_types.go
  pkg/reconciler/kubernetes/tektonresult/testdata/api-config.yaml
  pkg/reconciler/kubernetes/tektonresult/transform_test.go
Labels: approved, lgtm, size/M, release-note

#1750 fix role in openshift and include upgrade status
  config/openshift/base/role.yaml
  pkg/apis/operator/v1alpha1/tektonconfig_lifecycle.go
  pkg/apis/operator/v1alpha1/tektonconfig_lifecycle_test.go
  pkg/reconciler/shared/tektonconfig/tektonconfig.go
  pkg/reconciler/shared/tektonconfig/upgrade/post_upgrade.go
  pkg/reconciler/shared/tektonconfig/upgrade/upgrade.go
  pkg/reconciler/shared/tektonconfig/upgrade/upgrade_test.go
Labels: kind/bug, approved, lgtm, release-note-none, size/L

#1753 continue the post upgrade on storage migration errors
  pkg/reconciler/shared/tektonconfig/upgrade/helper/migrator.go
  pkg/reconciler/shared/tektonconfig/upgrade/helper/migrator_test.go
  pkg/reconciler/shared/tektonconfig/upgrade/helper/storage_version_migrator.go
  pkg/reconciler/shared/tektonconfig/upgrade/helper/storage_version_migrator_test.go
  pkg/reconciler/shared/tektonconfig/upgrade/post_upgrade.go
  vendor/modules.txt
Labels: kind/bug, approved, lgtm, release-note-none, size/L
