Repository tektoncd/operator, pull requests merged in 2023-03, with the labels that each got.

#1354 [release-v0.64.x] fix build test failures, happens after plumbing pr-1369
  pkg/client/clientset/versioned/fake/register.go
  pkg/client/clientset/versioned/scheme/register.go
  pkg/reconciler/common/proxy.go
  pkg/reconciler/common/proxy_test.go
  pkg/reconciler/kubernetes/tektonhub/tektonhub.go
  pkg/reconciler/openshift/tektonaddon/transformer.go
  third_party/github.com/fsnotify/fsnotify/LICENSE
Labels: approved, lgtm, size/M, release-note-none

#1358 [release-v0.65.x] Update pipelines-as-code to v0.17.0 :)
  components.yaml
Labels: approved, size/XS, lgtm, release-note

#1361 fixing syntax for olm.maxOpenshiftVersion
  operatorhub/openshift/release-artifacts/bundle/metadata/properties.yaml
Labels: approved, size/XS, lgtm, release-note

#1355 [0.65.x] TektonPipeline: make sure embedded-status is full by default…
  pkg/apis/operator/v1alpha1/tektonpipeline_defaults.go
Labels: approved, lgtm, size/S, release-note-none

#1368 tektonaddon: bump git-cli from 0.3 to 0.4
  pkg/reconciler/openshift/tektonaddon/communityClusterTasks.go
Labels: approved, size/XS, lgtm, release-note

#1348 Fixes `CATALOG_REFRESH_INTERVAL` in Tekon Hub CR
  pkg/reconciler/kubernetes/tektonhub/tektonhub.go
Labels: approved, size/XS, lgtm, release-note

#1378 Bump triggers version
  components.yaml
Labels: approved, size/XS, lgtm, release-note

#1379 dependabot: do not update k8s.io/* major/minor updates
  .github/dependabot.yml
Labels: approved, size/XS, lgtm, release-note-none

#1384 Update tektoncd/pipeline to 0.45.0
  go.mod
  go.sum
  pkg/apis/operator/v1alpha1/tektonpipeline_defaults.go
  pkg/apis/operator/v1alpha1/tektonpipeline_defaults_test.go
  pkg/apis/operator/v1alpha1/tektonpipeline_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/config/feature_flags.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/config/spire_config.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/config/store.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/config/trusted_resources.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/images.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1/merge.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1/openapi_generated.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1/pipeline_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1/provenance.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1/result_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1/status_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1/swagger.json
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1/task_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1/zz_generated.deepcopy.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/merge.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/openapi_generated.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipeline_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipelinerun_conversion.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/pipelinerun_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/provenance.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/provenance_conversion.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/resource_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/result_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/status_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/swagger.json
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/task_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/zz_generated.deepcopy.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/resource/v1alpha1/pipeline_resource_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/resource/v1alpha1/pipelineresource_validation.go
  vendor/github.com/tektoncd/pipeline/pkg/spire/config/config.go
  vendor/github.com/tektoncd/pipeline/pkg/spire/config/zz_generated.deepcopy.go
  vendor/knative.dev/pkg/apis/duck/v1/destination.go
  vendor/knative.dev/pkg/apis/field_error.go
  vendor/knative.dev/pkg/changeset/commit.go
  vendor/knative.dev/pkg/client/injection/kube/client/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/args/args.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/client.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/filtered_informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/informer.go
  vendor/knative.dev/pkg/codegen/cmd/injection-gen/generators/packages.go
  vendor/knative.dev/pkg/injection/sharedmain/main.go
  vendor/knative.dev/pkg/kmeta/names.go
  vendor/knative.dev/pkg/metrics/config.go
  vendor/knative.dev/pkg/metrics/config_observability.go
  vendor/knative.dev/pkg/metrics/prometheus_exporter.go
  vendor/knative.dev/pkg/network/h2c.go
  vendor/knative.dev/pkg/profiling/server.go
  vendor/knative.dev/pkg/reconciler/testing/reactions.go
  vendor/knative.dev/pkg/reconciler/testing/table.go
  vendor/knative.dev/pkg/version/version.go
  vendor/knative.dev/pkg/webhook/resourcesemantics/validation/validation_admit.go
  vendor/knative.dev/pkg/webhook/webhook.go
  vendor/modules.txt
Labels: approved, lgtm, release-note, size/XXL

#1385 Ignore openshift/client-go as it doesn't tag versions
  .github/dependabot.yml
Labels: approved, size/XS, lgtm, release-note-none

#1387 Ensure operator always sets targetNamespace label
  pkg/reconciler/shared/tektonconfig/tektonconfig.go
Labels: approved, size/XS, lgtm, release-note-none, ok-to-test

#1397 Adds `default-forbidden-env` field for Pipelines
  pkg/apis/operator/v1alpha1/tektonpipeline_types.go
  third_party/filippo.io/edwards25519/LICENSE
  third_party/github.com/digitorus/pkcs7/LICENSE
  third_party/github.com/digitorus/timestamp/LICENSE
  third_party/github.com/go-logr/stdr/LICENSE
  third_party/github.com/google/go-github/v50/github/LICENSE
  third_party/github.com/sigstore/cosign/v2/LICENSE
  third_party/github.com/sigstore/timestamp-authority/pkg/verification/LICENSE
  third_party/go.opentelemetry.io/otel/LICENSE
  third_party/go.opentelemetry.io/otel/trace/LICENSE
  third_party/go.step.sm/crypto/LICENSE
  third_party/go.step.sm/crypto/internal/bcrypt_pbkdf/LICENSE
Labels: approved, lgtm, release-note, size/XXL

#1402 [v0.65.x] TektonPipeline: make sure embedded-status is "both" by defa…
  pkg/apis/operator/v1alpha1/tektonpipeline_defaults.go
Labels: approved, size/XS, lgtm, release-note-none

#1404 bumping the tkn version to use 0.30.0 in consolecli
  pkg/reconciler/openshift/tektonaddon/consolecli.go
Labels: approved, size/XS, lgtm, release-note

#1405 Moves `default-forbidden-env` to optional Pipelines properties
  pkg/apis/operator/v1alpha1/tektonpipeline_types.go
Labels: approved, size/XS, lgtm, release-note

#1377 Update release-cheat-sheet for consistency
  tekton/release-cheat-sheet.md
Labels: approved, size/XS, lgtm, release-note

#1412 remove pruner container user and fsGroup ids in OpenShift platform
  pkg/reconciler/common/prune.go
Labels: approved, lgtm, size/S, release-note-none

#1418 Bumping PAC version to 0.17.2
  components.yaml
Labels: approved, size/XS, lgtm, release-note
