Repository tektoncd/operator, pull requests merged in 2024-12, with the labels that each got.

#2430 Remove older versions of task and stepactions resolver installersets
  pkg/reconciler/shared/tektonconfig/upgrade/post_upgrade.go
  pkg/reconciler/shared/tektonconfig/upgrade/upgrade.go
Labels: approved, lgtm, size/M, release-note

#2429 enable fips compliance on openshift operator
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml.tmpl
Labels: approved, size/XS, lgtm, release-note-none

#2445 Fix env keys for git-clone and git-cli task
  operatorhub/openshift/config.yaml
Labels: approved, size/XS, lgtm, release-note

#2441 Adds runtimeclassname support in `options` field for deployment and statefulsets
  docs/TektonConfig.md
  pkg/reconciler/common/testdata/test-additional-options-base-runtimeclassname-deployment.yaml
  pkg/reconciler/common/testdata/test-additional-options-base-runtimeclassname-statefulset.yaml
  pkg/reconciler/common/testdata/test-additional-options-test-runtimeclassname-deployment.yaml
  pkg/reconciler/common/testdata/test-additional-options-test-runtimeclassname-statefulset.yaml
  pkg/reconciler/common/transformer_additional_options.go
  pkg/reconciler/common/transformer_additional_options_test.go
Labels: approved, lgtm, release-note, size/XL

#2460 update pruner sha with latest
  charts/tekton-operator/values.yaml
  config/kubernetes/base/operator.yaml
  config/openshift/base/operator.yaml
  operatorhub/kubernetes/config.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/tektoncd-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/S, release-note

#2462 Update the release to use ghcr.io
  tekton/build-publish-images-manifests.yaml
  tekton/operator-release-pipeline.yaml
  tekton/release-cheat-sheet.md
  tekton/setup-release-from-scratch.md
Labels: approved, lgtm, release-note, size/L

#2465 Update DEVELOPMENT.md
  DEVELOPMENT.md
Labels: approved, size/XS, lgtm, kind/documentation, release-note, ok-to-test

#2466 Fix wrong shell in release task
  tekton/build-publish-images-manifests.yaml
  tekton/operator-release-pipeline.yaml
Labels: approved, lgtm, size/S, release-note, kind/misc

#2475 Fix nightly failures
  tekton/operator-release-pipeline.yaml
Labels: approved, size/XS, lgtm, release-note-none
