Repository tektoncd/operator, pull requests merged in 2024-11, with the labels that each got.

#2387 Add Results Prometheus histogram config
  docs/TektonResult.md
  pkg/apis/operator/v1alpha1/tektonresult_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/kubernetes/tektonresult/testdata/api-config.yaml
  pkg/reconciler/kubernetes/tektonresult/transform_test.go
Labels: approved, lgtm, size/S, release-note-none

#2382 Add Tekton Results DB_SSLROOTCERT config option
  docs/TektonResult.md
  pkg/apis/operator/v1alpha1/tektonresult_types.go
  pkg/reconciler/kubernetes/tektonresult/testdata/api-config.yaml
  pkg/reconciler/kubernetes/tektonresult/transform_test.go
Labels: approved, lgtm, size/S, release-note-none

#2411 Update CSV template file to remove the cluster task
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml.tmpl
Labels: approved, size/XS, lgtm, release-note

#2413 Update task version
  hack/openshift/fetch-tektoncd-catalog-tasks.sh
Labels: approved, lgtm, size/S, release-note

#2414 Update image sha to latest
  config/openshift/base/operator.yaml
  operatorhub/openshift/config.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
Labels: approved, lgtm, size/M, release-note-none

#2417 [main] include jkhelil as approver
  OWNERS
Labels: approved, size/XS, lgtm, release-note-none

#2418 Update Makefile to include component-bump in help command
  Makefile
Labels: approved, size/XS, lgtm, release-note-none

#2419 update charts on main with devel version
  charts/tekton-operator/Chart.yaml
  charts/tekton-operator/templates/kubernetes-crds.yaml
  charts/tekton-operator/templates/openshift-crds.yaml
Labels: approved, lgtm, size/M, release-note

#2420 add version 0.74.0 to supported version on the readme
  README.md
Labels: approved, size/XS, lgtm, release-note-none

#2425 Updates go.mod by executing update-codegen script
  go.mod
Labels: approved, size/XS, lgtm, release-note-none

#2426 Update base image from rhel8/ubi8 to rhel9/ubi9
  config/openshift/base/operator.yaml
  hack/openshift/update-image-sha.sh
  operatorhub/openshift/config.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
Labels: approved, lgtm, size/M, release-note-none

#2432 fix namespace reconciliation error during openshift rbac reconciliation
  pkg/reconciler/openshift/tektonconfig/rbac.go
Labels: approved, lgtm, size/S, release-note-none, ok-to-test
