Repository tektoncd/operator, pull requests merged in 2024-03, with the labels that each got.

#2046 [v0.70.x] prepare v0.70.1 patch release
  charts/tekton-operator/Chart.yaml
  charts/tekton-operator/templates/kubernetes-crds.yaml
  charts/tekton-operator/templates/openshift-crds.yaml
  cmd/kubernetes/operator/kodata/webhook/webhook.yaml
  cmd/openshift/operator/kodata/cabundles/config-service-cabundle.yaml
  cmd/openshift/operator/kodata/cabundles/config-trusted-cabundle.yaml
  cmd/openshift/operator/kodata/webhook/webhook.yaml
  components.yaml
  config/base/300-operator_v1alpha1_chain_crd.yaml
  config/base/300-operator_v1alpha1_config_crd.yaml
  config/base/300-operator_v1alpha1_hub_crd.yaml
  config/base/300-operator_v1alpha1_installer_set_crd.yaml
  config/base/300-operator_v1alpha1_pipeline_crd.yaml
  config/base/300-operator_v1alpha1_result_crd.yaml
  config/base/300-operator_v1alpha1_trigger_crd.yaml
  config/base/config-info.yaml
  config/base/config-leader-election.yaml
  config/base/config-logging.yaml
  config/base/operator.yaml
  config/base/tekton-config-defaults.yaml
  config/kubernetes/base/300-operator_v1alpha1_dashboard_crd.yaml
  config/kubernetes/base/operator.yaml
  config/kubernetes/base/operator_service.yaml
  config/kubernetes/base/webhook.yaml
  config/openshift/base/300-operator_v1alpha1_addon_crd.yaml
  config/openshift/base/300-operator_v1alpha1_openshiftpipelinesascode_crd.yaml
  config/openshift/base/operator.yaml
  config/openshift/base/operator_service.yaml
  config/openshift/base/webhook.yaml
  config/webhooks/webhook-config-leader-election.yaml
  config/webhooks/webhook-service.yaml
  config/webhooks/webhook.yaml
  go.mod
  go.sum
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
  vendor/modules.txt
Labels: approved, lgtm, release-note-none, size/L

#2043 Revert "Fix Conflict between Results PreReconciler and Reconciler"
  pkg/reconciler/kubernetes/tektonresult/tektonresult.go
Labels: approved, lgtm, size/M, release-note-none, kind/misc

#2047 Documentation aesthetics - removed the excess ``` backticks from fenced code block after rendering
  docs/install.md
Labels: approved, size/XS, lgtm, release-note-none, ok-to-test

#2051 Fix typo of additional pac controller details
  docs/OpenShiftPipelinesAsCode.md
Labels: approved, size/XS, lgtm, release-note

#2054 [main] update OpenShift bundle features annotations
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
Labels: approved, size/XS, lgtm, release-note-none

#2056 [v0.70.x] prepare v0.70.2 patch release
  charts/tekton-operator/Chart.yaml
  charts/tekton-operator/templates/kubernetes-crds.yaml
  charts/tekton-operator/templates/openshift-crds.yaml
  cmd/kubernetes/operator/kodata/webhook/webhook.yaml
  cmd/openshift/operator/kodata/cabundles/config-service-cabundle.yaml
  cmd/openshift/operator/kodata/cabundles/config-trusted-cabundle.yaml
  cmd/openshift/operator/kodata/webhook/webhook.yaml
  components.yaml
  config/base/300-operator_v1alpha1_chain_crd.yaml
  config/base/300-operator_v1alpha1_config_crd.yaml
  config/base/300-operator_v1alpha1_hub_crd.yaml
  config/base/300-operator_v1alpha1_installer_set_crd.yaml
  config/base/300-operator_v1alpha1_pipeline_crd.yaml
  config/base/300-operator_v1alpha1_result_crd.yaml
  config/base/300-operator_v1alpha1_trigger_crd.yaml
  config/base/config-info.yaml
  config/base/config-leader-election.yaml
  config/base/config-logging.yaml
  config/base/operator.yaml
  config/base/tekton-config-defaults.yaml
  config/kubernetes/base/300-operator_v1alpha1_dashboard_crd.yaml
  config/kubernetes/base/operator.yaml
  config/kubernetes/base/operator_service.yaml
  config/kubernetes/base/webhook.yaml
  config/openshift/base/300-operator_v1alpha1_addon_crd.yaml
  config/openshift/base/300-operator_v1alpha1_openshiftpipelinesascode_crd.yaml
  config/openshift/base/operator.yaml
  config/openshift/base/operator_service.yaml
  config/openshift/base/webhook.yaml
  config/webhooks/webhook-config-leader-election.yaml
  config/webhooks/webhook-service.yaml
  config/webhooks/webhook.yaml
  go.mod
  go.sum
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
  vendor/modules.txt
Labels: approved, lgtm, release-note-none, size/L

#2059 [main] support startingDeadlineSeconds configuration in pruner cron jobs
  docs/TektonConfig.md
  pkg/apis/operator/v1alpha1/tektonconfig_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/common/prune.go
  pkg/reconciler/common/prune_test.go
Labels: approved, lgtm, size/M, release-note

#2064 [main] remove unnecessary log
  pkg/reconciler/common/prune.go
Labels: approved, size/XS, lgtm, release-note-none

#2067 [release-0.70.x] Update component versions in the clusterserviceversi…
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
Labels: size/XS, release-note-none

#2066 Update component versions in the clusterserviceversion template.
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
Labels: approved, lgtm, size/S, release-note-none

#2068 [release-0.69.x] Update component versions in the clusterserviceversi…
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
Labels: approved, size/XS, lgtm, release-note-none

#2075 [0.69.x] bump patch version
  chart/Chart.yaml
  chart/templates/kubernetes-crds.yaml
  chart/templates/openshift-crds.yaml
  cmd/kubernetes/operator/kodata/webhook/webhook.yaml
  cmd/openshift/operator/kodata/cabundles/config-service-cabundle.yaml
  cmd/openshift/operator/kodata/cabundles/config-trusted-cabundle.yaml
  cmd/openshift/operator/kodata/webhook/webhook.yaml
  config/base/300-operator_v1alpha1_chain_crd.yaml
  config/base/300-operator_v1alpha1_config_crd.yaml
  config/base/300-operator_v1alpha1_hub_crd.yaml
  config/base/300-operator_v1alpha1_installer_set_crd.yaml
  config/base/300-operator_v1alpha1_pipeline_crd.yaml
  config/base/300-operator_v1alpha1_result_crd.yaml
  config/base/300-operator_v1alpha1_trigger_crd.yaml
  config/base/config-info.yaml
  config/base/config-logging.yaml
  config/base/operator.yaml
  config/base/tekton-config-defaults.yaml
  config/kubernetes/base/300-operator_v1alpha1_dashboard_crd.yaml
  config/kubernetes/base/operator.yaml
  config/kubernetes/base/operator_service.yaml
  config/kubernetes/base/webhook.yaml
  config/openshift/base/300-operator_v1alpha1_addon_crd.yaml
  config/openshift/base/300-operator_v1alpha1_openshiftpipelinesascode_crd.yaml
  config/openshift/base/operator.yaml
  config/openshift/base/operator_service.yaml
  config/openshift/base/webhook.yaml
  config/webhooks/webhook-service.yaml
  config/webhooks/webhook.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/config-logging_v1_configmap.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/operator.tekton.dev_tektonchains.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/operator.tekton.dev_tektonconfigs.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/operator.tekton.dev_tektondashboards.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/operator.tekton.dev_tektonhubs.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/operator.tekton.dev_tektoninstallersets.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/operator.tekton.dev_tektonpipelines.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/operator.tekton.dev_tektonresults.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/operator.tekton.dev_tektontriggers.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/tekton-config-defaults_v1_configmap.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/tekton-operator-info_v1_configmap.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/tekton-operator-webhook_v1_service.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/tekton-operator_v1_service.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/tektoncd-operator.clusterserviceversion.yaml
Labels: approved, lgtm, release-note-none, size/L

#2077 Bump tkn version to v0.35.2
  pkg/reconciler/openshift/tektonaddon/consolecli.go
Labels: approved, size/XS, lgtm, release-note

#2084 [main] make options 'disabled' field as pointer to reduce the noise on TektonConfig CR
  pkg/apis/operator/v1alpha1/additional_options.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/common/transformer_additional_options.go
  pkg/reconciler/common/transformer_additional_options_test.go
  pkg/reconciler/kubernetes/tektoninstallerset/client/check_test.go
Labels: approved, lgtm, size/M, release-note-none
