Repository tektoncd/operator, pull requests merged in 2024-06, with the labels that each got.

#2188 Bump components version of pipeline and dashboard
  components.yaml
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
Labels: approved, size/XS, lgtm, release-note-none

#2174 Support for disconnected environments for resolverTasks
  config/openshift/base/operator.yaml
  hack/openshift/fetch-tektoncd-catalog-tasks.sh
  operatorhub/openshift/config.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
  pkg/reconciler/common/transformers.go
  pkg/reconciler/openshift/tektonaddon/resolverTask.go
Labels: approved, lgtm, size/M, release-note, ok-to-test

#2187 Update install.md to reflect the correct installation behaviour
  docs/install.md
Labels: approved, size/XS, lgtm, release-note-none

#2190 [main] remove unsupported versions from bump payload
  .github/workflows/bump-payload-on-releases.yaml
Labels: approved, size/XS, lgtm, release-note-none

#2129 Add webhookconfiguration options to tektonConfig additional options
  docs/TektonConfig.md
  docs/TektonPipeline.md
  hack/fetch-releases.sh
  pkg/apis/operator/v1alpha1/additional_options.go
  pkg/apis/operator/v1alpha1/additional_options_validation.go
  pkg/apis/operator/v1alpha1/tektonconfig_validation.go
  pkg/apis/operator/v1alpha1/tektonconfig_validation_test.go
  pkg/apis/operator/v1alpha1/tektonpipeline_types.go
  pkg/apis/operator/v1alpha1/tektonpipeline_validation.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/common/testdata/test-additional-options-base-webhook.yaml
  pkg/reconciler/common/testdata/test-additional-options-test-webhook.yaml
  pkg/reconciler/common/transformer_additional_options.go
  pkg/reconciler/common/transformer_additional_options_test.go
Labels: approved, lgtm, release-note, ok-to-test, size/L

#2200 Remove unused variable tknVersion
  pkg/reconciler/openshift/tektonaddon/consolecli.go
  pkg/reconciler/openshift/tektonaddon/transformer.go
  pkg/reconciler/openshift/tektonaddon/transformer_test.go
Labels: approved, lgtm, size/S, release-note-none

#2176 Fix PAC config not handling hub catalogs
  go.mod
  go.sum
  pkg/apis/operator/v1alpha1/openshiftpipelinesascode_defaults.go
  pkg/apis/operator/v1alpha1/openshiftpipelinesascode_defaults_test.go
  pkg/apis/operator/v1alpha1/openshiftpipelinesascode_validation.go
  pkg/reconciler/openshift/openshiftpipelinesascode/testdata/test-expected-additional-pac-cm.yaml
  pkg/reconciler/openshift/openshiftpipelinesascode/transform.go
  pkg/reconciler/openshift/openshiftpipelinesascode/transform_test.go
  vendor/github.com/openshift-pipelines/pipelines-as-code/pkg/params/settings/config.go
  vendor/github.com/openshift-pipelines/pipelines-as-code/pkg/params/settings/convert.go
  vendor/github.com/openshift-pipelines/pipelines-as-code/pkg/params/settings/default.go
  vendor/modules.txt
Labels: approved, lgtm, release-note, size/L

#2203 Support for disconnected environments
  config/openshift/base/operator.yaml
  hack/openshift/fetch-tektoncd-catalog-tasks.sh
  operatorhub/openshift/config.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
  pkg/reconciler/common/transformers.go
  pkg/reconciler/openshift/tektonaddon/resolverTask.go
Labels: approved, lgtm, size/M, release-note

#2204 Fix cvp issue by removing internal registry from relatedImages
  config/openshift/base/operator.yaml
  operatorhub/openshift/config.yaml
Labels: kind/bug, approved, size/XS, lgtm, release-note-none

#2209 Add missing manualapprovalgate CR
  config/crs/kubernetes/kustomization.yaml
  config/crs/openshift/kustomization.yaml
Labels: approved, size/XS, lgtm, release-note

#2208 Fix validation for additionalPacController settings
  pkg/apis/operator/v1alpha1/openshiftpipelinesascode_validation.go
  pkg/apis/operator/v1alpha1/openshiftpipelinesascode_validation_test.go
Labels: kind/bug, approved, lgtm, release-note, size/L

#2215 Update task versions for s2i and tkn
  hack/openshift/fetch-tektoncd-catalog-tasks.sh
Labels: approved, lgtm, size/S, release-note

#2219 skip ManualApprovalgate tests on s390x/ppc64le arch
  test/e2e/common/06_manualapprovalgatedeployment_test.go
Labels: approved, size/XS, lgtm, release-note
