Repository tektoncd/operator, pull requests merged in 2024-04, with the labels that each got.

#2083 [main] perform manifest transformation earlier
  pkg/reconciler/kubernetes/tektoninstallerset/client/check.go
  pkg/reconciler/kubernetes/tektoninstallerset/client/cleanup.go
  pkg/reconciler/kubernetes/tektoninstallerset/client/create.go
  pkg/reconciler/kubernetes/tektoninstallerset/client/create_test.go
  pkg/reconciler/kubernetes/tektoninstallerset/client/custom_versioned_clustertask.go
  pkg/reconciler/kubernetes/tektoninstallerset/client/main_set.go
  pkg/reconciler/kubernetes/tektoninstallerset/client/pre_post_custom_set.go
  pkg/reconciler/kubernetes/tektoninstallerset/client/update.go
  pkg/reconciler/kubernetes/tektoninstallerset/client/update_test.go
Labels: kind/bug, approved, lgtm, release-note-none, size/L

#2109 [main] apply nodeSelector, tolerations, and priorityClassName into pipelines-console-plugin pod
  pkg/reconciler/openshift/tektonconfig/console_plugin_reconciler.go
  pkg/reconciler/openshift/tektonconfig/console_plugin_reconciler_test.go
Labels: approved, lgtm, size/M, release-note-none

#2101 [2100] Reconcile a namespace again with missing rolebinding
  pkg/reconciler/openshift/tektonconfig/rbac.go
Labels: approved, size/XS, lgtm, release-note, ok-to-test

#2092 [main] HPA creation enabled via options
  docs/TektonConfig.md
  pkg/reconciler/common/testdata/test-additional-options-test-hpa.yaml
  pkg/reconciler/common/transformer_additional_options.go
Labels: approved, lgtm, release-note, size/L

#2099 Wrap errors with more context while creating resources in the operator
  pkg/reconciler/openshift/tektonconfig/common.go
  pkg/reconciler/openshift/tektonconfig/rbac.go
Labels: approved, lgtm, size/S, release-note, ok-to-test

#2013 [0.70.0] update kubernetes release artifacts bundle
  operatorhub/kubernetes/release-artifacts/bundle.Dockerfile
  operatorhub/kubernetes/release-artifacts/bundle/manifests/config-logging_v1_configmap.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/operator.tekton.dev_tektonchains.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/operator.tekton.dev_tektonconfigs.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/operator.tekton.dev_tektondashboards.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/operator.tekton.dev_tektonhubs.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/operator.tekton.dev_tektoninstallersets.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/operator.tekton.dev_tektonpipelines.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/operator.tekton.dev_tektonresults.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/operator.tekton.dev_tektontriggers.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/tekton-config-defaults_v1_configmap.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/tekton-operator-controller-config-leader-election_v1_configmap.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/tekton-operator-info_rbac.authorization.k8s.io_v1_role.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/tekton-operator-info_v1_configmap.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/tekton-operator-webhook-config-leader-election_v1_configmap.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/tekton-operator-webhook_v1_service.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/tekton-operator_v1_service.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/tekton-result-read-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/tekton-result-read-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/tektoncd-operator.clusterserviceversion.yaml
  operatorhub/kubernetes/release-artifacts/bundle/metadata/annotations.yaml
Labels: approved, lgtm, release-note-none, size/L

#2065 Disallow to update the targetNamespace in TektonConfig CR
  pkg/apis/operator/v1alpha1/tektonconfig_validation.go
  pkg/apis/operator/v1alpha1/tektonconfig_validation_test.go
Labels: approved, lgtm, size/M, release-note

#2124 Bump go to 1.21
  Makefile
  go.mod
  go.sum
  vendor/github.com/buildkite/agent/v3/api/retryable.go
  vendor/github.com/buildkite/agent/v3/version/VERSION
  vendor/modules.txt
Labels: approved, lgtm, release-note, size/L

#2126 [0.70.x] fixes chart version
  charts/tekton-operator/Chart.yaml
Labels: approved, size/XS, lgtm, release-note-none
