Repository tektoncd/operator, pull requests merged in 2024-07, with the labels that each got.

#2223 docs: remove unsupported feature flag `scope-when-expressions-to-task`
  docs/TektonConfig.md
  docs/TektonPipeline.md
  pkg/apis/operator/v1alpha1/tektonpipeline_types.go
Labels: approved, size/XS, lgtm, release-note, ok-to-test

#2161 Add support for using nightly release
  Makefile
  components.nightly.yaml
Labels: approved, lgtm, size/S, release-note

#2229 Update task-git version to 0.3.1
  hack/openshift/fetch-tektoncd-catalog-tasks.sh
Labels: approved, size/XS, lgtm, release-note

#2179 ArtifactsPipelineRunEnableDeepInspection making this field to accept both bool and string
  pkg/apis/operator/v1alpha1/tektonchain_types.go
  pkg/apis/operator/v1alpha1/tektonchain_validation.go
  pkg/apis/operator/v1alpha1/tektonchain_validation_test.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
Labels: approved, lgtm, size/M, release-note

#2227 Add versioned task for resolver task
  pkg/reconciler/kubernetes/tektoninstallerset/client/custom_versioned_clustertask.go
  pkg/reconciler/openshift/tektonaddon/cluster_task.go
  pkg/reconciler/openshift/tektonaddon/cluster_task_versioned.go
  pkg/reconciler/openshift/tektonaddon/community_cluster_tasks.go
  pkg/reconciler/openshift/tektonaddon/const.go
  pkg/reconciler/openshift/tektonaddon/openshift_console.go
  pkg/reconciler/openshift/tektonaddon/resolver_task.go
  pkg/reconciler/openshift/tektonaddon/resolver_task_versioned.go
  pkg/reconciler/openshift/tektonaddon/tektonaddon.go
  pkg/reconciler/openshift/tektonaddon/testdata/test-versioned-resolver-name-expected.yaml
  pkg/reconciler/openshift/tektonaddon/testdata/test-versioned-resolvertask-name.yaml
  pkg/reconciler/openshift/tektonaddon/transformer.go
  pkg/reconciler/openshift/tektonaddon/transformer_test.go
Labels: approved, lgtm, release-note, size/L

#2230 Update helm charts with manual approvalgate CR
  charts/tekton-operator/Chart.yaml
  charts/tekton-operator/templates/deployment.yaml
  charts/tekton-operator/templates/kubernetes-crds.yaml
  charts/tekton-operator/templates/openshift-crds.yaml
  charts/tekton-operator/templates/openshift-rbac.yaml
  charts/tekton-operator/values.yaml
  config/kubernetes/base/operator.yaml
Labels: approved, lgtm, release-note, size/L

#2125 Update triggers default configmap for runAsUser and runAsGroup to handle restricted securityContext for Triggers
  pkg/reconciler/openshift/tektontrigger/extension.go
  pkg/reconciler/openshift/tektontrigger/transformers_test.go
Labels: approved, lgtm, size/S, release-note

#2245 Fix devel version replacement
  cmd/kubernetes/operator/kodata/webhook/webhook.yaml
  cmd/openshift/operator/kodata/cabundles/config-service-cabundle.yaml
  cmd/openshift/operator/kodata/cabundles/config-trusted-cabundle.yaml
  cmd/openshift/operator/kodata/webhook/webhook.yaml
  config/webhooks/webhook-config-leader-election.yaml
  hack/release.sh
Labels: approved, lgtm, size/S, release-note

#2246 Bump charts version and image sha
  charts/tekton-operator/Chart.yaml
  charts/tekton-operator/templates/kubernetes-crds.yaml
  charts/tekton-operator/templates/openshift-crds.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/buildah/buildah-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-dotnet/s2i-dotnet-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-go/s2i-go-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-java/s2i-java-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-nodejs/s2i-nodejs-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-perl/s2i-perl-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-php/s2i-php-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-python/s2i-python-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-ruby/s2i-ruby-task.yaml
  config/openshift/base/operator.yaml
  operatorhub/openshift/config.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
Labels: approved, lgtm, release-note, size/L

#2247 Update readme for k8s version
  README.md
  tekton/release-cheat-sheet.md
  tekton/task-fetch-components.yaml
Labels: approved, size/XS, lgtm, release-note

#2248 Fix alibabacloud-go/cr-20160607 license
  go.mod
  go.sum
  vendor/github.com/alibabacloud-go/cr-20160607/LICENSE
  vendor/modules.txt
Labels: approved, lgtm, release-note-none, size/L

#2250 Fix HPA apiVersion
  pkg/reconciler/common/testdata/inject-label/05-existing-labels-release.yaml
  pkg/reconciler/common/testdata/inject-label/06-existing-labels-release-expected.yaml
Labels: approved, lgtm, size/S, release-note

#2251 Add manual approval CRD in kubernetes csv
  operatorhub/kubernetes/manifests/bases/tektoncd-operator.clusterserviceversion.template.yaml
  operatorhub/kubernetes/manifests/bases/tektoncd-operator.clusterserviceversion.template.yaml.tmpl
Labels: approved, lgtm, size/S, release-note

#2254 [main] setup required resources for hub e2e tests
  test/e2e/common/05_tektonhubdeployment_test.go
Labels: approved, size/XS, lgtm, release-note-none

#2259 chore: fix typo in tekton/README.md
  tekton/README.md
Labels: approved, size/XS, lgtm, kind/documentation, release-note-none, ok-to-test

#2262 [main] add support to configure dashboard air gap image
  pkg/reconciler/common/transformers.go
  pkg/reconciler/kubernetes/tektondashboard/testdata/test-dashboard-transformer-base.yaml
  pkg/reconciler/kubernetes/tektondashboard/testdata/test-dashboard-transformer-updated.yaml
  pkg/reconciler/kubernetes/tektondashboard/transform.go
  pkg/reconciler/kubernetes/tektondashboard/transform_test.go
Labels: kind/feature, approved, lgtm, release-note, size/XXL

#2269 Fix chains default config
  pkg/reconciler/shared/tektonconfig/upgrade/pre_upgrade.go
  pkg/reconciler/shared/tektonconfig/upgrade/pre_upgrade_test.go
  pkg/reconciler/shared/tektonconfig/upgrade/upgrade.go
Labels: approved, lgtm, release-note, size/L

#2266 [main] add air gap image details documentation
  docs/AirGapImageConfiguration.md
  docs/install.md
Labels: approved, lgtm, release-note-none, size/L

#2268 [main] include pratap0007 and PuneetPunamiya as reviewer and approver
  OWNERS
Labels: approved, size/XS, lgtm, release-note-none
