Repository tektoncd/operator, pull requests merged in 2024-08, with the labels that each got.

#2261 Delete tekton hub db migration job pod during uninstall
  pkg/apis/operator/v1alpha1/tektoninstallerset_lifecycle.go
  pkg/apis/operator/v1alpha1/tektoninstallerset_lifecycle_test.go
  pkg/reconciler/kubernetes/tektonhub/tektonhub.go
  pkg/reconciler/kubernetes/tektoninstallerset/client/main_set_test.go
  pkg/reconciler/kubernetes/tektoninstallerset/install.go
  pkg/reconciler/kubernetes/tektoninstallerset/tektoninstallerset.go
Labels: approved, lgtm, size/M, release-note

#2260 Added new fields for signing and storage configs to load secrets from file
  docs/TektonChain.md
  pkg/apis/operator/v1alpha1/tektonchain_types.go
Labels: approved, lgtm, size/S, release-note, ok-to-test

#2285 Update triggers default configmap for FSGroup to handle restricted securityContext for Triggers
  pkg/reconciler/openshift/tektontrigger/extension.go
Labels: approved, size/XS, lgtm, release-note

#2293 Updates tkn image to use latest sha
  charts/tekton-operator/values.yaml
  config/kubernetes/base/operator.yaml
  config/openshift/base/operator.yaml
  operatorhub/kubernetes/config.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/tektoncd-operator.clusterserviceversion.yaml
Labels: approved, lgtm, size/S, release-note

#2281 Operator now supports StepAction alongside Tasks from ecosystem
  Makefile
  cmd/openshift/operator/kodata/tekton-addon/addons/07-ecosystem/role.yaml
  hack/fetch-releases.sh
  hack/openshift/fetch-tektoncd-catalog-tasks.sh
  operatorhub/openshift/config.yaml
  pkg/reconciler/common/testdata/test-replace-stepaction-image.yaml
  pkg/reconciler/common/transformers.go
  pkg/reconciler/common/transformers_test.go
  pkg/reconciler/openshift/tektonaddon/cluster_task.go
  pkg/reconciler/openshift/tektonaddon/cluster_task_versioned.go
  pkg/reconciler/openshift/tektonaddon/community_cluster_tasks.go
  pkg/reconciler/openshift/tektonaddon/const.go
  pkg/reconciler/openshift/tektonaddon/controller.go
  pkg/reconciler/openshift/tektonaddon/resolver_task.go
  pkg/reconciler/openshift/tektonaddon/resolver_task_versioned.go
  pkg/reconciler/openshift/tektonaddon/tektonaddon.go
  pkg/reconciler/openshift/tektonaddon/testdata/test-versioned-resolver-stepaction-expected.yaml
  pkg/reconciler/openshift/tektonaddon/testdata/test-versioned-resolverstepaction-name.yaml
  pkg/reconciler/openshift/tektonaddon/transform.go
  pkg/reconciler/openshift/tektonaddon/transformer.go
  pkg/reconciler/openshift/tektonaddon/transformer_test.go
  pkg/reconciler/shared/tektonconfig/upgrade/pre_upgrade.go
  pkg/reconciler/shared/tektonconfig/upgrade/pre_upgrade_test.go
  pkg/reconciler/shared/tektonconfig/upgrade/upgrade.go
Labels: kind/feature, approved, lgtm, release-note, size/XL
