Repository tektoncd/operator, pull requests merged in 2024-05, with the labels that each got.

#2139 Bump pipelines-as-code to 0.24.6
  components.yaml
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
Labels: approved, size/XS, lgtm, release-note

#2133 Expose feature flags for disabling inline spec in Pipelines
  docs/TektonConfig.md
  docs/TektonPipeline.md
  pkg/apis/operator/v1alpha1/tektonpipeline_defaults.go
  pkg/apis/operator/v1alpha1/tektonpipeline_defaults_test.go
  pkg/apis/operator/v1alpha1/tektonpipeline_types.go
  pkg/apis/operator/v1alpha1/tektonpipeline_validation.go
  pkg/apis/operator/v1alpha1/tektonpipeline_validation_test.go
Labels: kind/feature, approved, lgtm, size/M, release-note

#2144 Deprecate TLSHostnameOverride in TektonResult Properties
  docs/TektonResult.md
  pkg/apis/operator/v1alpha1/tektonresult_defaults.go
  pkg/apis/operator/v1alpha1/tektonresult_defaults_test.go
Labels: approved, lgtm, size/M, release-note, kind/misc

#2121 fix: prevent upgrade failures caused by deleting resources
  pkg/reconciler/kubernetes/tektoninstallerset/install.go
  pkg/reconciler/kubernetes/tektoninstallerset/install_test.go
Labels: approved, lgtm, size/M, release-note, ok-to-test

#2132 [main] adds target namsepace metadata support
  docs/TektonConfig.md
  pkg/apis/operator/v1alpha1/tektonconfig_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/common/targetnamespace.go
  pkg/reconciler/common/targetnamespace_test.go
  pkg/reconciler/kubernetes/tektonhub/tektonhub.go
  pkg/reconciler/kubernetes/tektonpipeline/reconcile.go
  pkg/reconciler/openshift/tektonpipeline/extension.go
  pkg/reconciler/shared/tektonconfig/tektonconfig.go
Labels: approved, lgtm, release-note, size/L

#2143 [main] bump pac package from 0.25.0 to 0.27.0
  go.mod
  go.sum
  pkg/apis/operator/v1alpha1/openshiftpipelinesascode_defaults.go
  pkg/apis/operator/v1alpha1/openshiftpipelinesascode_defaults_test.go
  pkg/apis/operator/v1alpha1/openshiftpipelinesascode_validation.go
  pkg/apis/operator/v1alpha1/tektonconfig_defaults.go
  pkg/apis/operator/v1alpha1/tektonconfig_validation.go
  pkg/reconciler/openshift/openshiftpipelinesascode/testdata/test-additional-pac-cm.yaml
  pkg/reconciler/openshift/openshiftpipelinesascode/transform.go
  vendor/github.com/emicklei/go-restful/v3/CHANGES.md
  vendor/github.com/emicklei/go-restful/v3/README.md
  vendor/github.com/emicklei/go-restful/v3/compress.go
  vendor/github.com/emicklei/go-restful/v3/jsr311.go
  vendor/github.com/openshift-pipelines/pipelines-as-code/pkg/configutil/config.go
  vendor/github.com/openshift-pipelines/pipelines-as-code/pkg/params/settings/config.go
  vendor/github.com/openshift-pipelines/pipelines-as-code/pkg/params/settings/default.go
  vendor/github.com/openshift-pipelines/pipelines-as-code/pkg/params/settings/validation.go
  vendor/github.com/prometheus/common/expfmt/decode.go
  vendor/github.com/prometheus/procfs/Makefile.common
  vendor/github.com/prometheus/procfs/crypto.go
  vendor/github.com/prometheus/procfs/meminfo.go
  vendor/github.com/prometheus/procfs/net_ip_socket.go
  vendor/github.com/prometheus/procfs/net_tls_stat.go
  vendor/github.com/prometheus/procfs/proc_stat.go
  vendor/modules.txt
Labels: approved, lgtm, size/XXL, release-note-none

#2015 Disallow to update targetNamespace in Hub CR
  pkg/apis/operator/v1alpha1/tektonhub_validation.go
  pkg/apis/operator/v1alpha1/tektonhub_validation_test.go
Labels: approved, lgtm, size/M, release-note

#2127 SRVKP-4014: Pull tasks from the tekton ecosystem catalog
  Makefile
  cmd/openshift/operator/kodata/tekton-addon/addons/07-ecosystem/role.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/07-ecosystem/rolebinding.yaml
  config/crs/openshift/config/all/operator_v1alpha1_config_cr.yaml
  docs/TektonAddon.md
  docs/TektonConfig.md
  hack/fetch-releases.sh
  hack/openshift/fetch-tektoncd-catalog-tasks.sh
  pkg/apis/operator/v1alpha1/const.go
  pkg/apis/operator/v1alpha1/tektonaddon_default_test.go
  pkg/apis/operator/v1alpha1/tektonconfig_default_test.go
  pkg/reconciler/openshift/tektonaddon/const.go
  pkg/reconciler/openshift/tektonaddon/controller.go
  pkg/reconciler/openshift/tektonaddon/resolverTask.go
  pkg/reconciler/openshift/tektonaddon/tektonaddon.go
Labels: approved, lgtm, release-note, ok-to-test, size/L

#2152 [0.71.x] update minor version and sync images
  charts/tekton-operator/Chart.yaml
  charts/tekton-operator/templates/kubernetes-crds.yaml
  charts/tekton-operator/templates/openshift-crds.yaml
  cmd/kubernetes/operator/kodata/webhook/webhook.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/buildah/buildah-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-dotnet/s2i-dotnet-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-go/s2i-go-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-java/s2i-java-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-nodejs/s2i-nodejs-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-perl/s2i-perl-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-php/s2i-php-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-python/s2i-python-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-ruby/s2i-ruby-task.yaml
  cmd/openshift/operator/kodata/webhook/webhook.yaml
  config/base/300-operator_v1alpha1_chain_crd.yaml
  config/base/300-operator_v1alpha1_config_crd.yaml
  config/base/300-operator_v1alpha1_hub_crd.yaml
  config/base/300-operator_v1alpha1_installer_set_crd.yaml
  config/base/300-operator_v1alpha1_manualapprovalgate_crd.yaml
  config/base/300-operator_v1alpha1_pipeline_crd.yaml
  config/base/300-operator_v1alpha1_result_crd.yaml
  config/base/300-operator_v1alpha1_trigger_crd.yaml
  config/base/config-info.yaml
  config/base/operator.yaml
  config/kubernetes/base/300-operator_v1alpha1_dashboard_crd.yaml
  config/kubernetes/base/operator.yaml
  config/kubernetes/base/operator_service.yaml
  config/kubernetes/base/webhook.yaml
  config/openshift/base/300-operator_v1alpha1_addon_crd.yaml
  config/openshift/base/300-operator_v1alpha1_openshiftpipelinesascode_crd.yaml
  config/openshift/base/operator.yaml
  config/openshift/base/operator_service.yaml
  config/openshift/base/webhook.yaml
  config/webhooks/webhook-service.yaml
  config/webhooks/webhook.yaml
  operatorhub/openshift/config.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
  pkg/reconciler/openshift/tektonaddon/consolecli.go
Labels: approved, lgtm, release-note-none, size/L

#2155 Update Makefile to add manual approval gate in clean-manifest target
  Makefile
  hack/fetch-releases.sh
Labels: approved, size/XS, lgtm, release-note

#2157 Adds docs for Manual Approval Gate
  docs/ManualApprovalGate.md
Labels: approved, lgtm, size/M, release-note

#2159 [main] bump go version to 1.21 in GH actions
  .github/workflows/bump-payload-on-main.yaml
  .github/workflows/bump-payload-on-releases.yaml
Labels: approved, size/XS, lgtm, release-note-none

#2158 Fix broken link to OpenShift Pipeline documentation
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml.tmpl
Labels: approved, size/XS, lgtm, release-note-none, ok-to-test

#2164 Move clustertask and clustertriggerbinding role to component
  cmd/openshift/operator/kodata/openshift/pipelines-rbac/03-clustertasks-view-permission.yaml
  cmd/openshift/operator/kodata/openshift/triggers-rbac/01-clustertriggerbindings-view-permission.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/01-clustertriggerbindings/cluster-role.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/01-clustertriggerbindings/cluster-rolebinding.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/cluster-role.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/cluster-rolebinding.yaml
  hack/fetch-releases.sh
Labels: approved, lgtm, release-note, size/L

#2163 Adds Manual Approval Gate env for openshift
  operatorhub/openshift/config.yaml
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml.tmpl
Labels: approved, lgtm, size/M, release-note

#2168 Fix pac config not getting added
  pkg/apis/operator/v1alpha1/openshiftpipelinesascode_defaults.go
  pkg/apis/operator/v1alpha1/openshiftpipelinesascode_validation.go
  pkg/reconciler/openshift/openshiftpipelinesascode/transform.go
  pkg/reconciler/openshift/openshiftpipelinesascode/transform_test.go
Labels: approved, lgtm, size/M, release-note

#2122 add jkhelil to owners file
  OWNERS
Labels: approved, size/XS, lgtm, release-note, ok-to-test

#2180 [main] hide manualapprovalgate cr from openshift console UI
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml.tmpl
Labels: approved, size/XS, lgtm, release-note-none, platform/openshift

#2178 [main] fix confiMap transformer to include string pointer's empty value
  pkg/reconciler/common/transformers.go
  pkg/reconciler/common/transformers_test.go
Labels: kind/bug, approved, lgtm, size/M, release-note-none
