Repository tektoncd/operator, pull requests merged in 2024-09, with the labels that each got.

#2298 Fix TektonChain docs
  docs/TektonChain.md
Labels: approved, lgtm, size/S, release-note

#2303 Fix installerset issue for resolver task and stepaction
  pkg/reconciler/openshift/tektonaddon/resolver_task.go
  pkg/reconciler/openshift/tektonaddon/resolver_task_versioned.go
Labels: approved, lgtm, size/S, release-note

#2294 Includes RBAC for results api to query openshift loki
  cmd/openshift/operator/kodata/static/tekton-results/logs-rbac/rbac.yaml
  config/crs/kubernetes/result/operator_v1alpha1_result_cr.yaml
  config/crs/openshift/result/operator_v1alpha1_result_cr.yaml
  pkg/reconciler/openshift/tektonresult/extension.go
  pkg/reconciler/openshift/tektonresult/extension_test.go
  pkg/reconciler/openshift/tektonresult/testdata/static/tekton-results/logs-rbac/rbac.yaml
Labels: kind/feature, approved, lgtm, release-note, ok-to-test, size/L, platform/openshift

#2308 fix(pipelines-scc): add ephemeral volumes
  cmd/openshift/operator/kodata/openshift/00-prereconcile/openshift-pipelines-scc.yaml
Labels: kind/feature, approved, size/XS, lgtm, release-note, ok-to-test

#2316 Update version for all the ecosystem tasks
  hack/openshift/fetch-tektoncd-catalog-tasks.sh
Labels: approved, lgtm, size/M, release-note

#2324 Bump Buildah image sha
  operatorhub/openshift/config.yaml
Labels: approved, size/XS, lgtm, release-note

#2328 increase rbac rbacMaxConcurrentCalls to 20
  pkg/reconciler/openshift/tektonconfig/rbac.go
Labels: approved, size/XS, lgtm, release-note

#2310 Add LokiStack Automation for TektonResult
  docs/TektonResult.md
  pkg/apis/operator/v1alpha1/tektonresult_types.go
  pkg/apis/operator/v1alpha1/tektonresult_validation.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/kubernetes/tektonresult/tektonresult.go
  pkg/reconciler/kubernetes/tektonresult/testdata/api-config.yaml
  pkg/reconciler/kubernetes/tektonresult/transform.go
  pkg/reconciler/kubernetes/tektonresult/transform_test.go
  pkg/reconciler/openshift/tektonresult/extension.go
  pkg/reconciler/openshift/tektonresult/extension_test.go
Labels: approved, lgtm, release-note, size/L

#2335 [SRVKP-6365] Fix to versionedResolverTasks & stepactions, bump ecosystem versions
  hack/openshift/fetch-tektoncd-catalog-tasks.sh
  pkg/reconciler/openshift/tektonaddon/tektonaddon.go
Labels: approved, lgtm, size/S, release-note-none, ok-to-test

#2338 Add resolverStepActions flag to enable/disable stepaction
  config/crs/openshift/config/all/operator_v1alpha1_config_cr.yaml
  docs/TektonAddon.md
  docs/TektonConfig.md
  pkg/apis/operator/v1alpha1/const.go
  pkg/apis/operator/v1alpha1/tektonaddon_default_test.go
  pkg/apis/operator/v1alpha1/tektonconfig_default_test.go
  pkg/reconciler/openshift/tektonaddon/tektonaddon.go
Labels: approved, lgtm, size/S, release-note

#2340 Update image sha to latest
  operatorhub/openshift/config.yaml
Labels: approved, lgtm, size/S, release-note

#2342 move openshift samples tasksnippets to tekton.dev/v1
  cmd/openshift/operator/kodata/tekton-addon/optional/samples/tasksnippets/buildah-task-snippet.yaml
  cmd/openshift/operator/kodata/tekton-addon/optional/samples/tasksnippets/openshift-client-task-snippet.yaml
  cmd/openshift/operator/kodata/tekton-addon/optional/samples/tasksnippets/s2i-go-task-snippet.yaml
  cmd/openshift/operator/kodata/tekton-addon/optional/samples/tasksnippets/s2i-java-task-snippet.yaml
  cmd/openshift/operator/kodata/tekton-addon/optional/samples/tasksnippets/s2i-nodejs-task-snippet.yaml
  cmd/openshift/operator/kodata/tekton-addon/optional/samples/tasksnippets/s2i-python-task-snippet.yaml
Labels: approved, lgtm, size/S, release-note, platform/openshift

#2346 Added Clusterrole for results API and Loki RBAC
  cmd/openshift/operator/kodata/static/tekton-results/logs-rbac/rbac.yaml
Labels: kind/bug, approved, lgtm, size/S, release-note-none

#2344 [main] ignore enable-tekton-oci-bundles feature flag
  docs/TektonConfig.md
  docs/TektonPipeline.md
  pkg/apis/operator/v1alpha1/tektonconfig_default_test.go
  pkg/apis/operator/v1alpha1/tektonpipeline_defaults.go
  pkg/apis/operator/v1alpha1/tektonpipeline_defaults_test.go
  pkg/apis/operator/v1alpha1/tektonpipeline_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/common/transformers_test.go
  pkg/reconciler/kubernetes/tektonpipeline/testdata/tektonpipeline-feature-flags-base.yaml
  pkg/reconciler/kubernetes/tektonpipeline/transform.go
  pkg/reconciler/kubernetes/tektonpipeline/transform_test.go
Labels: approved, lgtm, release-note, size/L

#2350 Pin images used in the release pipeline
  tekton/build-publish-images-manifests.yaml
  tekton/operator-release-pipeline.yaml
  tekton/task-fetch-components.yaml
Labels: approved, lgtm, size/S, release-note, kind/misc

#2353 Remove TLS Secret Check for Results API
  pkg/reconciler/kubernetes/tektonresult/tektonresult.go
  pkg/reconciler/openshift/tektonresult/extension.go
  pkg/reconciler/openshift/tektonresult/extension_test.go
  pkg/reconciler/openshift/tektonresult/testdata/api-service.yaml
Labels: kind/feature, approved, lgtm, size/M, release-note

#2354 Add QueryLimit & QueryParams Fields for ResultsAPI
  docs/TektonResult.md
  pkg/apis/operator/v1alpha1/tektonresult_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/kubernetes/tektonresult/testdata/api-config.yaml
  pkg/reconciler/kubernetes/tektonresult/transform_test.go
Labels: approved, lgtm, size/S, release-note-none, kind/misc
