Repository tektoncd/operator, pull requests merged in 2024-02, with the labels that each got.

#1959 [main] update pipelines console image in openshift
  operatorhub/openshift/config.yaml
Labels: approved, size/XS, lgtm, release-note-none

#1920 Adds logic to create configMap of `hub-info` in targetNamespace
  hack/fetch-releases.sh
  pkg/reconciler/kubernetes/tektonhub/tektonhub.go
Labels: approved, lgtm, size/S, release-note

#1958 Update the volumes of pipelines-scc to add support for CSI.
  cmd/openshift/operator/kodata/openshift/00-prereconcile/openshift-pipelines-scc.yaml
Labels: kind/feature, approved, size/XS, lgtm, release-note

#1966 Add Transformer for Watcher Container Env
  pkg/reconciler/common/testdata/test-replace-env-in-result-deployment.yaml
  pkg/reconciler/common/transformers.go
  pkg/reconciler/common/transformers_test.go
Labels: kind/bug, approved, lgtm, size/M, release-note-none

#1971 [main] bump gh actions go version
  .github/workflows/bump-payload-on-main.yaml
  .github/workflows/bump-payload-on-releases.yaml
Labels: approved, size/XS, lgtm, release-note-none

#1967 Add support for deploying additional pac controller
  docs/OpenShiftPipelinesAsCode.md
  docs/TektonConfig.md
  pkg/apis/operator/v1alpha1/const.go
  pkg/apis/operator/v1alpha1/openshiftpipelinesascode_defaults.go
  pkg/apis/operator/v1alpha1/openshiftpipelinesascode_defaults_test.go
  pkg/apis/operator/v1alpha1/openshiftpipelinesascode_lifecycle.go
  pkg/apis/operator/v1alpha1/openshiftpipelinesascode_lifecycle_test.go
  pkg/apis/operator/v1alpha1/openshiftpipelinesascode_types.go
  pkg/apis/operator/v1alpha1/openshiftpipelinesascode_validation.go
  pkg/apis/operator/v1alpha1/openshiftpipelinesascode_validation_test.go
  pkg/apis/operator/v1alpha1/tektonconfig_defaults.go
  pkg/apis/operator/v1alpha1/tektonconfig_validation.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/kubernetes/tektoninstallerset/client/create.go
  pkg/reconciler/kubernetes/tektoninstallerset/client/create_test.go
  pkg/reconciler/kubernetes/tektoninstallerset/client/custom_versioned_clustertask.go
  pkg/reconciler/kubernetes/tektoninstallerset/client/list.go
  pkg/reconciler/kubernetes/tektoninstallerset/client/main_set.go
  pkg/reconciler/kubernetes/tektoninstallerset/client/pre_post_custom_set.go
  pkg/reconciler/openshift/openshiftpipelinesascode/controller.go
  pkg/reconciler/openshift/openshiftpipelinesascode/pipelinerun_templates.go
  pkg/reconciler/openshift/openshiftpipelinesascode/reconcile.go
  pkg/reconciler/openshift/openshiftpipelinesascode/testdata/test-additional-pac-cm.yaml
  pkg/reconciler/openshift/openshiftpipelinesascode/testdata/test-expected-additional-pac-cm.yaml
  pkg/reconciler/openshift/openshiftpipelinesascode/testdata/test-expected-additional-pac-dep.yaml
  pkg/reconciler/openshift/openshiftpipelinesascode/testdata/test-expected-additional-pac-route.yaml
  pkg/reconciler/openshift/openshiftpipelinesascode/testdata/test-filter-manifest.yaml
  pkg/reconciler/openshift/openshiftpipelinesascode/transform.go
  pkg/reconciler/openshift/openshiftpipelinesascode/transform_test.go
  pkg/reconciler/openshift/openshiftpipelinesascode/update_route_in_configmap.go
  pkg/reconciler/openshift/tektonaddon/clustertTask.go
  pkg/reconciler/openshift/tektonaddon/clustertTaskVersioned.go
  pkg/reconciler/openshift/tektonaddon/communityClusterTasks.go
  pkg/reconciler/openshift/tektonaddon/consolecli.go
  pkg/reconciler/openshift/tektonaddon/openshiftConsole.go
  pkg/reconciler/openshift/tektonaddon/pipelinetemplate.go
  pkg/reconciler/openshift/tektonaddon/triggers.go
  pkg/reconciler/openshift/tektonconfig/extension/pipelinesascode.go
  pkg/reconciler/openshift/tektonconfig/extension/pipelinesascode_test.go
  test/e2e/openshift/openshiftpipelinesascode_test.go
  test/resources/deployment.go
  test/resources/openshiftpipelinesascode.go
  test/utils/clients.go
  test/utils/names.go
Labels: approved, lgtm, release-note, size/XXL

#1961 Add Internal DB for OpenShift
  cmd/openshift/operator/kodata/static/tekton-results/internal-db/db.yaml
  docs/TektonResult.md
  hack/fetch-releases.sh
  pkg/apis/operator/v1alpha1/tektonresult_lifecycle.go
  pkg/apis/operator/v1alpha1/tektonresult_lifecycle_test.go
  pkg/reconciler/kubernetes/tektonresult/tektonresult.go
  pkg/reconciler/openshift/tektonresult/extension.go
Labels: approved, lgtm, release-note, size/L

#1973 [main] bump results and dashboard
  components.yaml
Labels: approved, size/XS, lgtm, release-note-none

#1947 Add OpenShift PostReconcile Extension for Results Route RBAC
  cmd/openshift/operator/kodata/static/tekton-results/route-rbac/rbac.yaml
  pkg/apis/operator/v1alpha1/tektonresult_lifecycle.go
  pkg/apis/operator/v1alpha1/tektonresult_lifecycle_test.go
  pkg/apis/operator/v1alpha1/tektonresult_types.go
  pkg/reconciler/kubernetes/tektonresult/tektonresult.go
  pkg/reconciler/openshift/tektonresult/extension.go
  pkg/reconciler/openshift/tektonresult/extension_test.go
  pkg/reconciler/openshift/tektonresult/testdata/static/tekton-results/route-rbac/rbac.yaml
Labels: kind/feature, approved, lgtm, release-note, size/L

#1865 Fix to deploy TektonHub in custom namespace
  pkg/reconciler/common/targetnamespace.go
  pkg/reconciler/common/targetnamespace_test.go
Labels: approved, lgtm, size/M, release-note

#1950 Update buildah task to support RHEL entitlement
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/buildah/buildah-task.yaml
Labels: approved, lgtm, size/S, release-note

#1975 [v0.70.x] add v0.70.0 labels and bump cli version
  charts/tekton-operator/Chart.yaml
  charts/tekton-operator/templates/kubernetes-crds.yaml
  charts/tekton-operator/templates/openshift-crds.yaml
  cmd/kubernetes/operator/kodata/webhook/webhook.yaml
  cmd/openshift/operator/kodata/cabundles/config-service-cabundle.yaml
  cmd/openshift/operator/kodata/cabundles/config-trusted-cabundle.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/buildah/buildah-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-dotnet/s2i-dotnet-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-go/s2i-go-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-java/s2i-java-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-nodejs/s2i-nodejs-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-perl/s2i-perl-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-php/s2i-php-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-python/s2i-python-task.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/s2i-ruby/s2i-ruby-task.yaml
  cmd/openshift/operator/kodata/webhook/webhook.yaml
  config/base/300-operator_v1alpha1_chain_crd.yaml
  config/base/300-operator_v1alpha1_config_crd.yaml
  config/base/300-operator_v1alpha1_hub_crd.yaml
  config/base/300-operator_v1alpha1_installer_set_crd.yaml
  config/base/300-operator_v1alpha1_pipeline_crd.yaml
  config/base/300-operator_v1alpha1_result_crd.yaml
  config/base/300-operator_v1alpha1_trigger_crd.yaml
  config/base/config-info.yaml
  config/base/config-leader-election.yaml
  config/base/config-logging.yaml
  config/base/operator.yaml
  config/base/tekton-config-defaults.yaml
  config/kubernetes/base/300-operator_v1alpha1_dashboard_crd.yaml
  config/kubernetes/base/operator.yaml
  config/kubernetes/base/operator_service.yaml
  config/kubernetes/base/webhook.yaml
  config/openshift/base/300-operator_v1alpha1_addon_crd.yaml
  config/openshift/base/300-operator_v1alpha1_openshiftpipelinesascode_crd.yaml
  config/openshift/base/operator.yaml
  config/openshift/base/operator_service.yaml
  config/openshift/base/webhook.yaml
  config/webhooks/webhook-config-leader-election.yaml
  config/webhooks/webhook-service.yaml
  config/webhooks/webhook.yaml
  operatorhub/openshift/config.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
  pkg/reconciler/openshift/tektonaddon/consolecli.go
Labels: approved, lgtm, release-note-none, size/L

#1980 [main] initialize labels of old object to avoid nil error
  pkg/reconciler/openshift/tektonconfig/extension/addon.go
  pkg/reconciler/openshift/tektonconfig/extension/pipelinesascode.go
  pkg/reconciler/shared/tektonconfig/chain/chain.go
  pkg/reconciler/shared/tektonconfig/pipeline/pipeline.go
  pkg/reconciler/shared/tektonconfig/trigger/trigger.go
Labels: approved, lgtm, size/S, release-note-none

#1987 Lower down the threshold for scaling operator proxy webhook
  cmd/kubernetes/operator/kodata/webhook/webhook.yaml
  cmd/openshift/operator/kodata/webhook/webhook.yaml
Labels: approved, size/XS, lgtm, release-note

#1986 Implement Result MarkPreReconcilerFailed to fix upgrade
  pkg/apis/operator/v1alpha1/tektonresult_types.go
Labels: kind/bug, approved, size/XS, lgtm, release-note-none

#1988 [main] update console plugin displayName
  cmd/openshift/operator/kodata/static/tekton-config/00-console-plugin/pipeline_console_plugin.yaml
  pkg/reconciler/openshift/tektonconfig/testdata/postreconcile_manifest/test_post_manifest.yaml
Labels: approved, size/XS, lgtm, release-note-none

#1999 Adds recently added pipelinerun and builder artifacts to chains spec
  docs/TektonChain.md
  pkg/apis/operator/v1alpha1/tektonchain_types.go
  pkg/apis/operator/v1alpha1/tektonchain_validation.go
  pkg/apis/operator/v1alpha1/tektonchain_validation_test.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
Labels: kind/feature, approved, lgtm, size/M, release-note

#2004 [main] fix HPA maxReplicas update and disable HPA creation via options
  docs/TektonConfig.md
  pkg/reconciler/common/testdata/test-additional-options-base-hpa.yaml
  pkg/reconciler/common/testdata/test-additional-options-test-hpa.yaml
  pkg/reconciler/common/transformer_additional_options.go
  pkg/reconciler/common/transformer_additional_options_test.go
Labels: kind/bug, approved, lgtm, release-note, size/L

#2009 [0.70.x] update openshift component version and image shas
  config/openshift/base/operator.yaml
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
  pkg/reconciler/openshift/tektonaddon/consolecli.go
Labels: approved, lgtm, size/S, release-note-none

#2008 Fix Conflict between Results PreReconciler and Reconciler
  pkg/reconciler/kubernetes/tektonresult/tektonresult.go
Labels: kind/bug, approved, lgtm, size/M, release-note

#2007 Fix Results version not reflecting in certain flow
  pkg/reconciler/kubernetes/tektonresult/tektonresult.go
Labels: kind/bug, approved, lgtm, size/S, release-note-none

#2003 Fix the results reconciler's manifest reference
  pkg/reconciler/common/transformers.go
  pkg/reconciler/kubernetes/tektonresult/controller.go
  pkg/reconciler/kubernetes/tektonresult/filter.go
  pkg/reconciler/kubernetes/tektonresult/filter_test.go
  pkg/reconciler/kubernetes/tektonresult/installerset.go
  pkg/reconciler/kubernetes/tektonresult/tektonresult.go
  pkg/reconciler/kubernetes/tektonresult/transform.go
Labels: kind/bug, approved, lgtm, size/M, release-note

#1996 Remove --no-cache from buildah as no longer necessary
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/buildah/buildah-task.yaml
Labels: approved, size/XS, lgtm, release-note, ok-to-test

#2019 Removed Newline in Buildah Results
  cmd/openshift/operator/kodata/tekton-addon/addons/02-clustertasks/source_local/buildah/buildah-task.yaml
Labels: approved, size/XS, lgtm, release-note, ok-to-test

#2022 Fix filter and Transform for TektonResult
  pkg/reconciler/kubernetes/tektonresult/filter.go
  pkg/reconciler/kubernetes/tektonresult/filter_test.go
  pkg/reconciler/kubernetes/tektonresult/transform.go
Labels: kind/bug, approved, lgtm, size/S, release-note-none

#2030 Revert "Added filesystem-custom-path to allowed x509 fulcio providers"
  pkg/apis/operator/v1alpha1/tektonchain_validation.go
Labels: approved, size/XS, lgtm, release-note

#2034 Bump tektoncd/pipeline to v0.57.0
  go.mod
  go.sum
  pkg/apis/operator/v1alpha1/tektonpipeline_defaults.go
  pkg/apis/operator/v1alpha1/tektonpipeline_defaults_test.go
  vendor/github.com/google/cel-go/cel/inlining.go
  vendor/github.com/google/cel-go/common/types/int.go
  vendor/github.com/google/cel-go/common/types/list.go
  vendor/github.com/google/cel-go/common/types/overflow.go
  vendor/github.com/google/cel-go/common/types/provider.go
  vendor/github.com/google/cel-go/common/types/string.go
  vendor/github.com/google/cel-go/common/types/uint.go
  vendor/github.com/google/cel-go/interpreter/attributes.go
  vendor/github.com/google/go-containerregistry/pkg/v1/tarball/image.go
  vendor/github.com/opencontainers/image-spec/specs-go/v1/mediatype.go
  vendor/github.com/opencontainers/image-spec/specs-go/version.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/config/default.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/config/feature_flags.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/errors/errors.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1/openapi_generated.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1/swagger.json
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1/taskrun_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/taskrun_conversion.go
  vendor/go.opentelemetry.io/otel/CHANGELOG.md
  vendor/go.opentelemetry.io/otel/CODEOWNERS
  vendor/go.opentelemetry.io/otel/CONTRIBUTING.md
  vendor/go.opentelemetry.io/otel/attribute/set.go
  vendor/go.opentelemetry.io/otel/sdk/resource/auto.go
  vendor/go.opentelemetry.io/otel/sdk/resource/container.go
  vendor/go.opentelemetry.io/otel/sdk/resource/resource.go
  vendor/go.opentelemetry.io/otel/sdk/trace/batch_span_processor.go
  vendor/go.opentelemetry.io/otel/sdk/trace/provider.go
  vendor/go.opentelemetry.io/otel/sdk/version.go
  vendor/go.opentelemetry.io/otel/version.go
  vendor/go.opentelemetry.io/otel/versions.yaml
  vendor/google.golang.org/grpc/internal/transport/controlbuf.go
  vendor/google.golang.org/grpc/internal/transport/http2_client.go
  vendor/google.golang.org/grpc/internal/transport/http2_server.go
  vendor/google.golang.org/grpc/version.go
  vendor/modules.txt
Labels: approved, lgtm, release-note, size/XL
