Repository tektoncd/operator, pull requests merged in 2024-01, with the labels that each got.

#1909 Added filesystem-custom-path to allowed x509 fulcio providers
  pkg/apis/operator/v1alpha1/tektonchain_validation.go
Labels: approved, size/XS, lgtm, release-note, ok-to-test

#1913 [v0.69.x] update kubernetes operatorhub manifests
  operatorhub/kubernetes/manifests/bases/tektoncd-operator.clusterserviceversion.template.yaml
  operatorhub/kubernetes/release-artifacts/bundle.Dockerfile
  operatorhub/kubernetes/release-artifacts/bundle/manifests/config-logging_v1_configmap.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/operator.tekton.dev_tektonchains.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/operator.tekton.dev_tektonconfigs.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/operator.tekton.dev_tektondashboards.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/operator.tekton.dev_tektonhubs.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/operator.tekton.dev_tektoninstallersets.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/operator.tekton.dev_tektonpipelines.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/operator.tekton.dev_tektonresults.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/operator.tekton.dev_tektontriggers.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/tekton-config-defaults_v1_configmap.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/tekton-operator-info_rbac.authorization.k8s.io_v1_role.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/tekton-operator-info_v1_configmap.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/tekton-operator-webhook_v1_service.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/tekton-operator_v1_service.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/tekton-result-read-role_rbac.authorization.k8s.io_v1_clusterrole.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/tekton-result-read-rolebinding_rbac.authorization.k8s.io_v1_clusterrolebinding.yaml
  operatorhub/kubernetes/release-artifacts/bundle/manifests/tektoncd-operator.clusterserviceversion.yaml
  operatorhub/kubernetes/release-artifacts/bundle/metadata/annotations.yaml
Labels: approved, lgtm, release-note-none, size/L

#1915 fix(chart): helm-git support
  .github/workflows/helm-release.yaml
  .yamllint
  charts/tekton-operator/.helmignore
  charts/tekton-operator/Chart.yaml
  charts/tekton-operator/README.md
  charts/tekton-operator/templates/NOTES.txt
  charts/tekton-operator/templates/_helpers.tpl
  charts/tekton-operator/templates/config.yaml
  charts/tekton-operator/templates/deployment.yaml
  charts/tekton-operator/templates/kubernetes-crds.yaml
  charts/tekton-operator/templates/kubernetes-rbac.yaml
  charts/tekton-operator/templates/openshift-crds.yaml
  charts/tekton-operator/templates/openshift-rbac.yaml
  charts/tekton-operator/templates/secret.yaml
  charts/tekton-operator/templates/service.yaml
  charts/tekton-operator/values.yaml
Labels: approved, lgtm, size/S, release-note, ok-to-test

#1930 .github/workflows: skip some workflows on forks
  .github/workflows/bump-payload-on-main.yaml
  .github/workflows/bump-payload-on-releases.yaml
  .github/workflows/helm-release.yaml
Labels: approved, size/XS, lgtm, release-note-none

#1931 [v0.67.x] update operator patch version
  chart/Chart.yaml
  chart/templates/kubernetes-crds.yaml
  chart/templates/openshift-crds.yaml
  cmd/kubernetes/operator/kodata/webhook/webhook.yaml
  cmd/openshift/operator/kodata/webhook/webhook.yaml
  config/base/300-operator_v1alpha1_chain_crd.yaml
  config/base/300-operator_v1alpha1_config_crd.yaml
  config/base/300-operator_v1alpha1_hub_crd.yaml
  config/base/300-operator_v1alpha1_installer_set_crd.yaml
  config/base/300-operator_v1alpha1_pipeline_crd.yaml
  config/base/300-operator_v1alpha1_result_crd.yaml
  config/base/300-operator_v1alpha1_trigger_crd.yaml
  config/base/config-info.yaml
  config/base/operator.yaml
  config/kubernetes/base/300-operator_v1alpha1_dashboard_crd.yaml
  config/kubernetes/base/operator.yaml
  config/kubernetes/base/operator_service.yaml
  config/kubernetes/base/webhook.yaml
  config/openshift/base/300-operator_v1alpha1_addon_crd.yaml
  config/openshift/base/300-operator_v1alpha1_openshiftpipelinesascode_crd.yaml
  config/openshift/base/operator_service.yaml
  config/openshift/base/webhook.yaml
  config/webhooks/webhook-service.yaml
  config/webhooks/webhook.yaml
Labels: approved, lgtm, release-note-none, size/L

#1934 [v0.67.x] update pipeline pkg to v0.47.6
  go.mod
  go.sum
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/customrun_types.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/run_interface.go
  vendor/github.com/tektoncd/pipeline/pkg/apis/pipeline/v1beta1/taskrun_types.go
  vendor/modules.txt
Labels: approved, lgtm, size/S, release-note-none

#1929 Ensure Tekton* CR get the `operatorVersion` label.
  pkg/reconciler/kubernetes/tektonpipeline/reconcile.go
  pkg/reconciler/openshift/tektonconfig/extension.go
  pkg/reconciler/openshift/tektonconfig/extension/addon.go
  pkg/reconciler/openshift/tektonconfig/extension/addon_test.go
  pkg/reconciler/openshift/tektonconfig/extension/pipelinesascode.go
  pkg/reconciler/openshift/tektonconfig/extension/pipelinesascode_test.go
  pkg/reconciler/shared/tektonconfig/chain/chain.go
  pkg/reconciler/shared/tektonconfig/chain/chain_test.go
  pkg/reconciler/shared/tektonconfig/pipeline/pipeline.go
  pkg/reconciler/shared/tektonconfig/pipeline/pipeline_test.go
  pkg/reconciler/shared/tektonconfig/tektonconfig.go
  pkg/reconciler/shared/tektonconfig/trigger/trigger.go
  pkg/reconciler/shared/tektonconfig/trigger/trigger_test.go
Labels: approved, lgtm, release-note-none, size/L

#1936 [main] include webhook podname in charts deployment
  charts/tekton-operator/templates/deployment.yaml
Labels: kind/bug, approved, size/XS, lgtm, release-note-none

#1937 [v0.69.x] include webhook pod name in charts deployment
  chart/templates/deployment.yaml
Labels: kind/bug, approved, size/XS, lgtm, release-note-none

#1935 Add config leader election configmaps
  cmd/kubernetes/operator/kodata/webhook/webhook.yaml
  cmd/openshift/operator/kodata/webhook/webhook.yaml
  config/base/config-leader-election.yaml
  config/base/kustomization.yaml
  config/kubernetes/base/operator.yaml
  config/kubernetes/base/webhook.yaml
  config/openshift/base/operator.yaml
  config/openshift/base/webhook.yaml
  config/webhooks/kustomization.yaml
  config/webhooks/webhook-config-leader-election.yaml
Labels: kind/feature, approved, lgtm, release-note, size/L

#1939 [main] fix intendation issue in charts
  charts/tekton-operator/templates/deployment.yaml
Labels: approved, size/XS, lgtm, release-note-none

#1940 Bump github.com/cloudflare/circl from 1.3.5 to 1.3.7
  go.mod
  go.sum
  vendor/github.com/coreos/go-oidc/v3/oidc/oidc.go
  vendor/github.com/secure-systems-lab/go-securesystemslib/dsse/sign.go
  vendor/github.com/secure-systems-lab/go-securesystemslib/signerverifier/ecdsa.go
  vendor/github.com/secure-systems-lab/go-securesystemslib/signerverifier/ed25519.go
  vendor/github.com/secure-systems-lab/go-securesystemslib/signerverifier/rsa.go
  vendor/github.com/secure-systems-lab/go-securesystemslib/signerverifier/signerverifier.go
  vendor/github.com/secure-systems-lab/go-securesystemslib/signerverifier/utils.go
  vendor/github.com/sigstore/sigstore/pkg/signature/dsse/multidsse.go
  vendor/modules.txt
Labels: approved, lgtm, release-note, size/L

#1941 Bump golangci-lint and fix make test
  Makefile
Labels: approved, size/XS, lgtm, release-note

#1895 [main] manage pipeline console plugin deployment on openshift
  cmd/openshift/operator/kodata/static/tekton-config/00-console-plugin/pipeline_console_plugin.yaml
  config/openshift/base/role.yaml
  operatorhub/openshift/config.yaml
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
  pkg/reconciler/common/testdata/test-replace-namespace.yaml
  pkg/reconciler/common/transformers.go
  pkg/reconciler/common/transformers_test.go
  pkg/reconciler/openshift/tektonconfig/console_plugin_reconciler.go
  pkg/reconciler/openshift/tektonconfig/console_plugin_reconciler_test.go
  pkg/reconciler/openshift/tektonconfig/extension.go
  pkg/reconciler/openshift/tektonconfig/testdata/postreconcile_manifest/test_post_manifest.yaml
Labels: kind/feature, approved, lgtm, size/XL, release-note-none

#1944 [main] removes outdated text
  pkg/reconciler/kubernetes/tektonpipeline/transform.go
Labels: approved, size/XS, lgtm, release-note-none

#1942 [main] add hpa under options and support pod template labels and annotations
  docs/TektonConfig.md
  pkg/apis/operator/v1alpha1/additional_options.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/common/testdata/test-additional-options-base-hpa.yaml
  pkg/reconciler/common/testdata/test-additional-options-test-deployment.yaml
  pkg/reconciler/common/testdata/test-additional-options-test-hpa.yaml
  pkg/reconciler/common/testdata/test-additional-options-test-statefulsets.yaml
  pkg/reconciler/common/transformer_additional_options.go
  pkg/reconciler/common/transformer_additional_options_test.go
Labels: kind/feature, approved, lgtm, release-note, size/XL

#1948 Fix servicemonitor selectorLabels indentation in chart
  charts/tekton-operator/templates/service.yaml
Labels: approved, size/XS, lgtm, release-note, ok-to-test

#1951 Expose which controllers to install through values
  charts/tekton-operator/templates/deployment.yaml
  charts/tekton-operator/values.yaml
Labels: approved, size/XS, lgtm, release-note, ok-to-test

#1848 [main] ignore nested struct in AddConfigMapValues transformer
  pkg/reconciler/common/testdata/test-add-configmap-values.yaml
  pkg/reconciler/common/transformers.go
  pkg/reconciler/common/transformers_test.go
Labels: approved, lgtm, release-note-none, size/L
