Repository tektoncd/operator, pull requests merged in 2025-09, with the labels that each got.

#2875 add global opt out option disable proxy webhook
  docs/Proxy.md
  pkg/reconciler/common/initcontroller.go
Labels: approved, lgtm, size/S, release-note

#2862 replace container args by key and avoid duplicates
  pkg/reconciler/common/testdata/test-additional-options-args-dedup-and-replace.yaml
  pkg/reconciler/common/testdata/test-additional-options-args-pair-form-update-preserve-style.yaml
  pkg/reconciler/common/transformer_additional_options.go
  pkg/reconciler/common/transformer_additional_options_test.go
Labels: kind/bug, approved, lgtm, release-note, size/XL, ok-to-test

#2885 Updates postgres version for Results and Hub
  config/openshift/base/operator.yaml
  hack/openshift/update-image-sha.sh
  operatorhub/openshift/config.yaml
Labels: approved, size/XS, lgtm, release-note

#2886 Update image to latest sha
  config/openshift/base/operator.yaml
  operatorhub/openshift/config.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
Labels: approved, lgtm, size/M, release-note

#2897 revert hub bump
  components.yaml
  operatorhub/openshift/manifests/bases/openshift-pipelines-operator-rh.clusterserviceversion.template.yaml
Labels: approved, size/XS, lgtm, release-note

#2900 [release-v0.77.x] Bump pac to 0.37.0
  go.mod
  go.sum
  pkg/apis/operator/v1alpha1/openshiftpipelinesascode_defaults.go
  pkg/apis/operator/v1alpha1/openshiftpipelinesascode_defaults_test.go
  pkg/reconciler/openshift/openshiftpipelinesascode/testdata/test-additional-pac-cm.yaml
  pkg/reconciler/openshift/openshiftpipelinesascode/testdata/test-expected-additional-pac-cm.yaml
  pkg/reconciler/openshift/openshiftpipelinesascode/transform.go
  pkg/reconciler/openshift/openshiftpipelinesascode/transform_test.go
  vendor/github.com/openshift-pipelines/pipelines-as-code/pkg/hub/vars/types.go
  vendor/github.com/openshift-pipelines/pipelines-as-code/pkg/params/settings/config.go
  vendor/github.com/openshift-pipelines/pipelines-as-code/pkg/params/settings/convert.go
  vendor/github.com/openshift-pipelines/pipelines-as-code/pkg/params/settings/default.go
  vendor/modules.txt
Labels: approved, release-note, size/L

#2904 Add a preupgrade function to update PAC settings
  pkg/reconciler/shared/tektonconfig/upgrade/pre_upgrade.go
  pkg/reconciler/shared/tektonconfig/upgrade/pre_upgrade_test.go
  pkg/reconciler/shared/tektonconfig/upgrade/upgrade.go
Labels: approved, lgtm, release-note, size/L

#2877 Add Route support for Tekton Results
  cmd/openshift/operator/kodata/static/tekton-results/route-rbac/rbac.yaml
  config/openshift/base/role.yaml
  pkg/apis/operator/v1alpha1/tektonresult_defaults.go
  pkg/apis/operator/v1alpha1/tektonresult_defaults_test.go
  pkg/apis/operator/v1alpha1/tektonresult_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/openshift/tektonresult/extension.go
  pkg/reconciler/openshift/tektonresult/extension_test.go
  pkg/reconciler/openshift/tektonresult/testdata/static/tekton-results/route-rbac/rbac.yaml
Labels: kind/feature, approved, lgtm, release-note, ok-to-test, size/L

#2909 Add AddConfiguration transformation in Results
  pkg/reconciler/kubernetes/tektonresult/transform.go
  pkg/reconciler/kubernetes/tektonresult/transform_test.go
Labels: approved, lgtm, size/M, release-note
