Repository tektoncd/operator, pull requests merged in 2025-03, with the labels that each got.

#2614 fix image repositories for helm chart
  charts/tekton-operator/Chart.yaml
  charts/tekton-operator/templates/_helpers.tpl
Labels: size/S, release-note

#2617 [release-v0.75.x]Update SHA for the registry images
  cmd/openshift/operator/kodata/static/tekton-results/internal-db/db.yaml
  config/openshift/base/operator.yaml
  operatorhub/openshift/config.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
Labels: approved, lgtm, size/M, release-note

#2619 Update rhel8 to rhel9 for skopeo
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
Labels: approved, size/XS, lgtm, release-note

#2620 Update kn image from client-kn-rhel8 to kn-client-kn-rhel8
  config/openshift/base/operator.yaml
  hack/openshift/update-image-sha.sh
  operatorhub/openshift/config.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
Labels: approved, lgtm, size/S, release-note

#2621 [main] Update kn image from client-kn-rhel8 to kn-client-kn-rhel8
  config/openshift/base/operator.yaml
  hack/openshift/update-image-sha.sh
  operatorhub/openshift/config.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
Labels: approved, lgtm, size/S, release-note

#2602 fix release script and release cheat sheet
  hack/release-setup-branch.sh
  hack/release.sh
  tekton/release-cheat-sheet.md
Labels: approved, lgtm, release-note, size/L

#2400 Add TektonResult to TektonConfig doc
  docs/TektonConfig.md
  docs/TektonResult.md
Labels: approved, lgtm, release-note, size/L

#2622 Update Result API container env
  pkg/reconciler/kubernetes/tektonresult/testdata/api-deployment-env.yaml
  pkg/reconciler/kubernetes/tektonresult/transform.go
  pkg/reconciler/kubernetes/tektonresult/transform_test.go
Labels: kind/bug, approved, lgtm, release-note, size/L

#2633 enforce stricter securityContext rules on operator and webhook contai…
  config/kubernetes/base/operator.yaml
  config/kubernetes/base/webhook.yaml
  config/openshift/base/operator.yaml
  config/openshift/base/webhook.yaml
Labels: approved, lgtm, size/M, release-note

#2642 fix kubernetes_min_version initial value on the operator openshift ba…
  config/openshift/base/operator.yaml
  pkg/reconciler/common/transformer_inject_envar_test.go
Labels: approved, size/XS, lgtm, release-note

#2641 Add envKeys for git-init image
  operatorhub/openshift/config.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
Labels: approved, lgtm, release-note, size/L

#2630 Fix upgrade deadlock in Pipeline and Triggers
  pkg/reconciler/common/deadlockbreaker.go
  pkg/reconciler/common/deadlockbreaker_test.go
  pkg/reconciler/kubernetes/tektonpipeline/reconcile.go
  pkg/reconciler/kubernetes/tektontrigger/reconcile.go
Labels: approved, lgtm, release-note, size/L

#2640 fix releases.md
  releases.md
Labels: approved, lgtm, size/M, release-note

#2631 add anithapriyanatarajan and mbpavan to reviewers
  OWNERS
Labels: approved, size/XS, lgtm, release-note

#2659 Updates Makefile to be more descriptive
  Makefile
Labels: approved, lgtm, size/M, release-note
