Repository tektoncd/operator, pull requests merged in 2025-08, with the labels that each got.

#2814 fix(openshift git resolver): mount the trusted-ca-configmap into component's system ca store in Openshift
  docs/TektonOperator.md
  pkg/reconciler/common/certificates.go
  pkg/reconciler/openshift/common/cabundle.go
  pkg/reconciler/openshift/common/cabundle_test.go
  pkg/reconciler/openshift/openshiftpipelinesascode/transform.go
  pkg/reconciler/openshift/tektonchain/extension.go
  pkg/reconciler/openshift/tektonpipeline/extension.go
  pkg/reconciler/openshift/tektonresult/extension.go
  pkg/reconciler/openshift/tektontrigger/extension.go
  test/e2e/openshift/openshiftpipelinesascode_test.go
  test/e2e/openshift/tektonaddondeployment_test.go
  test/e2e/openshift/transformers_test.go
Labels: approved, lgtm, release-note-action-required, size/L

#2824 ADD: buildah-ns task as a part of openshift-pipelines namespace
  hack/openshift/fetch-tektoncd-catalog-tasks.sh
Labels: approved, lgtm, size/S, ok-to-test

#2825 Update OPC task image reference in OpenShift config
  operatorhub/openshift/config.yaml
Labels: approved, size/XS, lgtm, ok-to-test

#2819 Delete default tekton results tls secret during pre upgrade
  pkg/reconciler/shared/tektonconfig/upgrade/pre_upgrade.go
  pkg/reconciler/shared/tektonconfig/upgrade/upgrade.go
Labels: approved, lgtm, size/M, release-note

#2837 update s2i image
  operatorhub/openshift/config.yaml
Labels: approved, size/XS, lgtm, release-note

#2850 fix release cheat
  tekton/release-cheat-sheet.md
Labels: approved, size/XS, lgtm, release-note

#2859 docs: airgap images update for instance installed
  docs/AirGapImageConfiguration.md
Labels: approved, size/XS, lgtm, release-note, ok-to-test

#2831 Optimize proxy webhook performance by eliminating API calls during pod admission
  pkg/reconciler/common/certificates.go
  pkg/reconciler/common/certificates_test.go
  pkg/reconciler/proxy/proxy.go
  pkg/reconciler/proxy/proxy_test.go
Labels: approved, lgtm, release-note, ok-to-test, size/L

#2852 logging: demote high-frequency Info logs to Debug across controllers
  pkg/reconciler/kubernetes/manualapprovalgate/controller.go
  pkg/reconciler/kubernetes/tektonchain/controller.go
  pkg/reconciler/kubernetes/tektondashboard/controller.go
  pkg/reconciler/kubernetes/tektonhub/controller.go
  pkg/reconciler/kubernetes/tektoninstallerset/controller.go
  pkg/reconciler/kubernetes/tektoninstallerset/install.go
  pkg/reconciler/kubernetes/tektoninstallerset/tektoninstallerset.go
  pkg/reconciler/kubernetes/tektonpipeline/controller.go
  pkg/reconciler/kubernetes/tektonpipeline/reconcile.go
  pkg/reconciler/kubernetes/tektonpruner/controller.go
  pkg/reconciler/kubernetes/tektonresult/controller.go
  pkg/reconciler/kubernetes/tektontrigger/controller.go
  pkg/reconciler/openshift/openshiftpipelinesascode/controller.go
  pkg/reconciler/openshift/tektonaddon/controller.go
  pkg/reconciler/shared/tektonconfig/controller.go
  pkg/reconciler/shared/tektonconfig/tektonconfig.go
Labels: approved, lgtm, release-note, size/L

#2861 add Andrew Thorp as reviewer
  OWNERS
Labels: approved, size/XS, lgtm, release-note

#2864 fix(openshift): deduplicate system ca-bundle volumes and mounts
  pkg/reconciler/common/certificates.go
  pkg/reconciler/common/utils.go
  pkg/reconciler/common/utils_test.go
  pkg/reconciler/openshift/common/cabundle.go
  pkg/reconciler/openshift/common/cabundle_test.go
Labels: approved, lgtm, release-note, size/L

#2870 [release-v0.77.x] fix(openshift): deduplicate system ca-bundle volumes and mounts
  pkg/reconciler/common/certificates.go
  pkg/reconciler/common/utils.go
  pkg/reconciler/common/utils_test.go
  pkg/reconciler/openshift/common/cabundle.go
  pkg/reconciler/openshift/common/cabundle_test.go
Labels: approved, lgtm, release-note, ok-to-test, size/L
