Repository tektoncd/operator, pull requests merged in 2025-05, with the labels that each got.

#2707 ADD: OPC task as a part of openshift-pipelines namespace
  config/openshift/base/operator.yaml
  operatorhub/openshift/config.yaml
Labels: approved, lgtm, size/S, release-note, ok-to-test

#2708 Update Hub CR to add the targetNamespace
  config/crs/kubernetes/hub/operator_v1alpha1_hub_cr.yaml
  config/crs/openshift/hub/operator_v1alpha1_hub_cr.yaml
Labels: approved, size/XS, lgtm, release-note

#2703 fix typo
  docs/OpenShiftPipelinesAsCode.md
Labels: approved, size/XS, lgtm, release-note-none, ok-to-test

#2716 update cache stepaction version to 0.2.0 and container tasks to 0.7.0
  hack/openshift/fetch-tektoncd-catalog-tasks.sh
Labels: approved, lgtm, size/S, release-note, ok-to-test

#2717 Corrected comment for StartMainWithSelectedControllers and moved copyright header
  pkg/reconciler/platform/platform.go
Labels: approved, lgtm, size/M, release-note-none

#2725 fix namespace label patching to safely add reconciled label only
  pkg/reconciler/openshift/tektonconfig/rbac.go
Labels: approved, lgtm, size/M, release-note-none, ok-to-test

#2724 Support custom DB secret in Results
  docs/TektonConfig.md
  docs/TektonResult.md
  pkg/apis/operator/v1alpha1/tektonresult_types.go
  pkg/reconciler/kubernetes/tektonresult/tektonresult.go
  pkg/reconciler/kubernetes/tektonresult/transform.go
  pkg/reconciler/kubernetes/tektonresult/transform_test.go
  test/e2e/kubernetes/tektonresultdeployment_test.go
Labels: approved, lgtm, release-note, size/XL

#2729 Fix subpath capitalisation
  tekton/operator-release-pipeline.yaml
Labels: approved, lgtm, size/S, release-note, kind/misc

#2714 Add html_url to github-push CTB to fix clone issue
  cmd/openshift/operator/kodata/tekton-addon/addons/01-clustertriggerbindings/github.yaml
Labels: approved, size/XS, lgtm, release-note

#2732 Fix the rbac for ecosystem tasks and stepactions
  cmd/openshift/operator/kodata/tekton-addon/addons/06-ecosystem/stepactions/role.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/06-ecosystem/stepactions/rolebinding.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/06-ecosystem/tasks/role.yaml
  cmd/openshift/operator/kodata/tekton-addon/addons/06-ecosystem/tasks/rolebinding.yaml
Labels: kind/bug, approved, lgtm, size/S, release-note

#2616 Convert result watcher deployment to statefulset ordinals
  docs/TektonConfig.md
  docs/TektonResult.md
  pkg/apis/operator/v1alpha1/tektonresult_types.go
  pkg/apis/operator/v1alpha1/tektonresult_validation.go
  pkg/apis/operator/v1alpha1/tektonresult_validation_test.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/common/transformers.go
  pkg/reconciler/kubernetes/tektonresult/controller.go
  pkg/reconciler/kubernetes/tektonresult/installerset.go
  pkg/reconciler/kubernetes/tektonresult/metrics.go
  pkg/reconciler/kubernetes/tektonresult/tektonresult.go
  pkg/reconciler/kubernetes/tektonresult/transform.go
  pkg/reconciler/kubernetes/tektonresult/transform_test.go
  pkg/reconciler/shared/tektonconfig/result/result.go
  test/e2e/kubernetes/tektonresultstatefulset_test.go
  test/resources/tektonresults.go
Labels: approved, lgtm, release-note, ok-to-test, size/L

#2738 Update config.yaml with correct envKey for git-init
  docs/AirGapImageConfiguration.md
  operatorhub/openshift/config.yaml
Labels: size/XS, lgtm, release-note
