Repository tektoncd/operator, pull requests merged in 2025-04, with the labels that each got.

#2624 add statefulset feature to tekton chains controller
  pkg/apis/operator/v1alpha1/const.go
  pkg/apis/operator/v1alpha1/performance_types.go
  pkg/apis/operator/v1alpha1/performance_validation.go
  pkg/apis/operator/v1alpha1/performance_validation_test.go
  pkg/apis/operator/v1alpha1/tektonchain_types.go
  pkg/apis/operator/v1alpha1/tektonchain_validation.go
  pkg/apis/operator/v1alpha1/tektonpipeline_types.go
  pkg/apis/operator/v1alpha1/tektonpipeline_validation.go
  pkg/apis/operator/v1alpha1/tektonpipeline_validation_test.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/common/testdata/test-convert-chain-deployment-to-statefulset.yaml
  pkg/reconciler/common/transformers.go
  pkg/reconciler/common/transformers_test.go
  pkg/reconciler/kubernetes/tektonchain/controller.go
  pkg/reconciler/kubernetes/tektonchain/installerset.go
  pkg/reconciler/kubernetes/tektonchain/metrics.go
  pkg/reconciler/kubernetes/tektonchain/tektonchain.go
  pkg/reconciler/kubernetes/tektonchain/transform.go
  pkg/reconciler/kubernetes/tektonchain/transform_test.go
  pkg/reconciler/kubernetes/tektoninstallerset/client/cleanup.go
  pkg/reconciler/kubernetes/tektoninstallerset/client/labels.go
  pkg/reconciler/kubernetes/tektoninstallerset/client/obsolete_sets.go
  pkg/reconciler/kubernetes/tektonpipeline/transform.go
  pkg/reconciler/kubernetes/tektonpipeline/transform_test.go
  test/resources/tektonpipelines.go
Labels: approved, lgtm, release-note, size/XXL

#2672 Move Results config options from ResultAPIProperties to Result struct
  pkg/apis/operator/v1alpha1/tektonresult_defaults_test.go
  pkg/apis/operator/v1alpha1/tektonresult_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/kubernetes/tektonresult/filter_test.go
  pkg/reconciler/kubernetes/tektonresult/transform_test.go
  pkg/reconciler/shared/tektonconfig/result/result.go
  pkg/reconciler/shared/tektonconfig/upgrade/pre_upgrade.go
Labels: approved, lgtm, release-note, size/L

#2674 Improve operator logging by implementing proper log levels and context
  pkg/reconciler/kubernetes/tektoninstallerset/install.go
Labels: approved, lgtm, release-note, size/L

#2681 Add ghcr.io migration banner to README.md.
  README.md
Labels: approved, size/XS, lgtm, kind/documentation, release-note, ok-to-test

#2679 Move TektonConfig Update to UpdateStatus to prevent spec changes
  pkg/reconciler/common/common.go
  pkg/reconciler/shared/tektonconfig/tektonconfig.go
Labels: approved, lgtm, size/S, release-note

#2680 Add LoggingPluginMultipartRegex for ResultsAPI
  pkg/apis/operator/v1alpha1/tektonresult_types.go
  pkg/reconciler/kubernetes/tektonresult/testdata/api-config.yaml
  pkg/reconciler/kubernetes/tektonresult/transform_test.go
Labels: approved, size/XS, lgtm, release-note

#2692 set kubernetes_min_version on webhook
  config/openshift/base/webhook.yaml
Labels: size/XS, lgtm, release-note

#2693 set kubernetes_min_version on openshift-pipelines-operator-cluster-operations
  config/openshift/base/operator.yaml
Labels: size/XS, release-note

#2694 [openshift] set kubernetes_min_version on webhook and cluster-operations container
  config/openshift/base/operator.yaml
  config/openshift/base/webhook.yaml
Labels: approved, size/XS, lgtm, release-note

#2701 Update SHA for registry images
  config/openshift/base/operator.yaml
  operatorhub/openshift/config.yaml
  operatorhub/openshift/release-artifacts/bundle/manifests/openshift-pipelines-operator-rh.clusterserviceversion.yaml
Labels: approved, lgtm, size/M, release-note
