Repository tektoncd/operator, pull requests merged in 2025-02, with the labels that each got.

#2549 Only modify chains properties on upgrade
  pkg/reconciler/shared/tektonconfig/upgrade/pre_upgrade.go
Labels: approved, lgtm

#2547 Fix fetch-component-release task in nightly release
  tekton/task-fetch-components.yaml
Labels: approved, size/XS, lgtm, release-note, kind/misc

#2551 Add tekton-caches stepActions into operator catalog
  hack/openshift/fetch-tektoncd-catalog-tasks.sh
  operatorhub/openshift/config.yaml
Labels: approved, lgtm, size/S, release-note, ok-to-test

#2398 Add Results configuration in tekton config
  pkg/apis/operator/v1alpha1/tektonconfig_defaults.go
  pkg/apis/operator/v1alpha1/tektonconfig_types.go
  pkg/apis/operator/v1alpha1/tektonconfig_validation.go
  pkg/apis/operator/v1alpha1/tektonresult_defaults.go
  pkg/apis/operator/v1alpha1/tektonresult_types.go
  pkg/apis/operator/v1alpha1/zz_generated.deepcopy.go
  pkg/reconciler/kubernetes/tektoninstallerset/client/list.go
  pkg/reconciler/kubernetes/tektonresult/tektonresult.go
  pkg/reconciler/openshift/tektonresult/extension.go
  pkg/reconciler/shared/tektonconfig/controller.go
  pkg/reconciler/shared/tektonconfig/result/result.go
  pkg/reconciler/shared/tektonconfig/result/result_test.go
  pkg/reconciler/shared/tektonconfig/tektonconfig.go
Labels: approved, lgtm, release-note, size/XL, ok-to-test

#2565 update config yaml with new image pac cli and sidecarlogresults pipeline info
  operatorhub/openshift/config.yaml
Labels: approved, lgtm, size/M, release-note

#2557 Support addition of new containers provided as options
  docs/TektonConfig.md
  pkg/reconciler/common/testdata/test-additional-options-test-runtimeclassname-deployment-add-container.yaml
  pkg/reconciler/common/testdata/test-additional-options-test-runtimeclassname-deployment-add-initcontainer.yaml
  pkg/reconciler/common/testdata/test-additional-options-test-runtimeclassname-statefulset-add-container.yaml
  pkg/reconciler/common/testdata/test-additional-options-test-runtimeclassname-statefulset-add-initcontainer.yaml
  pkg/reconciler/common/transformer_additional_options.go
  pkg/reconciler/common/transformer_additional_options_test.go
Labels: approved, lgtm, release-note, size/XL

#2545 Add proxy in the ConsolePlugin
  cmd/openshift/operator/kodata/static/tekton-config/00-console-plugin/pipeline_console_plugin.yaml
Labels: approved, size/XS, lgtm, release-note

#2572 Update task-containers version from 0.5.1 to 0.6.0
  hack/openshift/fetch-tektoncd-catalog-tasks.sh
Labels: approved, lgtm, size/S, release-note

#2570 Fix image pull error due to missing sha256
  charts/tekton-operator/templates/_helpers.tpl
  charts/tekton-operator/values.yaml
Labels: approved, lgtm, size/S, release-note, ok-to-test

#2573 Update tekton-cache stepAction release versions
  hack/openshift/fetch-tektoncd-catalog-tasks.sh
Labels: kind/feature, approved, size/XS, lgtm, release-note, ok-to-test

#2595 docs: correct hyperlink error in results component documentation
  docs/TektonResult.md
Labels: approved, size/XS, lgtm, release-note-none

#2597 [release-v0.75.x] bump chart version to v0.75.0
  charts/tekton-operator/Chart.yaml
  charts/tekton-operator/templates/kubernetes-crds.yaml
  charts/tekton-operator/templates/openshift-crds.yaml
Labels: approved, lgtm, size/M, release-note

#2598 add l-qing as reviewer
  OWNERS
Labels: approved, size/XS, lgtm, release-note

#2610 Preserve the existing TektonResult CR configuration
  pkg/reconciler/shared/tektonconfig/upgrade/pre_upgrade.go
  pkg/reconciler/shared/tektonconfig/upgrade/upgrade.go
Labels: approved, lgtm, size/M, release-note
